/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersUpdateCustomer } from "../../funcs/customersUpdateCustomer.js";
import { UpdateCustomerRequestRequest$zodSchema } from "../../models/updatecustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateCustomerRequestRequest$zodSchema,
};

export const tool$customersUpdateCustomer: ToolDefinition<typeof args> = {
  name: "update-customer",
  description: `Update customer

Use when updating customer details (e.g. name, email, or metadata). Identify by id or external_customer_id.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersUpdateCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
