/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomerUpcomingGrants } from "../../funcs/customersGetCustomerUpcomingGrants.js";
import { GetCustomerUpcomingGrantsRequest$zodSchema } from "../../models/getcustomerupcominggrantsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerUpcomingGrantsRequest$zodSchema,
};

export const tool$customersGetCustomerUpcomingGrants: ToolDefinition<
  typeof args
> = {
  name: "get-customer-upcoming-grants",
  description: `Get upcoming credit grant applications

Use when showing upcoming or pending credits for a customer (e.g. in a portal or for forecasting).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomerUpcomingGrants(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
