/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomerUsageSummary } from "../../funcs/customersGetCustomerUsageSummary.js";
import { GetCustomerUsageSummaryRequest$zodSchema } from "../../models/getcustomerusagesummaryop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerUsageSummaryRequest$zodSchema.optional(),
};

export const tool$customersGetCustomerUsageSummary: ToolDefinition<
  typeof args
> = {
  name: "get-customer-usage-summary",
  description: `Get customer usage summary

Use when showing a customer's usage (e.g. portal or overage alerts). Identify by customer_id or customer_lookup_key; supports filters.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomerUsageSummary(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
