/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomerByExternalId } from "../../funcs/customersGetCustomerByExternalId.js";
import { GetCustomerByExternalIdRequest$zodSchema } from "../../models/getcustomerbyexternalidop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerByExternalIdRequest$zodSchema,
};

export const tool$customersGetCustomerByExternalId: ToolDefinition<
  typeof args
> = {
  name: "get-customer-by-external-id",
  description: `Get customer by external ID

Use when resolving a customer by your app's id (e.g. from your user table). Ideal for integrations that key by external id.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomerByExternalId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
