/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersCreateCustomer } from "../../funcs/customersCreateCustomer.js";
import { CreateCustomerRequest$zodSchema } from "../../models/createcustomerrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateCustomerRequest$zodSchema.describe(`Customer`),
};

export const tool$customersCreateCustomer: ToolDefinition<typeof args> = {
  name: "create-customer",
  description: `Create customer

Use when onboarding a new billing customer (e.g. sign-up or CRM sync). Ideal for linking via external_customer_id to your app's user id.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersCreateCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
