/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomer } from "../../funcs/customersGetCustomer.js";
import { GetCustomerRequest$zodSchema } from "../../models/getcustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerRequest$zodSchema,
};

export const tool$customersGetCustomer: ToolDefinition<typeof args> = {
  name: "get-customer",
  description: `Get customer

Use when you need to load a single customer (e.g. for a billing portal or to attach a subscription).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
