/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersListCustomerPaymentMethods } from "../../funcs/customersListCustomerPaymentMethods.js";
import { ListCustomerPaymentMethodsRequest$zodSchema } from "../../models/listcustomerpaymentmethodsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListCustomerPaymentMethodsRequest$zodSchema,
};

export const tool$customersListCustomerPaymentMethods: ToolDefinition<
  typeof args
> = {
  name: "list-customer-payment-methods",
  description: `List customer payment methods

Use when you need a customer's saved payment methods across every connected gateway, including whether each can be auto-charged. Only gateways that can list saved methods are included.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersListCustomerPaymentMethods(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
