/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersDeleteCustomer } from "../../funcs/customersDeleteCustomer.js";
import { DeleteCustomerRequest$zodSchema } from "../../models/deletecustomerop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeleteCustomerRequest$zodSchema,
};

export const tool$customersDeleteCustomer: ToolDefinition<typeof args> = {
  name: "delete-customer",
  description: `Delete customer

Use when removing a customer (e.g. GDPR or churn). Returns 204 No Content on success.`,
  scopes: ["delete"],
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersDeleteCustomer(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
