/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGetCustomerEntitlements } from "../../funcs/customersGetCustomerEntitlements.js";
import { GetCustomerEntitlementsRequest$zodSchema } from "../../models/getcustomerentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetCustomerEntitlementsRequest$zodSchema,
};

export const tool$customersGetCustomerEntitlements: ToolDefinition<
  typeof args
> = {
  name: "get-customer-entitlements",
  description: `Get customer entitlements

Use when checking what a customer can access (e.g. feature gating or usage limits). Supports optional filters (feature_ids, subscription_ids).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await customersGetCustomerEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
