/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsIngestEvent } from "../../funcs/eventsIngestEvent.js";
import { IngestEventRequest$zodSchema } from "../../models/ingesteventrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: IngestEventRequest$zodSchema.describe(`Event data`),
};

export const tool$eventsIngestEvent: ToolDefinition<typeof args> = {
  name: "ingest-event",
  description: `Ingest event

Use when sending a single usage event from your app (e.g. one API call or one GB stored). Events are processed asynchronously; returns 202 with event_id.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsIngestEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
