/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetHuggingfaceInferenceData } from "../../funcs/eventsGetHuggingfaceInferenceData.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$eventsGetHuggingfaceInferenceData: ToolDefinition = {
  name: "get-huggingface-inference-data",
  description: `Get Hugging Face inference data

Use when fetching Hugging Face inference usage or billing data (e.g. for HF-specific reporting or reconciliation).`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  tool: async (client, ctx) => {
    const [result] = await eventsGetHuggingfaceInferenceData(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
