/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetEvent } from "../../funcs/eventsGetEvent.js";
import { GetEventRequest$zodSchema } from "../../models/geteventop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventRequest$zodSchema,
};

export const tool$eventsGetEvent: ToolDefinition<typeof args> = {
  name: "get-event",
  description: `Get event

Use when debugging a specific event (e.g. why it failed or how it was aggregated). Includes processing status and debug info.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsGetEvent(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
