/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetUsageStatistics } from "../../funcs/eventsGetUsageStatistics.js";
import { GetUsageRequest$zodSchema } from "../../models/getusagerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUsageRequest$zodSchema.describe(`Request body`),
};

export const tool$eventsGetUsageStatistics: ToolDefinition<typeof args> = {
  name: "get-usage-statistics",
  description: `Get usage statistics

Use when building usage reports or dashboards across events. Supports filters and grouping; defaults to last 7 days if no range provided.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsGetUsageStatistics(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
