/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsGetUsageByMeter } from "../../funcs/eventsGetUsageByMeter.js";
import { GetUsageByMeterRequest$zodSchema } from "../../models/getusagebymeterrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetUsageByMeterRequest$zodSchema.describe(`Request body`),
};

export const tool$eventsGetUsageByMeter: ToolDefinition<typeof args> = {
  name: "get-usage-by-meter",
  description: `Get usage by meter

Use when showing usage for a specific meter (e.g. dashboard or overage check). Supports time range, filters, and grouping by customer or subscription.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsGetUsageByMeter(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
