/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsListRawEvents } from "../../funcs/eventsListRawEvents.js";
import { GetEventsRequest$zodSchema } from "../../models/geteventsrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetEventsRequest$zodSchema.describe(`Request body`),
};

export const tool$eventsListRawEvents: ToolDefinition<typeof args> = {
  name: "list-raw-events",
  description: `List raw events

Use when debugging ingestion or exporting raw event data (e.g. support or audit). Returns a paginated list; supports time range and sorting.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsListRawEvents(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
