/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventsIngestEventsBulk } from "../../funcs/eventsIngestEventsBulk.js";
import { BulkIngestEventRequest$zodSchema } from "../../models/bulkingesteventrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: BulkIngestEventRequest$zodSchema.describe(`Event data`),
};

export const tool$eventsIngestEventsBulk: ToolDefinition<typeof args> = {
  name: "ingest-events-bulk",
  description: `Bulk ingest events

Use when batching usage events (e.g. backfill or high-volume ingestion). More efficient than single event calls; returns 202 when accepted.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await eventsIngestEventsBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
