/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesVoidInvoice } from "../../funcs/invoicesVoidInvoice.js";
import { VoidInvoiceRequest$zodSchema } from "../../models/voidinvoiceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: VoidInvoiceRequest$zodSchema,
};

export const tool$invoicesVoidInvoice: ToolDefinition<typeof args> = {
  name: "void-invoice",
  description: `Void invoice

Use when cancelling an invoice (e.g. order cancelled or duplicate). Only unpaid invoices can be voided.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesVoidInvoice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
