/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesUpdateInvoicePaymentStatus } from "../../funcs/invoicesUpdateInvoicePaymentStatus.js";
import { UpdateInvoicePaymentStatusRequest$zodSchema } from "../../models/updateinvoicepaymentstatusop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateInvoicePaymentStatusRequest$zodSchema,
};

export const tool$invoicesUpdateInvoicePaymentStatus: ToolDefinition<
  typeof args
> = {
  name: "update-invoice-payment-status",
  description: `Update invoice payment status

Use when reconciling payment status from an external gateway or manual entry (e.g. mark paid after bank confirmation).`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesUpdateInvoicePaymentStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
