/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesTriggerInvoiceCommsWebhook } from "../../funcs/invoicesTriggerInvoiceCommsWebhook.js";
import { TriggerInvoiceCommsWebhookRequest$zodSchema } from "../../models/triggerinvoicecommswebhookop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: TriggerInvoiceCommsWebhookRequest$zodSchema,
};

export const tool$invoicesTriggerInvoiceCommsWebhook: ToolDefinition<
  typeof args
> = {
  name: "trigger-invoice-comms-webhook",
  description: `Trigger invoice communication webhook

Use when sending an invoice to the customer (e.g. trigger email or Slack). Payload includes full invoice details for your integration.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesTriggerInvoiceCommsWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
