/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesUpdateInvoice } from "../../funcs/invoicesUpdateInvoice.js";
import { UpdateInvoiceRequestRequest$zodSchema } from "../../models/updateinvoiceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateInvoiceRequestRequest$zodSchema,
};

export const tool$invoicesUpdateInvoice: ToolDefinition<typeof args> = {
  name: "update-invoice",
  description: `Update invoice

Use when updating invoice metadata or due date (e.g. PDF URL, net terms). For paid invoices only safe fields can be updated.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesUpdateInvoice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
