/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetInvoicePdf } from "../../funcs/invoicesGetInvoicePdf.js";
import { GetInvoicePdfRequest$zodSchema } from "../../models/getinvoicepdfop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetInvoicePdfRequest$zodSchema,
};

export const tool$invoicesGetInvoicePdf: ToolDefinition<typeof args> = {
  name: "get-invoice-pdf",
  description: `Get invoice PDF

Use when delivering an invoice PDF to the customer (e.g. email attachment or download). Use url=true for a presigned URL instead of binary. Use force_generate=true to regenerate and re-upload the PDF even if one already exists in S3.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetInvoicePdf(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
