/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesAttemptInvoicePayment } from "../../funcs/invoicesAttemptInvoicePayment.js";
import { AttemptInvoicePaymentRequest$zodSchema } from "../../models/attemptinvoicepaymentop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AttemptInvoicePaymentRequest$zodSchema,
};

export const tool$invoicesAttemptInvoicePayment: ToolDefinition<typeof args> = {
  name: "attempt-invoice-payment",
  description: `Attempt invoice payment

Use when paying an invoice with the customer's wallet balance (e.g. prepaid credits or balance applied at checkout).`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesAttemptInvoicePayment(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
