/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetInvoicePreview } from "../../funcs/invoicesGetInvoicePreview.js";
import { GetPreviewInvoiceRequest$zodSchema } from "../../models/getpreviewinvoicerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPreviewInvoiceRequest$zodSchema.describe(
    `Preview Invoice Request`,
  ),
};

export const tool$invoicesGetInvoicePreview: ToolDefinition<typeof args> = {
  name: "get-invoice-preview",
  description: `Get invoice preview

Use when showing a customer what they will be charged (e.g. preview before checkout or plan change). No invoice is created.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesGetInvoicePreview(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
