/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesCreateInvoice } from "../../funcs/invoicesCreateInvoice.js";
import { CreateInvoiceRequest$zodSchema } from "../../models/createinvoicerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateInvoiceRequest$zodSchema.describe(`Invoice details`),
};

export const tool$invoicesCreateInvoice: ToolDefinition<typeof args> = {
  name: "create-invoice",
  description: `Create one-off invoice

Use when creating a manual or one-off invoice (e.g. custom charge or non-recurring billing). Invoice is created in draft; finalize when ready.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesCreateInvoice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
