/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesExecuteInvoiceModify } from "../../funcs/invoicesExecuteInvoiceModify.js";
import { ExecuteInvoiceModifyRequestRequest$zodSchema } from "../../models/executeinvoicemodifyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExecuteInvoiceModifyRequestRequest$zodSchema,
};

export const tool$invoicesExecuteInvoiceModify: ToolDefinition<typeof args> = {
  name: "execute-invoice-modify",
  description: `Execute invoice modification

Execute a modification on a draft or finalized invoice. Supports line item changes: add (bulk), update (one line item per call; the edit is versioned, so the line item id changes), and remove (bulk, soft delete). Totals are recalculated from the remaining line items; a manual edit marks the invoice as manually edited, which disables recompute. Modifying a FINALIZED invoice voids it and recreates it as a draft copy carrying all current data (description, billing period, due date, metadata, line items); the modification lands on the copy and the response returns the new draft — chain subsequent calls to the returned invoice id; a call that still targets the voided original is rejected with an error naming the replacement.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesExecuteInvoiceModify(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
