/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesQueryInvoice } from "../../funcs/invoicesQueryInvoice.js";
import { InvoiceFilter$zodSchema } from "../../models/invoicefilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: InvoiceFilter$zodSchema.describe(`Filter`),
};

export const tool$invoicesQueryInvoice: ToolDefinition<typeof args> = {
  name: "query-invoice",
  description: `Query invoices

Use when listing or searching invoices (e.g. admin view or customer history). Returns a paginated list; supports filtering by customer, status, date range.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await invoicesQueryInvoice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
