/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansQueryPlan } from "../../funcs/plansQueryPlan.js";
import { PlanFilter$zodSchema } from "../../models/planfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PlanFilter$zodSchema.describe(`Filter`),
};

export const tool$plansQueryPlan: ToolDefinition<typeof args> = {
  name: "query-plan",
  description: `Query plans

Use when listing or searching plans (e.g. plan picker or admin catalog). Returns a paginated list; supports filtering and sorting.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansQueryPlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
