/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansDeletePlan } from "../../funcs/plansDeletePlan.js";
import { DeletePlanRequest$zodSchema } from "../../models/deleteplanop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePlanRequest$zodSchema,
};

export const tool$plansDeletePlan: ToolDefinition<typeof args> = {
  name: "delete-plan",
  description: `Delete plan

Use when retiring a plan (e.g. end-of-life). Existing subscriptions may be affected. Returns 200 with success message.`,
  scopes: ["delete"],
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansDeletePlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
