/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansGetPlan } from "../../funcs/plansGetPlan.js";
import { GetPlanRequest$zodSchema } from "../../models/getplanop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetPlanRequest$zodSchema,
};

export const tool$plansGetPlan: ToolDefinition<typeof args> = {
  name: "get-plan",
  description: `Get plan

Use when you need to load a single plan (e.g. for display or to create a subscription).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansGetPlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
