/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansClonePlan } from "../../funcs/plansClonePlan.js";
import { ClonePlanRequestRequest$zodSchema } from "../../models/cloneplanop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ClonePlanRequestRequest$zodSchema,
};

export const tool$plansClonePlan: ToolDefinition<typeof args> = {
  name: "clone-plan",
  description: `Clone a plan

Clone an existing plan, copying its active prices, published entitlements, and published credit grants`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansClonePlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
