/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { plansCreatePlan } from "../../funcs/plansCreatePlan.js";
import { CreatePlanRequest$zodSchema } from "../../models/createplanrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreatePlanRequest$zodSchema.describe(`Plan configuration`),
};

export const tool$plansCreatePlan: ToolDefinition<typeof args> = {
  name: "create-plan",
  description: `Create plan

Use when defining a new pricing plan (e.g. Free, Pro, Enterprise). Attach prices and entitlements; customers subscribe to plans.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await plansCreatePlan(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
