/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesDeletePrice } from "../../funcs/pricesDeletePrice.js";
import { DeletePriceRequestRequest$zodSchema } from "../../models/deletepriceop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: DeletePriceRequestRequest$zodSchema,
};

export const tool$pricesDeletePrice: ToolDefinition<typeof args> = {
  name: "delete-price",
  description: `Delete price

Use when retiring a price (e.g. end-of-life or replacement). Optional effective date or cascade for subscriptions.`,
  scopes: ["delete"],
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesDeletePrice(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
