/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { pricesCreatePricesBulk } from "../../funcs/pricesCreatePricesBulk.js";
import { CreateBulkPriceRequest$zodSchema } from "../../models/createbulkpricerequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateBulkPriceRequest$zodSchema.describe(
    `Bulk price configuration`,
  ),
};

export const tool$pricesCreatePricesBulk: ToolDefinition<typeof args> = {
  name: "create-prices-bulk",
  description: `Create prices in bulk

Use when creating many prices at once (e.g. importing a catalog or setting up a plan with multiple tiers).`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await pricesCreatePricesBulk(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
