/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionV2 } from "../../funcs/subscriptionsGetSubscriptionV2.js";
import { GetSubscriptionV2Request$zodSchema } from "../../models/getsubscriptionv2op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionV2Request$zodSchema,
};

export const tool$subscriptionsGetSubscriptionV2: ToolDefinition<typeof args> =
  {
    name: "get-subscription-v2",
    description: `Get subscription (V2)

Use when you need a subscription with related data (line items, prices, plan). Supports expand for detailed payloads without extra round-trips.`,
    scopes: ["read"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": true,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsGetSubscriptionV2(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
