/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsListAllSubscriptionSchedules } from "../../funcs/subscriptionsListAllSubscriptionSchedules.js";
import { ListAllSubscriptionSchedulesRequest$zodSchema } from "../../models/listallsubscriptionschedulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListAllSubscriptionSchedulesRequest$zodSchema.optional(),
};

export const tool$subscriptionsListAllSubscriptionSchedules: ToolDefinition<
  typeof args
> = {
  name: "list-all-subscription-schedules",
  description: `List all subscription schedules

Use when listing or searching scheduled changes across subscriptions (e.g. admin view). Returns schedules with optional filtering.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsListAllSubscriptionSchedules(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
