/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsUpdateSubscriptionLineItem } from "../../funcs/subscriptionsUpdateSubscriptionLineItem.js";
import { UpdateSubscriptionLineItemRequestRequest$zodSchema } from "../../models/updatesubscriptionlineitemop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: UpdateSubscriptionLineItemRequestRequest$zodSchema,
};

export const tool$subscriptionsUpdateSubscriptionLineItem: ToolDefinition<
  typeof args
> = {
  name: "update-subscription-line-item",
  description: `Update subscription line item

Use when changing a subscription line item (e.g. quantity or price). Implemented by ending the current line and creating a new one for clean billing.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsUpdateSubscriptionLineItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
