/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsActivateSubscription } from "../../funcs/subscriptionsActivateSubscription.js";
import { ActivateSubscriptionRequest$zodSchema } from "../../models/activatesubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ActivateSubscriptionRequest$zodSchema,
};

export const tool$subscriptionsActivateSubscription: ToolDefinition<
  typeof args
> = {
  name: "activate-subscription",
  description: `Activate draft subscription

Use when turning a draft subscription live (e.g. after collecting payment or completing setup). Once activated, billing and entitlements apply.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsActivateSubscription(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
