/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsExecuteSubscriptionModify } from "../../funcs/subscriptionsExecuteSubscriptionModify.js";
import { ExecuteSubscriptionModifyRequestRequest$zodSchema } from "../../models/executesubscriptionmodifyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExecuteSubscriptionModifyRequestRequest$zodSchema,
};

export const tool$subscriptionsExecuteSubscriptionModify: ToolDefinition<
  typeof args
> = {
  name: "execute-subscription-modify",
  description: `Execute subscription modification

Execute a mid-cycle subscription modification (inheritance, line item change, grouped invoicing, trial end, coupon, tax, a single addon add/remove, or a batch of addon adds and removes settled as one netted document).
Type "quantity_change" is deprecated: use "line_item_change", which changes a fixed charge's quantity, price, or both, with the same proration and checkout behaviour.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsExecuteSubscriptionModify(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
