/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPreviewSubscriptionModify } from "../../funcs/subscriptionsPreviewSubscriptionModify.js";
import { PreviewSubscriptionModifyRequest$zodSchema } from "../../models/previewsubscriptionmodifyop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PreviewSubscriptionModifyRequest$zodSchema,
};

export const tool$subscriptionsPreviewSubscriptionModify: ToolDefinition<
  typeof args
> = {
  name: "preview-subscription-modify",
  description: `Preview subscription modification

Preview the impact of a mid-cycle subscription modification without committing changes.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPreviewSubscriptionModify(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
