/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionSchedule } from "../../funcs/subscriptionsGetSubscriptionSchedule.js";
import { GetSubscriptionScheduleRequest$zodSchema } from "../../models/getsubscriptionscheduleop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionScheduleRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptionSchedule: ToolDefinition<
  typeof args
> = {
  name: "get-subscription-schedule",
  description: `Get subscription schedule

Use when you need to load a single scheduled change (e.g. to show when a plan change or renewal takes effect).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetSubscriptionSchedule(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
