/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsRemoveSubscriptionAddon } from "../../funcs/subscriptionsRemoveSubscriptionAddon.js";
import { RemoveAddonRequest$zodSchema } from "../../models/removeaddonrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: RemoveAddonRequest$zodSchema.describe(`Remove Addon Request`),
};

export const tool$subscriptionsRemoveSubscriptionAddon: ToolDefinition<
  typeof args
> = {
  name: "remove-subscription-addon",
  description: `Remove addon from subscription

Use when removing an add-on from a subscription (e.g. downgrade or opt-out).`,
  scopes: ["delete"],
  annotations: {
    "title": "",
    "destructiveHint": true,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsRemoveSubscriptionAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
