/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsQuerySubscription } from "../../funcs/subscriptionsQuerySubscription.js";
import { SubscriptionFilter$zodSchema } from "../../models/subscriptionfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SubscriptionFilter$zodSchema.describe(`Filter`),
};

export const tool$subscriptionsQuerySubscription: ToolDefinition<typeof args> =
  {
    name: "query-subscription",
    description: `Query subscriptions

Use when listing or searching subscriptions (e.g. admin view or customer subscription list). Returns a paginated list; supports filtering by customer, plan, status.`,
    scopes: ["write"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsQuerySubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
