/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCreateSubscriptionLineItem } from "../../funcs/subscriptionsCreateSubscriptionLineItem.js";
import { CreateSubscriptionLineItemRequestRequest$zodSchema } from "../../models/createsubscriptionlineitemop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateSubscriptionLineItemRequestRequest$zodSchema,
};

export const tool$subscriptionsCreateSubscriptionLineItem: ToolDefinition<
  typeof args
> = {
  name: "create-subscription-line-item",
  description: `Create subscription line item

Use when adding a new charge or seat to a subscription (e.g. extra seat or one-time add). Supports price_id or inline price.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsCreateSubscriptionLineItem(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
