/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsGetSubscriptionEntitlements } from "../../funcs/subscriptionsGetSubscriptionEntitlements.js";
import { GetSubscriptionEntitlementsRequest$zodSchema } from "../../models/getsubscriptionentitlementsop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: GetSubscriptionEntitlementsRequest$zodSchema,
};

export const tool$subscriptionsGetSubscriptionEntitlements: ToolDefinition<
  typeof args
> = {
  name: "get-subscription-entitlements",
  description: `Get subscription entitlements

Use when checking what features or limits a subscription has (e.g. entitlement checks or feature gating). Optional feature_ids to filter.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsGetSubscriptionEntitlements(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
