/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsExecuteSubscriptionPlanChangeV2 } from "../../funcs/subscriptionsExecuteSubscriptionPlanChangeV2.js";
import { ExecuteSubscriptionPlanChangeV2Request$zodSchema } from "../../models/executesubscriptionplanchangev2op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ExecuteSubscriptionPlanChangeV2Request$zodSchema,
};

export const tool$subscriptionsExecuteSubscriptionPlanChangeV2: ToolDefinition<
  typeof args
> = {
  name: "execute-subscription-plan-change-v2",
  description: `Execute a plan change (v2, swap in place)

Change a subscription's plan in place. Subscription id, billing anchor and period bounds are preserved; line items are sliced and settled in one transaction.`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsExecuteSubscriptionPlanChangeV2(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
