/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsPreviewSubscriptionPlanChangeV2 } from "../../funcs/subscriptionsPreviewSubscriptionPlanChangeV2.js";
import { PreviewSubscriptionPlanChangeV2Request$zodSchema } from "../../models/previewsubscriptionplanchangev2op.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: PreviewSubscriptionPlanChangeV2Request$zodSchema,
};

export const tool$subscriptionsPreviewSubscriptionPlanChangeV2: ToolDefinition<
  typeof args
> = {
  name: "preview-subscription-plan-change-v2",
  description: `Preview a plan change (v2, swap in place)

Preview a subscription plan change without writing. Swap-in-place: subscription id, billing anchor and period bounds are preserved.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsPreviewSubscriptionPlanChangeV2(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
