/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsQuerySubscriptionLineItems } from "../../funcs/subscriptionsQuerySubscriptionLineItems.js";
import { SubscriptionLineItemFilter$zodSchema } from "../../models/subscriptionlineitemfilter.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: SubscriptionLineItemFilter$zodSchema.describe(`Filter`),
};

export const tool$subscriptionsQuerySubscriptionLineItems: ToolDefinition<
  typeof args
> = {
  name: "query-subscription-line-items",
  description: `Search subscription line items

List subscription line items with a JSON filter (subscription, customer, price, pagination, expand=prices, etc.).`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsQuerySubscriptionLineItems(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
