/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsAddSubscriptionAddon } from "../../funcs/subscriptionsAddSubscriptionAddon.js";
import { AddAddonRequest$zodSchema } from "../../models/addaddonrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: AddAddonRequest$zodSchema.describe(`Add Addon Request`),
};

export const tool$subscriptionsAddSubscriptionAddon: ToolDefinition<
  typeof args
> = {
  name: "add-subscription-addon",
  description: `Add addon to subscription

Use when adding an optional product or add-on to an existing subscription (e.g. extra storage or support tier).`,
  scopes: ["write"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": false,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsAddSubscriptionAddon(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
