/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsListSubscriptionSchedules } from "../../funcs/subscriptionsListSubscriptionSchedules.js";
import { ListSubscriptionSchedulesRequest$zodSchema } from "../../models/listsubscriptionschedulesop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: ListSubscriptionSchedulesRequest$zodSchema,
};

export const tool$subscriptionsListSubscriptionSchedules: ToolDefinition<
  typeof args
> = {
  name: "list-subscription-schedules",
  description: `List subscription schedules

Use when listing scheduled changes for a subscription (e.g. upcoming plan change or renewal). Returns all schedules for that subscription.`,
  scopes: ["read"],
  annotations: {
    "title": "",
    "destructiveHint": false,
    "idempotentHint": false,
    "openWorldHint": false,
    "readOnlyHint": true,
  },
  args,
  tool: async (client, args, ctx) => {
    const [result] = await subscriptionsListSubscriptionSchedules(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(result.value);
  },
};
