/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCreateSubscription } from "../../funcs/subscriptionsCreateSubscription.js";
import { CreateSubscriptionRequest$zodSchema } from "../../models/createsubscriptionrequest.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CreateSubscriptionRequest$zodSchema.describe(`Subscription Request`),
};

export const tool$subscriptionsCreateSubscription: ToolDefinition<typeof args> =
  {
    name: "create-subscription",
    description: `Create subscription

Use when onboarding a customer to a plan or starting a new subscription. Ideal for draft subscriptions (activate later) or active from start.`,
    scopes: ["write"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsCreateSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
