/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { subscriptionsCancelSubscription } from "../../funcs/subscriptionsCancelSubscription.js";
import { CancelSubscriptionRequestRequest$zodSchema } from "../../models/cancelsubscriptionop.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: CancelSubscriptionRequestRequest$zodSchema,
};

export const tool$subscriptionsCancelSubscription: ToolDefinition<typeof args> =
  {
    name: "cancel-subscription",
    description: `Cancel subscription

Use when a customer churns or downgrades. Supports immediate or end-of-period cancellation and proration. Ideal for self-serve or support-driven cancellations.`,
    scopes: ["write"],
    annotations: {
      "title": "",
      "destructiveHint": false,
      "idempotentHint": false,
      "openWorldHint": false,
      "readOnlyHint": false,
    },
    args,
    tool: async (client, args, ctx) => {
      const [result] = await subscriptionsCancelSubscription(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      return formatResult(result.value);
    },
  };
