/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { TirdadCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import {
  createRegisterTool,
  MCPToolAnnotationFilter,
  registerDynamicTools,
} from "./tools.js";
import { tool$customersCreateCustomer } from "./tools/customersCreateCustomer.js";
import { tool$customersDeleteCustomer } from "./tools/customersDeleteCustomer.js";
import { tool$customersGetCustomer } from "./tools/customersGetCustomer.js";
import { tool$customersGetCustomerByExternalId } from "./tools/customersGetCustomerByExternalId.js";
import { tool$customersGetCustomerEntitlements } from "./tools/customersGetCustomerEntitlements.js";
import { tool$customersGetCustomerEntitlementsByExternalID } from "./tools/customersGetCustomerEntitlementsByExternalID.js";
import { tool$customersGetCustomerUpcomingGrants } from "./tools/customersGetCustomerUpcomingGrants.js";
import { tool$customersGetCustomerUsageSummary } from "./tools/customersGetCustomerUsageSummary.js";
import { tool$customersGetSubscriptionsForCustomer } from "./tools/customersGetSubscriptionsForCustomer.js";
import { tool$customersQueryCustomer } from "./tools/customersQueryCustomer.js";
import { tool$customersUpdateCustomer } from "./tools/customersUpdateCustomer.js";
import { tool$eventsGetEvent } from "./tools/eventsGetEvent.js";
import { tool$eventsGetHuggingfaceInferenceData } from "./tools/eventsGetHuggingfaceInferenceData.js";
import { tool$eventsGetUsageAnalytics } from "./tools/eventsGetUsageAnalytics.js";
import { tool$eventsGetUsageByMeter } from "./tools/eventsGetUsageByMeter.js";
import { tool$eventsGetUsageStatistics } from "./tools/eventsGetUsageStatistics.js";
import { tool$eventsIngestEvent } from "./tools/eventsIngestEvent.js";
import { tool$eventsIngestEventsBulk } from "./tools/eventsIngestEventsBulk.js";
import { tool$eventsListRawEvents } from "./tools/eventsListRawEvents.js";
import { tool$invoicesAttemptInvoicePayment } from "./tools/invoicesAttemptInvoicePayment.js";
import { tool$invoicesCreateInvoice } from "./tools/invoicesCreateInvoice.js";
import { tool$invoicesFinalizeInvoice } from "./tools/invoicesFinalizeInvoice.js";
import { tool$invoicesGetCustomerInvoiceSummary } from "./tools/invoicesGetCustomerInvoiceSummary.js";
import { tool$invoicesGetInvoice } from "./tools/invoicesGetInvoice.js";
import { tool$invoicesGetInvoicePdf } from "./tools/invoicesGetInvoicePdf.js";
import { tool$invoicesGetInvoicePreview } from "./tools/invoicesGetInvoicePreview.js";
import { tool$invoicesQueryInvoice } from "./tools/invoicesQueryInvoice.js";
import { tool$invoicesRecalculateInvoice } from "./tools/invoicesRecalculateInvoice.js";
import { tool$invoicesRecalculateInvoiceV2 } from "./tools/invoicesRecalculateInvoiceV2.js";
import { tool$invoicesTriggerInvoiceCommsWebhook } from "./tools/invoicesTriggerInvoiceCommsWebhook.js";
import { tool$invoicesUpdateInvoice } from "./tools/invoicesUpdateInvoice.js";
import { tool$invoicesUpdateInvoicePaymentStatus } from "./tools/invoicesUpdateInvoicePaymentStatus.js";
import { tool$invoicesVoidInvoice } from "./tools/invoicesVoidInvoice.js";
import { tool$plansClonePlan } from "./tools/plansClonePlan.js";
import { tool$plansCreatePlan } from "./tools/plansCreatePlan.js";
import { tool$plansDeletePlan } from "./tools/plansDeletePlan.js";
import { tool$plansGetPlan } from "./tools/plansGetPlan.js";
import { tool$plansQueryPlan } from "./tools/plansQueryPlan.js";
import { tool$plansSyncPlanPrices } from "./tools/plansSyncPlanPrices.js";
import { tool$plansUpdatePlan } from "./tools/plansUpdatePlan.js";
import { tool$pricesCreatePrice } from "./tools/pricesCreatePrice.js";
import { tool$pricesCreatePricesBulk } from "./tools/pricesCreatePricesBulk.js";
import { tool$pricesDeletePrice } from "./tools/pricesDeletePrice.js";
import { tool$pricesGetPrice } from "./tools/pricesGetPrice.js";
import { tool$pricesGetPriceByLookupKey } from "./tools/pricesGetPriceByLookupKey.js";
import { tool$pricesQueryPrice } from "./tools/pricesQueryPrice.js";
import { tool$pricesUpdatePrice } from "./tools/pricesUpdatePrice.js";
import { tool$subscriptionsActivateSubscription } from "./tools/subscriptionsActivateSubscription.js";
import { tool$subscriptionsAddSubscriptionAddon } from "./tools/subscriptionsAddSubscriptionAddon.js";
import { tool$subscriptionsCancelSubscription } from "./tools/subscriptionsCancelSubscription.js";
import { tool$subscriptionsCancelSubscriptionSchedule } from "./tools/subscriptionsCancelSubscriptionSchedule.js";
import { tool$subscriptionsCreateSubscription } from "./tools/subscriptionsCreateSubscription.js";
import { tool$subscriptionsCreateSubscriptionLineItem } from "./tools/subscriptionsCreateSubscriptionLineItem.js";
import { tool$subscriptionsDeleteSubscriptionLineItem } from "./tools/subscriptionsDeleteSubscriptionLineItem.js";
import { tool$subscriptionsExecuteSubscriptionChange } from "./tools/subscriptionsExecuteSubscriptionChange.js";
import { tool$subscriptionsExecuteSubscriptionModify } from "./tools/subscriptionsExecuteSubscriptionModify.js";
import { tool$subscriptionsExecuteSubscriptionPlanChangeV2 } from "./tools/subscriptionsExecuteSubscriptionPlanChangeV2.js";
import { tool$subscriptionsGetSubscription } from "./tools/subscriptionsGetSubscription.js";
import { tool$subscriptionsGetSubscriptionAddonAssociations } from "./tools/subscriptionsGetSubscriptionAddonAssociations.js";
import { tool$subscriptionsGetSubscriptionEntitlements } from "./tools/subscriptionsGetSubscriptionEntitlements.js";
import { tool$subscriptionsGetSubscriptionSchedule } from "./tools/subscriptionsGetSubscriptionSchedule.js";
import { tool$subscriptionsGetSubscriptionUpcomingGrants } from "./tools/subscriptionsGetSubscriptionUpcomingGrants.js";
import { tool$subscriptionsGetSubscriptionUsage } from "./tools/subscriptionsGetSubscriptionUsage.js";
import { tool$subscriptionsGetSubscriptionV2 } from "./tools/subscriptionsGetSubscriptionV2.js";
import { tool$subscriptionsListAllSubscriptionSchedules } from "./tools/subscriptionsListAllSubscriptionSchedules.js";
import { tool$subscriptionsListSubscriptionSchedules } from "./tools/subscriptionsListSubscriptionSchedules.js";
import { tool$subscriptionsPreviewSubscriptionChange } from "./tools/subscriptionsPreviewSubscriptionChange.js";
import { tool$subscriptionsPreviewSubscriptionModify } from "./tools/subscriptionsPreviewSubscriptionModify.js";
import { tool$subscriptionsPreviewSubscriptionPlanChangeV2 } from "./tools/subscriptionsPreviewSubscriptionPlanChangeV2.js";
import { tool$subscriptionsQuerySubscription } from "./tools/subscriptionsQuerySubscription.js";
import { tool$subscriptionsQuerySubscriptionLineItems } from "./tools/subscriptionsQuerySubscriptionLineItems.js";
import { tool$subscriptionsRemoveSubscriptionAddon } from "./tools/subscriptionsRemoveSubscriptionAddon.js";
import { tool$subscriptionsUpdateSubscription } from "./tools/subscriptionsUpdateSubscription.js";
import { tool$subscriptionsUpdateSubscriptionLineItem } from "./tools/subscriptionsUpdateSubscriptionLineItem.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  dynamic?: boolean | undefined;
  scopes?: MCPScope[] | undefined;
  annotationFilter?: MCPToolAnnotationFilter | undefined;
  getSDK?: () => TirdadCore;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Tirdad",
    version: "2.1.24",
  });

  const getClient = deps.getSDK || (() =>
    new TirdadCore({
      security: deps.security,
      serverURL: deps.serverURL,
      serverIdx: deps.serverIdx,
      debugLogger: deps.logger.level === "debug"
        ? {
          log: (...args) => console.log(...args),
          group: (...args) => console.group(...args),
          groupEnd: (...args) => console.groupEnd(...args),
        }
        : undefined,
    }));

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const [tool, tools, toolMap] = createRegisterTool(
    deps.logger,
    server,
    getClient,
    scopes,
    allowedTools,
    deps.dynamic,
    deps.annotationFilter,
  );
  const resource = createRegisterResource(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    getClient,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, getClient, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$customersUpdateCustomer);
  tool(tool$customersCreateCustomer);
  tool(tool$customersGetCustomerByExternalId);
  tool(tool$customersGetCustomerEntitlementsByExternalID);
  tool(tool$customersGetSubscriptionsForCustomer);
  tool(tool$customersQueryCustomer);
  tool(tool$customersGetCustomerUsageSummary);
  tool(tool$customersGetCustomer);
  tool(tool$customersDeleteCustomer);
  tool(tool$customersGetCustomerEntitlements);
  tool(tool$customersGetCustomerUpcomingGrants);
  tool(tool$invoicesGetCustomerInvoiceSummary);
  tool(tool$invoicesCreateInvoice);
  tool(tool$invoicesGetInvoicePreview);
  tool(tool$invoicesQueryInvoice);
  tool(tool$invoicesGetInvoice);
  tool(tool$invoicesUpdateInvoice);
  tool(tool$invoicesTriggerInvoiceCommsWebhook);
  tool(tool$invoicesFinalizeInvoice);
  tool(tool$invoicesUpdateInvoicePaymentStatus);
  tool(tool$invoicesAttemptInvoicePayment);
  tool(tool$invoicesGetInvoicePdf);
  tool(tool$invoicesRecalculateInvoice);
  tool(tool$invoicesRecalculateInvoiceV2);
  tool(tool$invoicesVoidInvoice);
  tool(tool$eventsIngestEvent);
  tool(tool$eventsGetUsageAnalytics);
  tool(tool$eventsIngestEventsBulk);
  tool(tool$eventsGetHuggingfaceInferenceData);
  tool(tool$eventsGetEvent);
  tool(tool$eventsListRawEvents);
  tool(tool$eventsGetUsageStatistics);
  tool(tool$eventsGetUsageByMeter);
  tool(tool$plansCreatePlan);
  tool(tool$plansQueryPlan);
  tool(tool$plansGetPlan);
  tool(tool$plansUpdatePlan);
  tool(tool$plansDeletePlan);
  tool(tool$plansClonePlan);
  tool(tool$plansSyncPlanPrices);
  tool(tool$pricesCreatePrice);
  tool(tool$pricesCreatePricesBulk);
  tool(tool$pricesGetPriceByLookupKey);
  tool(tool$pricesQueryPrice);
  tool(tool$pricesGetPrice);
  tool(tool$pricesUpdatePrice);
  tool(tool$pricesDeletePrice);
  tool(tool$subscriptionsCreateSubscription);
  tool(tool$subscriptionsAddSubscriptionAddon);
  tool(tool$subscriptionsRemoveSubscriptionAddon);
  tool(tool$subscriptionsQuerySubscriptionLineItems);
  tool(tool$subscriptionsUpdateSubscriptionLineItem);
  tool(tool$subscriptionsDeleteSubscriptionLineItem);
  tool(tool$subscriptionsQuerySubscription);
  tool(tool$subscriptionsGetSubscriptionUsage);
  tool(tool$subscriptionsGetSubscription);
  tool(tool$subscriptionsUpdateSubscription);
  tool(tool$subscriptionsActivateSubscription);
  tool(tool$subscriptionsGetSubscriptionAddonAssociations);
  tool(tool$subscriptionsCancelSubscription);
  tool(tool$subscriptionsExecuteSubscriptionChange);
  tool(tool$subscriptionsPreviewSubscriptionChange);
  tool(tool$subscriptionsExecuteSubscriptionPlanChangeV2);
  tool(tool$subscriptionsPreviewSubscriptionPlanChangeV2);
  tool(tool$subscriptionsGetSubscriptionEntitlements);
  tool(tool$subscriptionsGetSubscriptionUpcomingGrants);
  tool(tool$subscriptionsCreateSubscriptionLineItem);
  tool(tool$subscriptionsExecuteSubscriptionModify);
  tool(tool$subscriptionsPreviewSubscriptionModify);
  tool(tool$subscriptionsGetSubscriptionV2);
  tool(tool$subscriptionsListAllSubscriptionSchedules);
  tool(tool$subscriptionsGetSubscriptionSchedule);
  tool(tool$subscriptionsCancelSubscriptionSchedule);
  tool(tool$subscriptionsListSubscriptionSchedules);

  if (deps.dynamic) {
    registerDynamicTools(deps.logger, server, getClient, toolMap, scopes);
  }

  return { server, tools };
}
