/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ActivateDraftSubscriptionRequest = { start_date: string };

export const ActivateDraftSubscriptionRequest$zodSchema: z.ZodType<
  ActivateDraftSubscriptionRequest
> = z.object({
  start_date: z.iso.datetime({ offset: true }).describe(
    "start_date is the new start date for the subscription when activating",
  ),
});
