/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ActivateDraftSubscriptionRequest,
  ActivateDraftSubscriptionRequest$zodSchema,
} from "./activatedraftsubscriptionrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type ActivateSubscriptionRequest = {
  id: string;
  body: ActivateDraftSubscriptionRequest;
};

export const ActivateSubscriptionRequest$zodSchema: z.ZodType<
  ActivateSubscriptionRequest
> = z.object({
  body: ActivateDraftSubscriptionRequest$zodSchema.describe(
    "Activate Draft Subscription Request",
  ),
  id: z.string().describe("Subscription ID"),
});

export type ActivateSubscriptionResponse = SubscriptionResponse | ErrorResponse;

export const ActivateSubscriptionResponse$zodSchema: z.ZodType<
  ActivateSubscriptionResponse
> = z.union([
  SubscriptionResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
