/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddonCadence, AddonCadence$zodSchema } from "./addoncadence.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";

export type AddAddonRef = {
  addon_id?: string | undefined;
  association_id?: string | undefined;
  cadence?: AddonCadence | undefined;
  proration_behavior?: ProrationBehavior | undefined;
  start_date?: string | undefined;
};

export const AddAddonRef$zodSchema: z.ZodType<AddAddonRef> = z.object({
  addon_id: z.string().optional(),
  association_id: z.string().optional(),
  cadence: AddonCadence$zodSchema.optional(),
  proration_behavior: ProrationBehavior$zodSchema.optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
});
