/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddonAssociationEntityType,
  AddonAssociationEntityType$zodSchema,
} from "./addonassociationentitytype.js";
import { AddonStatus, AddonStatus$zodSchema } from "./addonstatus.js";
import {
  CheckoutSessionResponse,
  CheckoutSessionResponse$zodSchema,
} from "./checkoutsessionresponse.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import { Status, Status$zodSchema } from "./status.js";

export type AddAddonToSubscriptionResponse = {
  addon_id?: string | undefined;
  addon_status?: AddonStatus | undefined;
  cancellation_reason?: string | undefined;
  cancelled_at?: string | undefined;
  checkout_session?: CheckoutSessionResponse | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: AddonAssociationEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  invoice?: InvoiceResponse | undefined;
  metadata?: { [k: string]: any } | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const AddAddonToSubscriptionResponse$zodSchema: z.ZodType<
  AddAddonToSubscriptionResponse
> = z.object({
  addon_id: z.string().optional(),
  addon_status: AddonStatus$zodSchema.optional(),
  cancellation_reason: z.string().optional(),
  cancelled_at: z.iso.datetime({ offset: true }).optional(),
  checkout_session: CheckoutSessionResponse$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  end_date: z.iso.datetime({ offset: true }).optional(),
  entity_id: z.string().optional(),
  entity_type: AddonAssociationEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice: InvoiceResponse$zodSchema.optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
