/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AddLineItemRequest = {
  amount: string;
  description?: string | undefined;
  display_name: string;
  period_end?: string | undefined;
  period_start?: string | undefined;
  quantity: string;
};

export const AddLineItemRequest$zodSchema: z.ZodType<AddLineItemRequest> = z
  .object({
    amount: z.string(),
    description: z.string().optional(),
    display_name: z.string(),
    period_end: z.iso.datetime({ offset: true }).optional(),
    period_start: z.iso.datetime({ offset: true }).optional(),
    quantity: z.string(),
  });
