/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AddonStatus = {
  Active: "active",
  Cancelled: "cancelled",
  Pending: "pending",
} as const;
export type AddonStatus = ClosedEnum<typeof AddonStatus>;

export const AddonStatus$zodSchema = z.enum([
  "active",
  "cancelled",
  "pending",
]);
