/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AddonAssociationEntityType = {
  Subscription: "subscription",
  Plan: "plan",
  Addon: "addon",
} as const;
export type AddonAssociationEntityType = ClosedEnum<
  typeof AddonAssociationEntityType
>;

export const AddonAssociationEntityType$zodSchema = z.enum([
  "subscription",
  "plan",
  "addon",
]);
