/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Address = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
};

export const Address$zodSchema: z.ZodType<Address> = z.object({
  address_city: z.string().optional(),
  address_country: z.string().optional(),
  address_line1: z.string().optional(),
  address_line2: z.string().optional(),
  address_postal_code: z.string().optional(),
  address_state: z.string().optional(),
});
