/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionResponse,
  AddAddonToSubscriptionResponse$zodSchema,
} from "./addaddontosubscriptionresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type AddSubscriptionAddonResponse =
  | AddAddonToSubscriptionResponse
  | ErrorResponse;

export const AddSubscriptionAddonResponse$zodSchema: z.ZodType<
  AddSubscriptionAddonResponse
> = z.union([
  AddAddonToSubscriptionResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
