/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const AggregationType = {
  Count: "COUNT",
  Sum: "SUM",
  Avg: "AVG",
  CountUnique: "COUNT_UNIQUE",
  Latest: "LATEST",
  SumWithMultiplier: "SUM_WITH_MULTIPLIER",
  Max: "MAX",
  WeightedSum: "WEIGHTED_SUM",
} as const;
export type AggregationType = ClosedEnum<typeof AggregationType>;

export const AggregationType$zodSchema = z.enum([
  "COUNT",
  "SUM",
  "AVG",
  "COUNT_UNIQUE",
  "LATEST",
  "SUM_WITH_MULTIPLIER",
  "MAX",
  "WEIGHTED_SUM",
]);
