/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$zodSchema,
} from "./entitlementusageresetperiod.js";

export type AggregatedEntitlement = {
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  static_values?: Array<string> | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: EntitlementUsageResetPeriod | undefined;
};

export const AggregatedEntitlement$zodSchema: z.ZodType<AggregatedEntitlement> =
  z.object({
    is_enabled: z.boolean().optional(),
    is_soft_limit: z.boolean().optional(),
    static_values: z.array(z.string()).optional().describe(
      "For static/SLA features",
    ),
    usage_limit: z.int().optional(),
    usage_reset_period: EntitlementUsageResetPeriod$zodSchema.optional(),
  });
