/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregatedEntitlementBucket,
  AggregatedEntitlementBucket$zodSchema,
} from "./aggregatedentitlementbucket.js";
import {
  EntitlementAggregationMode,
  EntitlementAggregationMode$zodSchema,
} from "./entitlementaggregationmode.js";
import {
  EntitlementUsageResetPeriod,
  EntitlementUsageResetPeriod$zodSchema,
} from "./entitlementusageresetperiod.js";

export type ConfigValue = {};

export const ConfigValue$zodSchema: z.ZodType<ConfigValue> = z.object({});

export type AggregatedEntitlement = {
  aggregation_mode?: EntitlementAggregationMode | undefined;
  buckets?: Array<AggregatedEntitlementBucket> | undefined;
  config_values?: Array<{ [k: string]: ConfigValue }> | undefined;
  is_enabled?: boolean | undefined;
  is_soft_limit?: boolean | undefined;
  static_values?: Array<string> | undefined;
  usage_limit?: number | undefined;
  usage_reset_period?: EntitlementUsageResetPeriod | undefined;
};

export const AggregatedEntitlement$zodSchema: z.ZodType<AggregatedEntitlement> =
  z.object({
    aggregation_mode: EntitlementAggregationMode$zodSchema.optional(),
    buckets: z.array(AggregatedEntitlementBucket$zodSchema).optional(),
    config_values: z.array(
      z.record(z.string(), z.lazy(() => ConfigValue$zodSchema)),
    ).optional(),
    is_enabled: z.boolean().optional(),
    is_soft_limit: z.boolean().optional(),
    static_values: z.array(z.string()).optional(),
    usage_limit: z.int().optional(),
    usage_reset_period: EntitlementUsageResetPeriod$zodSchema.optional(),
  });
