/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntitlementGrantDurationUnit,
  EntitlementGrantDurationUnit$zodSchema,
} from "./entitlementgrantdurationunit.js";
import {
  EntitlementGrantMeasure,
  EntitlementGrantMeasure$zodSchema,
} from "./entitlementgrantmeasure.js";

export type AggregatedEntitlementBucket = {
  entitlement_id?: string | undefined;
  grant_duration_unit?: EntitlementGrantDurationUnit | undefined;
  grant_duration_value?: number | undefined;
  grant_measure?: EntitlementGrantMeasure | undefined;
  grant_quota?: string | undefined;
  source_entity_id?: string | undefined;
  usage_limit?: number | undefined;
};

export const AggregatedEntitlementBucket$zodSchema: z.ZodType<
  AggregatedEntitlementBucket
> = z.object({
  entitlement_id: z.string().optional(),
  grant_duration_unit: EntitlementGrantDurationUnit$zodSchema.optional(),
  grant_duration_value: z.int().optional(),
  grant_measure: EntitlementGrantMeasure$zodSchema.optional(),
  grant_quota: z.string().optional(),
  source_entity_id: z.string().optional(),
  usage_limit: z.int().optional(),
});
