/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertCondition, AlertCondition$zodSchema } from "./alertcondition.js";

export type AlertThreshold = {
  condition?: AlertCondition | undefined;
  threshold?: number | undefined;
};

export const AlertThreshold$zodSchema: z.ZodType<AlertThreshold> = z.object({
  condition: AlertCondition$zodSchema.optional(),
  threshold: z.number().optional(),
});
