/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$zodSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  MeterUsageAttribution,
  MeterUsageAttribution$zodSchema,
} from "./meterusageattribution.js";

export type AttributedToCustomerResult = {
  error?: ErrorResponse | undefined;
  meter_usage?: MeterUsageAttribution | undefined;
  status?: DebugTrackerStatus | undefined;
};

export const AttributedToCustomerResult$zodSchema: z.ZodType<
  AttributedToCustomerResult
> = z.object({
  error: ErrorResponse$zodSchema.optional(),
  meter_usage: MeterUsageAttribution$zodSchema.optional(),
  status: DebugTrackerStatus$zodSchema.optional(),
});
