/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type AutoTopup = {
  amount?: number | undefined;
  enabled?: boolean | undefined;
  invoicing?: boolean | undefined;
  threshold?: number | undefined;
};

export const AutoTopup$zodSchema: z.ZodType<AutoTopup> = z.object({
  amount: z.number().optional(),
  enabled: z.boolean().optional(),
  invoicing: z.boolean().optional(),
  threshold: z.number().optional(),
});
