/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const BillingModel = {
  FlatFee: "FLAT_FEE",
  Package: "PACKAGE",
  Tiered: "TIERED",
} as const;
export type BillingModel = ClosedEnum<typeof BillingModel>;

export const BillingModel$zodSchema = z.enum([
  "FLAT_FEE",
  "PACKAGE",
  "TIERED",
]);
