/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const BillingCycle = {
  Anniversary: "anniversary",
  Calendar: "calendar",
} as const;
export type BillingCycle = ClosedEnum<typeof BillingCycle>;

export const BillingCycle$zodSchema = z.enum([
  "anniversary",
  "calendar",
]);
