/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const BillingCadence = {
  Recurring: "RECURRING",
} as const;
export type BillingCadence = ClosedEnum<typeof BillingCadence>;

export const BillingCadence$zodSchema = z.enum([
  "RECURRING",
]);
