/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const BillingPeriodBehaviour = {
  Unchanged: "unchanged",
  AnchorAtEffect: "anchor_at_effect",
  AnchorAtConfig: "anchor_at_config",
} as const;
export type BillingPeriodBehaviour = ClosedEnum<typeof BillingPeriodBehaviour>;

export const BillingPeriodBehaviour$zodSchema = z.enum([
  "unchanged",
  "anchor_at_effect",
  "anchor_at_config",
]);
