/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";

export type BillingCycleInfo = {
  billing_anchor?: string | undefined;
  billing_cadence?: BillingCadence | undefined;
  billing_period?: BillingPeriod | undefined;
  billing_period_count?: number | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
};

export const BillingCycleInfo$zodSchema: z.ZodType<BillingCycleInfo> = z.object(
  {
    billing_anchor: z.iso.datetime({ offset: true }).optional().describe(
      "billing_anchor is the new billing anchor",
    ),
    billing_cadence: BillingCadence$zodSchema.optional(),
    billing_period: BillingPeriod$zodSchema.optional(),
    billing_period_count: z.int().optional().describe(
      "billing_period_count is the billing period count",
    ),
    period_end: z.iso.datetime({ offset: true }).optional().describe(
      "period_end is the end of the new billing period",
    ),
    period_start: z.iso.datetime({ offset: true }).optional().describe(
      "period_start is the start of the new billing period",
    ),
  },
);
