/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingCycle, BillingCycle$zodSchema } from "./billingcycle.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";

export type BillingPeriodConfig = {
  billing_anchor?: string | undefined;
  billing_cycle?: BillingCycle | undefined;
  billing_period_count?: number | undefined;
  billing_period_unit?: BillingPeriod | undefined;
};

export const BillingPeriodConfig$zodSchema: z.ZodType<BillingPeriodConfig> = z
  .object({
    billing_anchor: z.iso.datetime({ offset: true }).optional(),
    billing_cycle: BillingCycle$zodSchema.optional(),
    billing_period_count: z.int().optional(),
    billing_period_unit: BillingPeriod$zodSchema.optional(),
  });
