/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const BillingPeriod = {
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Weekly: "WEEKLY",
  Daily: "DAILY",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
  Onetime: "ONETIME",
} as const;
export type BillingPeriod = ClosedEnum<typeof BillingPeriod>;

export const BillingPeriod$zodSchema = z.enum([
  "MONTHLY",
  "ANNUAL",
  "WEEKLY",
  "DAILY",
  "QUARTERLY",
  "HALF_YEARLY",
  "ONETIME",
]);
