/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Bucket, Bucket$zodSchema } from "./bucket.js";

export type BucketSummary = {
  base_charge?: string | undefined;
  bucket_id?: string | undefined;
  commitment_type?: string | undefined;
  commitment_value?: string | undefined;
  computed_overage?: string | undefined;
  computed_true_up?: string | undefined;
  computed_utilized?: string | undefined;
  end?: Bucket | undefined;
  price_id?: string | undefined;
  start?: Bucket | undefined;
  subscription_line_item_id?: string | undefined;
  total_usage?: string | undefined;
};

export const BucketSummary$zodSchema: z.ZodType<BucketSummary> = z.object({
  base_charge: z.string().optional(),
  bucket_id: z.string().optional(),
  commitment_type: z.string().optional(),
  commitment_value: z.string().optional(),
  computed_overage: z.string().optional(),
  computed_true_up: z.string().optional(),
  computed_utilized: z.string().optional(),
  end: Bucket$zodSchema.optional(),
  price_id: z.string().optional().describe(
    "PriceID is the bucket's own price (the line item's price for the\nout-of-bucket row).",
  ),
  start: Bucket$zodSchema.optional(),
  subscription_line_item_id: z.string().optional().describe(
    "SubscriptionLineItemID is the line item this bucket is configured on.",
  ),
  total_usage: z.string().optional(),
});
