/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CancellationType,
  CancellationType$zodSchema,
} from "./cancellationtype.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import {
  ProrationDetail,
  ProrationDetail$zodSchema,
} from "./prorationdetail.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type CancelSubscriptionResponse = {
  cancellation_type?: CancellationType | undefined;
  effective_date?: string | undefined;
  message?: string | undefined;
  processed_at?: string | undefined;
  proration_details?: Array<ProrationDetail> | undefined;
  proration_invoice?: InvoiceResponse | undefined;
  reason?: string | undefined;
  status?: SubscriptionStatus | undefined;
  subscription_id?: string | undefined;
  total_credit_amount?: string | undefined;
};

export const CancelSubscriptionResponse$zodSchema: z.ZodType<
  CancelSubscriptionResponse
> = z.object({
  cancellation_type: CancellationType$zodSchema.optional(),
  effective_date: z.iso.datetime({ offset: true }).optional(),
  message: z.string().optional().describe("Response metadata"),
  processed_at: z.iso.datetime({ offset: true }).optional(),
  proration_details: z.array(ProrationDetail$zodSchema).optional(),
  proration_invoice: InvoiceResponse$zodSchema.optional(),
  reason: z.string().optional(),
  status: SubscriptionStatus$zodSchema.optional(),
  subscription_id: z.string().optional().describe("Basic cancellation info"),
  total_credit_amount: z.string().optional(),
});
