/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ScheduleStatus, ScheduleStatus$zodSchema } from "./schedulestatus.js";

/**
 * Confirmation of schedule cancellation
 */
export type CancelScheduleResponse = {
  message?: string | undefined;
  status?: ScheduleStatus | undefined;
};

export const CancelScheduleResponse$zodSchema: z.ZodType<
  CancelScheduleResponse
> = z.object({
  message: z.string().optional().describe("message is a confirmation message"),
  status: ScheduleStatus$zodSchema.optional(),
}).describe("Confirmation of schedule cancellation");
