/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CancelScheduleRequest,
  CancelScheduleRequest$zodSchema,
} from "./cancelschedulerequest.js";

export type CancelSubscriptionScheduleRequest = {
  schedule_id: string;
  body?: CancelScheduleRequest | undefined;
};

export const CancelSubscriptionScheduleRequest$zodSchema: z.ZodType<
  CancelSubscriptionScheduleRequest
> = z.object({
  body: CancelScheduleRequest$zodSchema.optional().describe(
    "Cancel request (optional if using path parameter)",
  ),
  schedule_id: z.string().describe(
    "Schedule ID (optional if using request body)",
  ),
});
