/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CancelSubscriptionRequest,
  CancelSubscriptionRequest$zodSchema,
} from "./cancelsubscriptionrequest.js";
import {
  CancelSubscriptionResponse,
  CancelSubscriptionResponse$zodSchema,
} from "./cancelsubscriptionresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type CancelSubscriptionRequestRequest = {
  id: string;
  body: CancelSubscriptionRequest;
};

export const CancelSubscriptionRequestRequest$zodSchema: z.ZodType<
  CancelSubscriptionRequestRequest
> = z.object({
  body: CancelSubscriptionRequest$zodSchema.describe(
    "Cancel Subscription Request",
  ),
  id: z.string().describe("Subscription ID"),
});

export type CancelSubscriptionResponseResponse =
  | CancelSubscriptionResponse
  | ErrorResponse;

export const CancelSubscriptionResponseResponse$zodSchema: z.ZodType<
  CancelSubscriptionResponseResponse
> = z.union([
  CancelSubscriptionResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
