/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CancelImmediatelyInvoicePolicy = {
  GenerateInvoice: "generate_invoice",
  Skip: "skip",
} as const;
export type CancelImmediatelyInvoicePolicy = ClosedEnum<
  typeof CancelImmediatelyInvoicePolicy
>;

export const CancelImmediatelyInvoicePolicy$zodSchema = z.enum([
  "generate_invoice",
  "skip",
]);
