/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubscriptionScheduleChangeType,
  SubscriptionScheduleChangeType$zodSchema,
} from "./subscriptionschedulechangetype.js";

/**
 * Request to cancel a subscription schedule (supports two modes)
 */
export type CancelScheduleRequest = {
  schedule_id?: string | undefined;
  schedule_type?: SubscriptionScheduleChangeType | undefined;
  subscription_id?: string | undefined;
};

export const CancelScheduleRequest$zodSchema: z.ZodType<CancelScheduleRequest> =
  z.object({
    schedule_id: z.string().optional().describe(
      "schedule_id is the ID of the schedule to cancel (optional if subscription_id and schedule_type are provided)",
    ),
    schedule_type: SubscriptionScheduleChangeType$zodSchema.optional(),
    subscription_id: z.string().optional().describe(
      "subscription_id is the ID of the subscription (required if schedule_id is not provided)",
    ),
  }).describe("Request to cancel a subscription schedule (supports two modes)");
