/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangedLineItemAction,
  ChangedLineItemAction$zodSchema,
} from "./changedlineitemaction.js";

export type ChangedLineItem = {
  change_action?: ChangedLineItemAction | undefined;
  end_date?: string | undefined;
  id?: string | undefined;
  price_id?: string | undefined;
  quantity?: string | undefined;
  start_date?: string | undefined;
};

export const ChangedLineItem$zodSchema: z.ZodType<ChangedLineItem> = z.object({
  change_action: ChangedLineItemAction$zodSchema.optional().describe(
    "created | updated | ended",
  ),
  end_date: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  price_id: z.string().optional(),
  quantity: z.string().optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
});
