/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ChangedInvoiceStatus = {
  Preview: "preview",
  Issued: "issued",
} as const;
export type ChangedInvoiceStatus = ClosedEnum<typeof ChangedInvoiceStatus>;

export const ChangedInvoiceStatus$zodSchema = z.enum([
  "preview",
  "issued",
]);
