/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangedInvoiceAction,
  ChangedInvoiceAction$zodSchema,
} from "./changedinvoiceaction.js";
import {
  ChangedInvoiceStatus,
  ChangedInvoiceStatus$zodSchema,
} from "./changedinvoicestatus.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import {
  WalletTransactionResponse,
  WalletTransactionResponse$zodSchema,
} from "./wallettransactionresponse.js";

export type ChangedInvoice = {
  action?: ChangedInvoiceAction | undefined;
  id?: string | undefined;
  invoice?: InvoiceResponse | undefined;
  status?: ChangedInvoiceStatus | undefined;
  wallet_transaction?: WalletTransactionResponse | undefined;
};

export const ChangedInvoice$zodSchema: z.ZodType<ChangedInvoice> = z.object({
  action: ChangedInvoiceAction$zodSchema.optional().describe(
    "created (proration invoice) | wallet_credit (downgrade credit)",
  ),
  id: z.string().optional(),
  invoice: InvoiceResponse$zodSchema.optional(),
  status: ChangedInvoiceStatus$zodSchema.optional().describe(
    "preview | issued | INITIATED | PENDING | PROCESSING | SUCCEEDED | OVERPAID | FAILED | REFUNDED | PARTIALLY_REFUNDED",
  ),
  wallet_transaction: WalletTransactionResponse$zodSchema.optional(),
});
