/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ChangedInvoice, ChangedInvoice$zodSchema } from "./changedinvoice.js";
import {
  ChangedLineItem,
  ChangedLineItem$zodSchema,
} from "./changedlineitem.js";
import {
  ChangedSubscription,
  ChangedSubscription$zodSchema,
} from "./changedsubscription.js";

export type ChangedResources = {
  invoices?: Array<ChangedInvoice> | undefined;
  line_items?: Array<ChangedLineItem> | undefined;
  subscriptions?: Array<ChangedSubscription> | undefined;
};

export const ChangedResources$zodSchema: z.ZodType<ChangedResources> = z.object(
  {
    invoices: z.array(ChangedInvoice$zodSchema).optional(),
    line_items: z.array(ChangedLineItem$zodSchema).optional(),
    subscriptions: z.array(ChangedSubscription$zodSchema).optional(),
  },
);
