/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * created | ended
 */
export const ChangedAddonAssociationAction = {
  Created: "created",
  Ended: "ended",
} as const;
/**
 * created | ended
 */
export type ChangedAddonAssociationAction = ClosedEnum<
  typeof ChangedAddonAssociationAction
>;

export const ChangedAddonAssociationAction$zodSchema = z.enum([
  "created",
  "ended",
]).describe("created | ended");
