/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

/**
 * created | updated
 */
export const ChangedSubscriptionAction = {
  Created: "created",
  Updated: "updated",
} as const;
/**
 * created | updated
 */
export type ChangedSubscriptionAction = ClosedEnum<
  typeof ChangedSubscriptionAction
>;

export const ChangedSubscriptionAction$zodSchema = z.enum([
  "created",
  "updated",
]).describe("created | updated");
