/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CollectionMethod,
  CollectionMethod$zodSchema,
} from "./collectionmethod.js";
import {
  PaymentMethodType,
  PaymentMethodType$zodSchema,
} from "./paymentmethodtype.js";

export type CheckoutJSONBCheckoutPaymentProviderConfig = {
  collection_method?: CollectionMethod | undefined;
  max_mandate_limit?: string | undefined;
  payment_method?: PaymentMethodType | undefined;
};

export const CheckoutJSONBCheckoutPaymentProviderConfig$zodSchema: z.ZodType<
  CheckoutJSONBCheckoutPaymentProviderConfig
> = z.object({
  collection_method: CollectionMethod$zodSchema.optional(),
  max_mandate_limit: z.string().optional(),
  payment_method: PaymentMethodType$zodSchema.optional(),
});
