/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CheckoutPaymentProvider = {
  Razorpay: "razorpay",
} as const;
export type CheckoutPaymentProvider = ClosedEnum<
  typeof CheckoutPaymentProvider
>;

export const CheckoutPaymentProvider$zodSchema = z.enum([
  "razorpay",
]);
