/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaymentAction, PaymentAction$zodSchema } from "./paymentaction.js";

export type CheckoutJSONBCheckoutProviderResult = {
  expires_at?: string | undefined;
  next_action?: PaymentAction | undefined;
  provider_metadata?: { [k: string]: string } | undefined;
  provider_payment_intent_id?: string | undefined;
  provider_session_id?: string | undefined;
};

export const CheckoutJSONBCheckoutProviderResult$zodSchema: z.ZodType<
  CheckoutJSONBCheckoutProviderResult
> = z.object({
  expires_at: z.iso.datetime({ offset: true }).optional().describe(
    "ExpiresAt is the provider URL expiry. When set and earlier than the session expiry,\nexecuteCheckoutAction tightens the session expiry to match.",
  ),
  next_action: PaymentAction$zodSchema.optional(),
  provider_metadata: z.record(z.string(), z.string()).optional().describe(
    "ProviderMetadata holds provider-specific data not needed for business logic.",
  ),
  provider_payment_intent_id: z.string().optional().describe(
    "ProviderPaymentIntentID is the provider-side charge/intent ID.\nStripe returns this at link creation (pi_xxx); others populate it from the webhook payload.",
  ),
  provider_session_id: z.string().optional().describe(
    "ProviderSessionID is stored in EntityIntegrationMapping at link creation.\n  Stripe:   Checkout Session ID  (cs_xxx)\n  Razorpay: Payment Link ID      (plink_xxx)\n  Nomod:    Payment Link ID      (NOTE: webhook uses Charge ID; look up by PaymentLinkID field)\n  Moyasar:  Payment ID",
  ),
});
