/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";

export type CheckoutPaymentBlock = {
  gateway?: string | undefined;
  id?: string | undefined;
  status?: PaymentStatus | undefined;
};

export const CheckoutPaymentBlock$zodSchema: z.ZodType<CheckoutPaymentBlock> = z
  .object({
    gateway: z.string().optional(),
    id: z.string().optional(),
    status: PaymentStatus$zodSchema.optional(),
  });
