/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CheckoutAction, CheckoutAction$zodSchema } from "./checkoutaction.js";
import {
  CheckoutJSONBCheckoutConfiguration,
  CheckoutJSONBCheckoutConfiguration$zodSchema,
} from "./checkoutjsonbcheckoutconfiguration.js";
import {
  CheckoutJSONBCheckoutPaymentProviderConfig,
  CheckoutJSONBCheckoutPaymentProviderConfig$zodSchema,
} from "./checkoutjsonbcheckoutpaymentproviderconfig.js";
import {
  CheckoutJSONBCheckoutProviderResult,
  CheckoutJSONBCheckoutProviderResult$zodSchema,
} from "./checkoutjsonbcheckoutproviderresult.js";
import {
  CheckoutJSONBCheckoutResult,
  CheckoutJSONBCheckoutResult$zodSchema,
} from "./checkoutjsonbcheckoutresult.js";
import {
  CheckoutPaymentProvider,
  CheckoutPaymentProvider$zodSchema,
} from "./checkoutpaymentprovider.js";
import { CheckoutStatus, CheckoutStatus$zodSchema } from "./checkoutstatus.js";
import { PaymentAction, PaymentAction$zodSchema } from "./paymentaction.js";
import { Status, Status$zodSchema } from "./status.js";

export type CheckoutSessionResponse = {
  action?: CheckoutAction | undefined;
  cancel_url?: string | undefined;
  cancelled_at?: string | undefined;
  checkout_invoice_id?: string | undefined;
  checkout_payment_id?: string | undefined;
  checkout_status?: CheckoutStatus | undefined;
  completed_at?: string | undefined;
  configuration?: CheckoutJSONBCheckoutConfiguration | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  customer_id?: string | undefined;
  environment_id?: string | undefined;
  expires_at?: string | undefined;
  failure_reason?: string | undefined;
  failure_url?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_action?: PaymentAction | undefined;
  payment_provider?: CheckoutPaymentProvider | undefined;
  payment_provider_config?:
    | CheckoutJSONBCheckoutPaymentProviderConfig
    | undefined;
  provider_result?: CheckoutJSONBCheckoutProviderResult | undefined;
  result?: CheckoutJSONBCheckoutResult | undefined;
  status?: Status | undefined;
  success_url?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CheckoutSessionResponse$zodSchema: z.ZodType<
  CheckoutSessionResponse
> = z.object({
  action: CheckoutAction$zodSchema.optional(),
  cancel_url: z.string().optional(),
  cancelled_at: z.iso.datetime({ offset: true }).optional(),
  checkout_invoice_id: z.string().optional().describe(
    "CheckoutInvoiceID and CheckoutPaymentID are set once the apply step\ncreates the corresponding Flexprice entities (completed sessions only).",
  ),
  checkout_payment_id: z.string().optional(),
  checkout_status: CheckoutStatus$zodSchema.optional(),
  completed_at: z.iso.datetime({ offset: true }).optional(),
  configuration: CheckoutJSONBCheckoutConfiguration$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  customer_id: z.string().optional(),
  environment_id: z.string().optional(),
  expires_at: z.iso.datetime({ offset: true }).optional().describe(
    "ExpiresAt is required. A Temporal timer fires at this time for any\nsession still in initiated|pending, marking it expired. The caller\nmust create a new session after expiry (expire-and-restart model).",
  ),
  failure_reason: z.string().optional().describe(
    "FailureReason is a human-readable string set on failed sessions.",
  ),
  failure_url: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional().describe(
    "IdempotencyKey is caller-supplied. It is unique only while the session\nis active (initiated|pending). The same key may be reused once the\nsession reaches a terminal state (completed|failed|expired).",
  ),
  metadata: z.record(z.string(), z.string()).optional(),
  payment_action: PaymentAction$zodSchema.optional(),
  payment_provider: CheckoutPaymentProvider$zodSchema.optional(),
  payment_provider_config: CheckoutJSONBCheckoutPaymentProviderConfig$zodSchema
    .optional(),
  provider_result: CheckoutJSONBCheckoutProviderResult$zodSchema.optional(),
  result: CheckoutJSONBCheckoutResult$zodSchema.optional(),
  status: Status$zodSchema.optional(),
  success_url: z.string().optional().describe(
    "Redirect URLs sent to the payment provider. The provider redirects the\nuser browser to the appropriate URL after the payment flow completes.",
  ),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
