/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CheckoutStatus = {
  Initiated: "initiated",
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
  Expired: "expired",
} as const;
export type CheckoutStatus = ClosedEnum<typeof CheckoutStatus>;

export const CheckoutStatus$zodSchema = z.enum([
  "initiated",
  "pending",
  "completed",
  "failed",
  "expired",
]);
