/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CheckoutPaymentProvider,
  CheckoutPaymentProvider$zodSchema,
} from "./checkoutpaymentprovider.js";
import {
  CheckoutPaymentProviderConfig,
  CheckoutPaymentProviderConfig$zodSchema,
} from "./checkoutpaymentproviderconfig.js";

export type CheckoutParams = {
  cancel_url?: string | undefined;
  failure_url?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_provider: CheckoutPaymentProvider;
  payment_provider_config?: CheckoutPaymentProviderConfig | undefined;
  success_url?: string | undefined;
};

export const CheckoutParams$zodSchema: z.ZodType<CheckoutParams> = z.object({
  cancel_url: z.string().optional(),
  failure_url: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  payment_provider: CheckoutPaymentProvider$zodSchema,
  payment_provider_config: CheckoutPaymentProviderConfig$zodSchema.optional(),
  success_url: z.string().optional(),
});
