/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CheckoutAction, CheckoutAction$zodSchema } from "./checkoutaction.js";
import {
  CheckoutPaymentBlock,
  CheckoutPaymentBlock$zodSchema,
} from "./checkoutpaymentblock.js";
import {
  CheckoutPaymentProvider,
  CheckoutPaymentProvider$zodSchema,
} from "./checkoutpaymentprovider.js";
import { CheckoutStatus, CheckoutStatus$zodSchema } from "./checkoutstatus.js";
import {
  EntityCreationResult,
  EntityCreationResult$zodSchema,
} from "./entitycreationresult.js";
import { PaymentAction, PaymentAction$zodSchema } from "./paymentaction.js";

export type CheckoutSessionResponse = {
  action?: CheckoutAction | undefined;
  cancel_url?: string | undefined;
  cancelled_at?: string | undefined;
  checkout_invoice_id?: string | undefined;
  checkout_payment_id?: string | undefined;
  checkout_status?: CheckoutStatus | undefined;
  completed_at?: string | undefined;
  created_at?: string | undefined;
  customer_id?: string | undefined;
  entity_creation_result?: EntityCreationResult | undefined;
  expires_at?: string | undefined;
  failure_reason?: string | undefined;
  failure_url?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  next_poll_after_ms?: number | undefined;
  payment?: CheckoutPaymentBlock | undefined;
  payment_action?: PaymentAction | undefined;
  payment_provider?: CheckoutPaymentProvider | undefined;
  stale?: boolean | undefined;
  success_url?: string | undefined;
  terminal?: boolean | undefined;
  updated_at?: string | undefined;
};

export const CheckoutSessionResponse$zodSchema: z.ZodType<
  CheckoutSessionResponse
> = z.object({
  action: CheckoutAction$zodSchema.optional(),
  cancel_url: z.string().optional(),
  cancelled_at: z.iso.datetime({ offset: true }).optional(),
  checkout_invoice_id: z.string().optional(),
  checkout_payment_id: z.string().optional(),
  checkout_status: CheckoutStatus$zodSchema.optional(),
  completed_at: z.iso.datetime({ offset: true }).optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  customer_id: z.string().optional(),
  entity_creation_result: EntityCreationResult$zodSchema.optional(),
  expires_at: z.iso.datetime({ offset: true }).optional(),
  failure_reason: z.string().optional(),
  failure_url: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  next_poll_after_ms: z.int().optional().describe(
    "NextPollAfterMs is how long a client should wait before reading again.\nZero means stop — either the session is terminal, or this response did not\ncome from a polling read.",
  ),
  payment: CheckoutPaymentBlock$zodSchema.optional(),
  payment_action: PaymentAction$zodSchema.optional(),
  payment_provider: CheckoutPaymentProvider$zodSchema.optional(),
  stale: z.boolean().optional().describe(
    "Stale reports that this response is stored state that was not checked against\nthe payment provider on this request — the read was debounced, or the gateway\ndid not answer. A UI should say \"still checking\" rather than presenting a\nstale answer as fact.",
  ),
  success_url: z.string().optional(),
  terminal: z.boolean().optional().describe(
    "Terminal reports whether the session has finished. Clients poll until this is\ntrue rather than hardcoding the status set, which would go stale if a status\nis ever added.",
  ),
  updated_at: z.iso.datetime({ offset: true }).optional(),
});
