/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CheckoutAction = {
  CreateSubscription: "create_subscription",
  ModifySubscription: "modify_subscription",
  WalletTopup: "wallet_topup",
  AddAddon: "add_addon",
} as const;
export type CheckoutAction = ClosedEnum<typeof CheckoutAction>;

export const CheckoutAction$zodSchema = z.enum([
  "create_subscription",
  "modify_subscription",
  "wallet_topup",
  "add_addon",
]);
