/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ClonePlanRequest,
  ClonePlanRequest$zodSchema,
} from "./cloneplanrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PlanResponse, PlanResponse$zodSchema } from "./planresponse.js";

export type ClonePlanRequestRequest = { id: string; body: ClonePlanRequest };

export const ClonePlanRequestRequest$zodSchema: z.ZodType<
  ClonePlanRequestRequest
> = z.object({
  body: ClonePlanRequest$zodSchema.describe("Clone configuration"),
  id: z.string().describe("Source Plan ID"),
});

export type ClonePlanResponse = PlanResponse | ErrorResponse;

export const ClonePlanResponse$zodSchema: z.ZodType<ClonePlanResponse> = z
  .union([
    PlanResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
