/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ClonePlanRequest = {
  description?: string | undefined;
  display_order?: number | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const ClonePlanRequest$zodSchema: z.ZodType<ClonePlanRequest> = z.object(
  {
    description: z.string().optional().describe(
      "Description overrides the source plan's description when provided",
    ),
    display_order: z.int().optional().describe(
      "DisplayOrder overrides the source plan's display order when provided",
    ),
    lookup_key: z.string().optional().describe(
      "LookupKey is required and must be unique across published plans",
    ),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional().describe(
      "Name is required and must be different from the source plan's name",
    ),
  },
);
