/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Bucket, Bucket$zodSchema } from "./bucket.js";
import { CommitmentType, CommitmentType$zodSchema } from "./commitmenttype.js";
import {
  CreatePriceRequest,
  CreatePriceRequest$zodSchema,
} from "./createpricerequest.js";

export type CommitmentBucketRequest = {
  commitment_type?: CommitmentType | undefined;
  commitment_value?: string | undefined;
  end?: Bucket | undefined;
  id?: string | undefined;
  overage_factor?: string | undefined;
  price?: CreatePriceRequest | undefined;
  start?: Bucket | undefined;
  true_up_enabled?: boolean | undefined;
};

export const CommitmentBucketRequest$zodSchema: z.ZodType<
  CommitmentBucketRequest
> = z.object({
  commitment_type: CommitmentType$zodSchema.optional(),
  commitment_value: z.string().optional(),
  end: Bucket$zodSchema.optional(),
  id: z.string().optional(),
  overage_factor: z.string().optional(),
  price: CreatePriceRequest$zodSchema.optional(),
  start: Bucket$zodSchema.optional(),
  true_up_enabled: z.boolean().optional(),
});
