/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PlanChangeScheduleDetails,
  PlanChangeScheduleDetails$zodSchema,
} from "./planchangescheduledetails.js";

export type ConfigurationDetails = {
  plan_change?: PlanChangeScheduleDetails | undefined;
};

export const ConfigurationDetails$zodSchema: z.ZodType<ConfigurationDetails> = z
  .object({
    plan_change: PlanChangeScheduleDetails$zodSchema.optional(),
  });
