/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CouponCadence, CouponCadence$zodSchema } from "./couponcadence.js";
import { CouponType, CouponType$zodSchema } from "./coupontype.js";
import { Status, Status$zodSchema } from "./status.js";

export type Coupon = {
  amount_off?: string | undefined;
  cadence?: CouponCadence | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  duration_in_periods?: number | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  max_redemptions?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  percentage_off?: string | undefined;
  redeem_after?: string | undefined;
  redeem_before?: string | undefined;
  rules?: { [k: string]: any } | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  total_redemptions?: number | undefined;
  type?: CouponType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const Coupon$zodSchema: z.ZodType<Coupon> = z.object({
  amount_off: z.string().optional(),
  cadence: CouponCadence$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  duration_in_periods: z.int().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  max_redemptions: z.int().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  percentage_off: z.string().optional(),
  redeem_after: z.string().optional(),
  redeem_before: z.string().optional(),
  rules: z.record(z.string(), z.any()).optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  total_redemptions: z.int().optional(),
  type: CouponType$zodSchema.optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
