/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Coupon, Coupon$zodSchema } from "./coupon.js";
import { Status, Status$zodSchema } from "./status.js";

export type CouponAssociationResponse = {
  coupon?: Coupon | undefined;
  coupon_id?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  end_date?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  subscription_line_item_id?: string | undefined;
  subscription_phase_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CouponAssociationResponse$zodSchema: z.ZodType<
  CouponAssociationResponse
> = z.object({
  coupon: Coupon$zodSchema.optional(),
  coupon_id: z.string().optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  end_date: z.iso.datetime({ offset: true }).optional().describe("Optional"),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional().describe("Mandatory"),
  subscription_line_item_id: z.string().optional().describe("Optional"),
  subscription_phase_id: z.string().optional().describe("Optional"),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
