/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CouponType, CouponType$zodSchema } from "./coupontype.js";
import { Status, Status$zodSchema } from "./status.js";

export type CouponApplicationResponse = {
  applied_at?: string | undefined;
  coupon_association_id?: string | undefined;
  coupon_id?: string | undefined;
  coupon_snapshot?: { [k: string]: any } | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  discount_percentage?: string | undefined;
  discount_type?: CouponType | undefined;
  discounted_amount?: string | undefined;
  environment_id?: string | undefined;
  final_price?: string | undefined;
  id?: string | undefined;
  invoice_id?: string | undefined;
  invoice_line_item_id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  original_price?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CouponApplicationResponse$zodSchema: z.ZodType<
  CouponApplicationResponse
> = z.object({
  applied_at: z.iso.datetime({ offset: true }).optional(),
  coupon_association_id: z.string().optional(),
  coupon_id: z.string().optional(),
  coupon_snapshot: z.record(z.string(), z.any()).optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  discount_percentage: z.string().optional(),
  discount_type: CouponType$zodSchema.optional(),
  discounted_amount: z.string().optional(),
  environment_id: z.string().optional(),
  final_price: z.string().optional(),
  id: z.string().optional(),
  invoice_id: z.string().optional(),
  invoice_line_item_id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  original_price: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
