/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CouponType = {
  Fixed: "fixed",
  Percentage: "percentage",
} as const;
export type CouponType = ClosedEnum<typeof CouponType>;

export const CouponType$zodSchema = z.enum([
  "fixed",
  "percentage",
]);
