/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CouponCadence = {
  Once: "once",
  Repeated: "repeated",
  Forever: "forever",
} as const;
export type CouponCadence = ClosedEnum<typeof CouponCadence>;

export const CouponCadence$zodSchema = z.enum([
  "once",
  "repeated",
  "forever",
]);
