/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateInvoiceLineItemRequest,
  CreateInvoiceLineItemRequest$zodSchema,
} from "./createinvoicelineitemrequest.js";
import {
  InvoiceBillingReason,
  InvoiceBillingReason$zodSchema,
} from "./invoicebillingreason.js";
import { InvoiceCoupon, InvoiceCoupon$zodSchema } from "./invoicecoupon.js";
import {
  InvoiceLineItemCoupon,
  InvoiceLineItemCoupon$zodSchema,
} from "./invoicelineitemcoupon.js";
import { InvoiceStatus, InvoiceStatus$zodSchema } from "./invoicestatus.js";
import { InvoiceType, InvoiceType$zodSchema } from "./invoicetype.js";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";
import {
  TaxRateOverride,
  TaxRateOverride$zodSchema,
} from "./taxrateoverride.js";
import {
  TaxRateResponse,
  TaxRateResponse$zodSchema,
} from "./taxrateresponse.js";

export type CreateInvoiceRequest = {
  amount_due: string;
  amount_paid?: string | undefined;
  billing_period?: string | undefined;
  billing_reason?: InvoiceBillingReason | undefined;
  coupons?: Array<string> | undefined;
  currency: string;
  customer_id: string;
  description?: string | undefined;
  due_date?: string | undefined;
  idempotency_key?: string | undefined;
  invoice_coupons?: Array<InvoiceCoupon> | undefined;
  invoice_number?: string | undefined;
  invoice_pdf_url?: string | undefined;
  invoice_status?: InvoiceStatus | undefined;
  invoice_type?: InvoiceType | undefined;
  issue_date?: string | undefined;
  line_item_coupons?: Array<InvoiceLineItemCoupon> | undefined;
  line_items?: Array<CreateInvoiceLineItemRequest> | undefined;
  metadata?: { [k: string]: string } | undefined;
  payment_status?: PaymentStatus | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  prepared_tax_rates?: Array<TaxRateResponse> | undefined;
  subscription_id?: string | undefined;
  subtotal: string;
  tax_rate_overrides?: Array<TaxRateOverride> | undefined;
  tax_rates?: Array<string> | undefined;
  total: string;
  total_prepaid_applied?: string | undefined;
};

export const CreateInvoiceRequest$zodSchema: z.ZodType<CreateInvoiceRequest> = z
  .object({
    amount_due: z.string().describe(
      "amount_due is the total amount that needs to be paid for this invoice",
    ),
    amount_paid: z.string().optional().describe(
      "amount_paid is the amount that has been paid towards this invoice",
    ),
    billing_period: z.string().optional().describe(
      "billing_period is the period this invoice covers (e.g., \"monthly\", \"yearly\")",
    ),
    billing_reason: InvoiceBillingReason$zodSchema.optional(),
    coupons: z.array(z.string()).optional().describe("coupons"),
    currency: z.string().describe(
      "currency is the three-letter ISO currency code (e.g., USD, EUR) for the invoice",
    ),
    customer_id: z.string().describe(
      "customer_id is the unique identifier of the customer this invoice belongs to",
    ),
    description: z.string().optional().describe(
      "description is an optional text description of the invoice",
    ),
    due_date: z.iso.datetime({ offset: true }).optional().describe(
      "due_date is the date by which payment is expected",
    ),
    idempotency_key: z.string().optional().describe(
      "idempotency_key is an optional key used to prevent duplicate invoice creation",
    ),
    invoice_coupons: z.array(InvoiceCoupon$zodSchema).optional().describe(
      "Invoice Coupons",
    ),
    invoice_number: z.string().optional().describe(
      "invoice_number is an optional human-readable identifier for the invoice",
    ),
    invoice_pdf_url: z.string().optional().describe(
      "invoice_pdf_url is the URL where customers can download the PDF version of this invoice",
    ),
    invoice_status: InvoiceStatus$zodSchema.optional(),
    invoice_type: InvoiceType$zodSchema.optional(),
    issue_date: z.iso.datetime({ offset: true }).optional().describe(
      "issue_date overrides the user-facing date of the invoice.\nDefaults to created_at if not provided.",
    ),
    line_item_coupons: z.array(InvoiceLineItemCoupon$zodSchema).optional()
      .describe("Invoice Line Item Coupons"),
    line_items: z.array(CreateInvoiceLineItemRequest$zodSchema).optional()
      .describe(
        "line_items contains the individual items that make up this invoice",
      ),
    metadata: z.record(z.string(), z.string()).optional(),
    payment_status: PaymentStatus$zodSchema.optional(),
    period_end: z.iso.datetime({ offset: true }).optional().describe(
      "period_end is the end date of the billing period",
    ),
    period_start: z.iso.datetime({ offset: true }).optional().describe(
      "period_start is the start date of the billing period",
    ),
    prepared_tax_rates: z.array(TaxRateResponse$zodSchema).optional().describe(
      "prepared_tax_rates contains the tax rates pre-resolved by the caller (e.g., billing service)",
    ),
    subscription_id: z.string().optional().describe(
      "subscription_id is the optional unique identifier of the subscription associated with this invoice",
    ),
    subtotal: z.string().describe(
      "subtotal is the amount before taxes and discounts are applied",
    ),
    tax_rate_overrides: z.array(TaxRateOverride$zodSchema).optional().describe(
      "tax_rate_overrides is the tax rate overrides to be applied to the invoice",
    ),
    tax_rates: z.array(z.string()).optional().describe("tax_rates"),
    total: z.string().describe(
      "total is the total amount of the invoice including taxes and discounts",
    ),
    total_prepaid_applied: z.string().optional().describe(
      "total_prepaid_applied is the total amount of prepaid applied to this invoice.",
    ),
  });
