/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type CreateSubscriptionResponse = SubscriptionResponse | ErrorResponse;

export const CreateSubscriptionResponse$zodSchema: z.ZodType<
  CreateSubscriptionResponse
> = z.union([
  SubscriptionResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
