/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PriceResponse, PriceResponse$zodSchema } from "./priceresponse.js";

export type CreatePriceResponse = PriceResponse | ErrorResponse;

export const CreatePriceResponse$zodSchema: z.ZodType<CreatePriceResponse> = z
  .union([
    PriceResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
