/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionRequest,
  AddAddonToSubscriptionRequest$zodSchema,
} from "./addaddontosubscriptionrequest.js";
import { BillingCycle, BillingCycle$zodSchema } from "./billingcycle.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  CollectionMethod,
  CollectionMethod$zodSchema,
} from "./collectionmethod.js";
import {
  CreateCreditGrantRequest,
  CreateCreditGrantRequest$zodSchema,
} from "./createcreditgrantrequest.js";
import {
  CreateSubscriptionLineItemRequest,
  CreateSubscriptionLineItemRequest$zodSchema,
} from "./createsubscriptionlineitemrequest.js";
import {
  LineItemCommitmentConfig,
  LineItemCommitmentConfig$zodSchema,
} from "./lineitemcommitmentconfig.js";
import {
  OverrideEntitlementRequest,
  OverrideEntitlementRequest$zodSchema,
} from "./overrideentitlementrequest.js";
import {
  OverrideLineItemRequest,
  OverrideLineItemRequest$zodSchema,
} from "./overridelineitemrequest.js";
import {
  PaymentBehavior,
  PaymentBehavior$zodSchema,
} from "./paymentbehavior.js";
import { PaymentTerms, PaymentTerms$zodSchema } from "./paymentterms.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";
import {
  SubscriptionCouponInput,
  SubscriptionCouponInput$zodSchema,
} from "./subscriptioncouponinput.js";
import {
  SubscriptionInheritanceConfig,
  SubscriptionInheritanceConfig$zodSchema,
} from "./subscriptioninheritanceconfig.js";
import {
  SubscriptionPhaseCreateRequest,
  SubscriptionPhaseCreateRequest$zodSchema,
} from "./subscriptionphasecreaterequest.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";
import {
  TaxRateOverride,
  TaxRateOverride$zodSchema,
} from "./taxrateoverride.js";

export type CreateSubscriptionRequest = {
  addons?: Array<AddAddonToSubscriptionRequest> | undefined;
  auto_invoice_threshold?: string | undefined;
  billing_anchor?: string | undefined;
  billing_cycle?: BillingCycle | undefined;
  billing_period: BillingPeriod;
  billing_period_count?: number | undefined;
  collection_method?: CollectionMethod | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: BillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<CreateCreditGrantRequest> | undefined;
  currency: string;
  customer_id?: string | undefined;
  customer_timezone?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  external_customer_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  inheritance?: SubscriptionInheritanceConfig | undefined;
  line_item_commitments?: { [k: string]: LineItemCommitmentConfig } | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<CreateSubscriptionLineItemRequest> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  override_entitlements?: Array<OverrideEntitlementRequest> | undefined;
  override_line_items?: Array<OverrideLineItemRequest> | undefined;
  payment_behavior?: PaymentBehavior | undefined;
  payment_terms?: PaymentTerms | undefined;
  phases?: Array<SubscriptionPhaseCreateRequest> | undefined;
  plan_id: string;
  proration_behavior?: ProrationBehavior | undefined;
  start_date?: string | undefined;
  subscription_coupons?: Array<SubscriptionCouponInput> | undefined;
  subscription_status?: SubscriptionStatus | undefined;
  tax_rate_overrides?: Array<TaxRateOverride> | undefined;
  trial_period_days?: number | undefined;
};

export const CreateSubscriptionRequest$zodSchema: z.ZodType<
  CreateSubscriptionRequest
> = z.object({
  addons: z.array(AddAddonToSubscriptionRequest$zodSchema).optional().describe(
    "Addons represents addons to be added to the subscription during creation",
  ),
  auto_invoice_threshold: z.string().optional().describe(
    "AutoInvoiceThreshold is the usage amount (in subscription currency) that triggers\nan intermediate invoice mid-period. Set once at creation; cannot be changed later.\nAllowed only when the subscription resolves to type standalone (no parent hierarchy rows).\nPlan line items must be usage-based only (no fixed or other non-usage plan prices).\nNil means auto invoice threshold billing is disabled for this subscription.",
  ),
  billing_anchor: z.iso.datetime({ offset: true }).optional().describe(
    "BillingAnchor overrides the derived billing anchor when billing_cycle is anniversary.\nFor monthly billing, the day-of-month (and time-of-day) define cycle boundaries: if start_date\nis before that day in the month, the first billing period ends on the next occurrence of that\nday in the same month (a shorter first period); subsequent periods follow the usual interval.",
  ),
  billing_cycle: BillingCycle$zodSchema.optional(),
  billing_period: BillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  collection_method: CollectionMethod$zodSchema.optional(),
  commitment_amount: z.string().optional().describe(
    "CommitmentAmount is the minimum amount a customer commits to paying for a billing period",
  ),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  coupons: z.array(z.string()).optional().describe(
    "Deprecated: use SubscriptionCoupons instead.",
  ),
  credit_grants: z.array(CreateCreditGrantRequest$zodSchema).optional()
    .describe("Credit grants to be applied when subscription is created"),
  currency: z.string(),
  customer_id: z.string().optional().describe(
    "customer_id is the flexprice customer id\nand it is prioritized over external_customer_id in case both are provided.",
  ),
  customer_timezone: z.string().optional().describe(
    "Timezone of the customer.\nIf not set, the default value is UTC.",
  ),
  enable_true_up: z.boolean().optional().describe(
    "Enable Commitment True Up Fee",
  ),
  end_date: z.iso.datetime({ offset: true }).optional(),
  external_customer_id: z.string().optional().describe(
    "external_customer_id is the customer id in your DB\nand must be same as what you provided as external_id while creating the customer in flexprice.",
  ),
  gateway_payment_method_id: z.string().optional(),
  inheritance: SubscriptionInheritanceConfig$zodSchema.optional(),
  line_item_commitments: z.record(
    z.string(),
    LineItemCommitmentConfig$zodSchema,
  ).optional().describe(
    "LineItemCommitments allows setting commitment configuration per line item (keyed by price_id)",
  ),
  line_item_coupons: z.record(z.string(), z.array(z.string())).optional()
    .describe("Deprecated: use SubscriptionCoupons instead."),
  line_items: z.array(CreateSubscriptionLineItemRequest$zodSchema).optional()
    .describe(
      "LineItems are extra line items to add at creation (each with price_id or price), in addition to plan prices",
    ),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  overage_factor: z.string().optional().describe(
    "OverageFactor is a multiplier applied to usage beyond the commitment amount",
  ),
  override_entitlements: z.array(OverrideEntitlementRequest$zodSchema)
    .optional().describe(
      "OverrideEntitlements allows customizing specific entitlements for this subscription",
    ),
  override_line_items: z.array(OverrideLineItemRequest$zodSchema).optional()
    .describe(
      "OverrideLineItems allows customizing specific prices for this subscription",
    ),
  payment_behavior: PaymentBehavior$zodSchema.optional(),
  payment_terms: PaymentTerms$zodSchema.optional(),
  phases: z.array(SubscriptionPhaseCreateRequest$zodSchema).optional().describe(
    "Phases represents subscription phases to be created with the subscription",
  ),
  plan_id: z.string(),
  proration_behavior: ProrationBehavior$zodSchema.optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
  subscription_coupons: z.array(SubscriptionCouponInput$zodSchema).optional()
    .describe(
      "SubscriptionCoupons is the preferred way to attach coupons at creation.\nAccepts coupon_code; optionally targets a line item via price_id.",
    ),
  subscription_status: SubscriptionStatus$zodSchema.optional(),
  tax_rate_overrides: z.array(TaxRateOverride$zodSchema).optional().describe(
    "tax_rate_overrides is the tax rate overrides\tto be applied to the subscription",
  ),
  trial_period_days: z.int().optional().describe(
    "TrialPeriodDays: nil = inherit trial length from plan recurring-fixed prices (must be uniform).\n0 = explicitly no trial (overrides catalog). >0 = override duration in days.",
  ),
});
