/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";

export type CreateSubscriptionParams = {
  billing_period?: BillingPeriod | undefined;
  currency?: string | undefined;
  end_date?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  plan_id?: string | undefined;
  start_date?: string | undefined;
  subscription_id?: string | undefined;
};

export const CreateSubscriptionParams$zodSchema: z.ZodType<
  CreateSubscriptionParams
> = z.object({
  billing_period: BillingPeriod$zodSchema.optional(),
  currency: z.string().optional(),
  end_date: z.iso.datetime({ offset: true }).optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  plan_id: z.string().optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
  subscription_id: z.string().optional(),
});
