/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerResponse,
  CustomerResponse$zodSchema,
} from "./customerresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type CreateCustomerResponse = CustomerResponse | ErrorResponse;

export const CreateCustomerResponse$zodSchema: z.ZodType<
  CreateCustomerResponse
> = z.union([
  CustomerResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
