/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionRequest,
  AddAddonToSubscriptionRequest$zodSchema,
} from "./addaddontosubscriptionrequest.js";
import { BillingCycle, BillingCycle$zodSchema } from "./billingcycle.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import { CheckoutParams, CheckoutParams$zodSchema } from "./checkoutparams.js";
import {
  CollectionMethod,
  CollectionMethod$zodSchema,
} from "./collectionmethod.js";
import {
  CreateCreditGrantRequest,
  CreateCreditGrantRequest$zodSchema,
} from "./createcreditgrantrequest.js";
import {
  CreateSubscriptionLineItemRequest,
  CreateSubscriptionLineItemRequest$zodSchema,
} from "./createsubscriptionlineitemrequest.js";
import {
  LineItemCommitmentConfig,
  LineItemCommitmentConfig$zodSchema,
} from "./lineitemcommitmentconfig.js";
import {
  OverrideEntitlementRequest,
  OverrideEntitlementRequest$zodSchema,
} from "./overrideentitlementrequest.js";
import {
  OverrideLineItemRequest,
  OverrideLineItemRequest$zodSchema,
} from "./overridelineitemrequest.js";
import {
  PaymentBehavior,
  PaymentBehavior$zodSchema,
} from "./paymentbehavior.js";
import { PaymentTerms, PaymentTerms$zodSchema } from "./paymentterms.js";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";
import {
  SubscriptionCouponInput,
  SubscriptionCouponInput$zodSchema,
} from "./subscriptioncouponinput.js";
import {
  SubscriptionInheritanceConfig,
  SubscriptionInheritanceConfig$zodSchema,
} from "./subscriptioninheritanceconfig.js";
import {
  SubscriptionPhaseCreateRequest,
  SubscriptionPhaseCreateRequest$zodSchema,
} from "./subscriptionphasecreaterequest.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";
import {
  TaxRateOverride,
  TaxRateOverride$zodSchema,
} from "./taxrateoverride.js";

export type CreateSubscriptionRequest = {
  addons?: Array<AddAddonToSubscriptionRequest> | undefined;
  auto_invoice_threshold?: string | undefined;
  billing_anchor?: string | undefined;
  billing_cycle?: BillingCycle | undefined;
  billing_period: BillingPeriod;
  billing_period_count?: number | undefined;
  checkout?: CheckoutParams | undefined;
  collection_method?: CollectionMethod | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: BillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<CreateCreditGrantRequest> | undefined;
  currency: string;
  customer_id?: string | undefined;
  enable_true_up?: boolean | undefined;
  end_date?: string | undefined;
  external_customer_id?: string | undefined;
  gateway_payment_method_id?: string | undefined;
  inheritance?: SubscriptionInheritanceConfig | undefined;
  line_item_commitments?: { [k: string]: LineItemCommitmentConfig } | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<CreateSubscriptionLineItemRequest> | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  overage_factor?: string | undefined;
  override_entitlements?: Array<OverrideEntitlementRequest> | undefined;
  override_line_items?: Array<OverrideLineItemRequest> | undefined;
  payment_behavior?: PaymentBehavior | undefined;
  payment_terms?: PaymentTerms | undefined;
  phases?: Array<SubscriptionPhaseCreateRequest> | undefined;
  plan_id: string;
  proration_behavior?: ProrationBehavior | undefined;
  start_date?: string | undefined;
  subscription_coupons?: Array<SubscriptionCouponInput> | undefined;
  subscription_status?: SubscriptionStatus | undefined;
  tax_rate_overrides?: Array<TaxRateOverride> | undefined;
  timezone?: string | undefined;
  trial_period_days?: number | undefined;
};

export const CreateSubscriptionRequest$zodSchema: z.ZodType<
  CreateSubscriptionRequest
> = z.object({
  addons: z.array(AddAddonToSubscriptionRequest$zodSchema).optional(),
  auto_invoice_threshold: z.string().optional().describe(
    "AutoInvoiceThreshold triggers a mid-period invoice when usage (in subscription currency) exceeds this amount.\nStandalone subscriptions only; all plan prices must be usage-based. Immutable after creation.",
  ),
  billing_anchor: z.iso.datetime({ offset: true }).optional().describe(
    "BillingAnchor overrides the derived anchor for anniversary billing. For monthly billing,\nthe day-of-month defines cycle boundaries (shorter first period if start is before that day).",
  ),
  billing_cycle: BillingCycle$zodSchema.optional(),
  billing_period: BillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  checkout: CheckoutParams$zodSchema.optional(),
  collection_method: CollectionMethod$zodSchema.optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  coupons: z.array(z.string()).optional().describe(
    "Deprecated: use SubscriptionCoupons instead.",
  ),
  credit_grants: z.array(CreateCreditGrantRequest$zodSchema).optional(),
  currency: z.string(),
  customer_id: z.string().optional().describe(
    "CustomerID takes priority over ExternalCustomerID when both are provided.",
  ),
  enable_true_up: z.boolean().optional(),
  end_date: z.iso.datetime({ offset: true }).optional(),
  external_customer_id: z.string().optional(),
  gateway_payment_method_id: z.string().optional(),
  inheritance: SubscriptionInheritanceConfig$zodSchema.optional(),
  line_item_commitments: z.record(
    z.string(),
    LineItemCommitmentConfig$zodSchema,
  ).optional().describe(
    "LineItemCommitments sets per-line-item commitment config, keyed by price_id.",
  ),
  line_item_coupons: z.record(z.string(), z.array(z.string())).optional()
    .describe("Deprecated: use SubscriptionCoupons instead."),
  line_items: z.array(CreateSubscriptionLineItemRequest$zodSchema).optional()
    .describe("LineItems are extra (non-plan) line items added at creation."),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  overage_factor: z.string().optional(),
  override_entitlements: z.array(OverrideEntitlementRequest$zodSchema)
    .optional(),
  override_line_items: z.array(OverrideLineItemRequest$zodSchema).optional()
    .describe(
      "OverrideLineItems overrides specific plan prices for this subscription.",
    ),
  payment_behavior: PaymentBehavior$zodSchema.optional(),
  payment_terms: PaymentTerms$zodSchema.optional(),
  phases: z.array(SubscriptionPhaseCreateRequest$zodSchema).optional(),
  plan_id: z.string(),
  proration_behavior: ProrationBehavior$zodSchema.optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
  subscription_coupons: z.array(SubscriptionCouponInput$zodSchema).optional()
    .describe(
      "SubscriptionCoupons is the preferred way to attach coupons at creation.\nAccepts coupon_code; optionally targets a line item via price_id.",
    ),
  subscription_status: SubscriptionStatus$zodSchema.optional(),
  tax_rate_overrides: z.array(TaxRateOverride$zodSchema).optional(),
  timezone: z.string().optional(),
  trial_period_days: z.int().optional().describe(
    "TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days.",
  ),
});
