/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreateSubscriptionResult = {
  invoice_id?: string | undefined;
  payment_id?: string | undefined;
  subscription_id?: string | undefined;
};

export const CreateSubscriptionResult$zodSchema: z.ZodType<
  CreateSubscriptionResult
> = z.object({
  invoice_id: z.string().optional(),
  payment_id: z.string().optional(),
  subscription_id: z.string().optional(),
});
