/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreditGrantCadence,
  CreditGrantCadence$zodSchema,
} from "./creditgrantcadence.js";
import {
  CreditGrantExpiryDurationUnit,
  CreditGrantExpiryDurationUnit$zodSchema,
} from "./creditgrantexpirydurationunit.js";
import {
  CreditGrantExpiryType,
  CreditGrantExpiryType$zodSchema,
} from "./creditgrantexpirytype.js";
import {
  CreditGrantPeriod,
  CreditGrantPeriod$zodSchema,
} from "./creditgrantperiod.js";
import {
  CreditGrantScope,
  CreditGrantScope$zodSchema,
} from "./creditgrantscope.js";
import { Status, Status$zodSchema } from "./status.js";

export type CreditGrantResponse = {
  cadence?: CreditGrantCadence | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grant_anchor?: string | undefined;
  credits?: string | undefined;
  end_date?: string | undefined;
  environment_id?: string | undefined;
  expiration_duration?: number | undefined;
  expiration_duration_unit?: CreditGrantExpiryDurationUnit | undefined;
  expiration_type?: CreditGrantExpiryType | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  period?: CreditGrantPeriod | undefined;
  period_count?: number | undefined;
  plan_id?: string | undefined;
  priority?: number | undefined;
  scope?: CreditGrantScope | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CreditGrantResponse$zodSchema: z.ZodType<CreditGrantResponse> = z
  .object({
    cadence: CreditGrantCadence$zodSchema.optional(),
    conversion_rate: z.string().optional().describe(
      "amount in the currency =  number of credits * conversion_rate\nex if conversion_rate is 1, then 1 USD = 1 credit\nex if conversion_rate is 2, then 1 USD = 0.5 credits\nex if conversion_rate is 0.5, then 1 USD = 2 credits",
    ),
    created_at: z.iso.datetime({ offset: true }).optional(),
    created_by: z.string().optional(),
    credit_grant_anchor: z.iso.datetime({ offset: true }).optional(),
    credits: z.string().optional(),
    end_date: z.iso.datetime({ offset: true }).optional(),
    environment_id: z.string().optional(),
    expiration_duration: z.int().optional(),
    expiration_duration_unit: CreditGrantExpiryDurationUnit$zodSchema
      .optional(),
    expiration_type: CreditGrantExpiryType$zodSchema.optional(),
    id: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    period: CreditGrantPeriod$zodSchema.optional(),
    period_count: z.int().optional(),
    plan_id: z.string().optional(),
    priority: z.int().optional(),
    scope: CreditGrantScope$zodSchema.optional(),
    start_date: z.iso.datetime({ offset: true }).optional(),
    status: Status$zodSchema.optional(),
    subscription_id: z.string().optional(),
    tenant_id: z.string().optional(),
    topup_conversion_rate: z.string().optional().describe(
      "topup_conversion_rate is the conversion rate for the topup to the currency\nex if topup_conversion_rate is 1, then 1 USD = 1 credit\nex if topup_conversion_rate is 2, then 1 USD = 0.5 credits\nex if topup_conversion_rate is 0.5, then 1 USD = 2 credits",
    ),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    updated_by: z.string().optional(),
  });
