/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantCadence = {
  Onetime: "ONETIME",
  Recurring: "RECURRING",
} as const;
export type CreditGrantCadence = ClosedEnum<typeof CreditGrantCadence>;

export const CreditGrantCadence$zodSchema = z.enum([
  "ONETIME",
  "RECURRING",
]);
