/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ApplicationStatus,
  ApplicationStatus$zodSchema,
} from "./applicationstatus.js";
import {
  CreditGrantApplicationReason,
  CreditGrantApplicationReason$zodSchema,
} from "./creditgrantapplicationreason.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";

export type CreditGrantApplicationResponse = {
  application_reason?: CreditGrantApplicationReason | undefined;
  application_status?: ApplicationStatus | undefined;
  applied_at?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grant_id?: string | undefined;
  credits?: number | undefined;
  environment_id?: string | undefined;
  failure_reason?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  retry_count?: number | undefined;
  scheduled_for?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  subscription_status_at_application?: SubscriptionStatus | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const CreditGrantApplicationResponse$zodSchema: z.ZodType<
  CreditGrantApplicationResponse
> = z.object({
  application_reason: CreditGrantApplicationReason$zodSchema.optional(),
  application_status: ApplicationStatus$zodSchema.optional(),
  applied_at: z.iso.datetime({ offset: true }).optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  credit_grant_id: z.string().optional(),
  credits: z.number().optional(),
  environment_id: z.string().optional(),
  failure_reason: z.string().optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  period_end: z.iso.datetime({ offset: true }).optional(),
  period_start: z.iso.datetime({ offset: true }).optional(),
  retry_count: z.int().optional(),
  scheduled_for: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional(),
  subscription_status_at_application: SubscriptionStatus$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
