/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantPeriod = {
  Daily: "DAILY",
  Weekly: "WEEKLY",
  Monthly: "MONTHLY",
  Annual: "ANNUAL",
  Quarterly: "QUARTERLY",
  HalfYearly: "HALF_YEARLY",
} as const;
export type CreditGrantPeriod = ClosedEnum<typeof CreditGrantPeriod>;

export const CreditGrantPeriod$zodSchema = z.enum([
  "DAILY",
  "WEEKLY",
  "MONTHLY",
  "ANNUAL",
  "QUARTERLY",
  "HALF_YEARLY",
]);
