/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantExpiryDurationUnit = {
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
  Year: "YEAR",
} as const;
export type CreditGrantExpiryDurationUnit = ClosedEnum<
  typeof CreditGrantExpiryDurationUnit
>;

export const CreditGrantExpiryDurationUnit$zodSchema = z.enum([
  "DAY",
  "WEEK",
  "MONTH",
  "YEAR",
]);
