/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantApplicationReason = {
  FirstTimeRecurringCreditGrant: "first_time_recurring_credit_grant",
  RecurringCreditGrant: "recurring_credit_grant",
  OnetimeCreditGrant: "onetime_credit_grant",
} as const;
export type CreditGrantApplicationReason = ClosedEnum<
  typeof CreditGrantApplicationReason
>;

export const CreditGrantApplicationReason$zodSchema = z.enum([
  "first_time_recurring_credit_grant",
  "recurring_credit_grant",
  "onetime_credit_grant",
]);
