/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantScope = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
} as const;
export type CreditGrantScope = ClosedEnum<typeof CreditGrantScope>;

export const CreditGrantScope$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
]);
