/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CreditBreakdown = {
  free?: string | undefined;
  purchased?: string | undefined;
};

export const CreditBreakdown$zodSchema: z.ZodType<CreditBreakdown> = z.object({
  free: z.string().optional(),
  purchased: z.string().optional(),
});
