/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const CreditGrantExpiryType = {
  Never: "NEVER",
  Duration: "DURATION",
  BillingCycle: "BILLING_CYCLE",
} as const;
export type CreditGrantExpiryType = ClosedEnum<typeof CreditGrantExpiryType>;

export const CreditGrantExpiryType$zodSchema = z.enum([
  "NEVER",
  "DURATION",
  "BILLING_CYCLE",
]);
