/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Customer, Customer$zodSchema } from "./customer.js";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$zodSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type CustomerLookupResult = {
  customer?: Customer | undefined;
  error?: ErrorResponse | undefined;
  status?: DebugTrackerStatus | undefined;
};

export const CustomerLookupResult$zodSchema: z.ZodType<CustomerLookupResult> = z
  .object({
    customer: Customer$zodSchema.optional(),
    error: ErrorResponse$zodSchema.optional(),
    status: DebugTrackerStatus$zodSchema.optional(),
  });
