/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerInvoiceSummary,
  CustomerInvoiceSummary$zodSchema,
} from "./customerinvoicesummary.js";

export type CustomerMultiCurrencyInvoiceSummary = {
  customer_id?: string | undefined;
  default_currency?: string | undefined;
  summaries?: Array<CustomerInvoiceSummary> | undefined;
};

export const CustomerMultiCurrencyInvoiceSummary$zodSchema: z.ZodType<
  CustomerMultiCurrencyInvoiceSummary
> = z.object({
  customer_id: z.string().optional().describe(
    "customer_id is the unique identifier of the customer",
  ),
  default_currency: z.string().optional().describe(
    "default_currency is the primary currency for this customer",
  ),
  summaries: z.array(CustomerInvoiceSummary$zodSchema).optional().describe(
    "summaries contains the invoice summaries for each currency",
  ),
});
