/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";

export type Customer = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  email?: string | undefined;
  environment_id?: string | undefined;
  external_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const Customer$zodSchema: z.ZodType<Customer> = z.object({
  address_city: z.string().optional().describe(
    "AddressCity is the city of the customer's address",
  ),
  address_country: z.string().optional().describe(
    "AddressCountry is the country of the customer's address (ISO 3166-1 alpha-2)",
  ),
  address_line1: z.string().optional().describe(
    "AddressLine1 is the first line of the customer's address",
  ),
  address_line2: z.string().optional().describe(
    "AddressLine2 is the second line of the customer's address",
  ),
  address_postal_code: z.string().optional().describe(
    "AddressPostalCode is the postal code of the customer's address",
  ),
  address_state: z.string().optional().describe(
    "AddressState is the state of the customer's address",
  ),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  email: z.string().optional().describe("Email is the email of the customer"),
  environment_id: z.string().optional().describe(
    "EnvironmentID is the environment identifier for the customer",
  ),
  external_id: z.string().optional().describe(
    "ExternalID is the external identifier for the customer",
  ),
  id: z.string().optional().describe(
    "ID is the unique identifier for the customer",
  ),
  metadata: z.record(z.string(), z.string()).optional().describe("Metadata"),
  name: z.string().optional().describe("Name is the name of the customer"),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
