/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregatedFeature,
  AggregatedFeature$zodSchema,
} from "./aggregatedfeature.js";

export type CustomerEntitlementsResponse = {
  customer_id?: string | undefined;
  features?: Array<AggregatedFeature> | undefined;
};

export const CustomerEntitlementsResponse$zodSchema: z.ZodType<
  CustomerEntitlementsResponse
> = z.object({
  customer_id: z.string().optional(),
  features: z.array(AggregatedFeature$zodSchema).optional(),
});
