/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const CustomerFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type CustomerFilterOrder = ClosedEnum<typeof CustomerFilterOrder>;

export const CustomerFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type CustomerFilter = {
  customer_ids?: Array<string> | undefined;
  email?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_id?: string | undefined;
  external_ids?: Array<string> | undefined;
  filters?: Array<FilterCondition> | undefined;
  limit?: number | undefined;
  metadata?: { [k: string]: string } | undefined;
  offset?: number | undefined;
  order?: CustomerFilterOrder | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
};

export const CustomerFilter$zodSchema: z.ZodType<CustomerFilter> = z.object({
  customer_ids: z.array(z.string()).optional(),
  email: z.string().optional(),
  end_time: z.iso.datetime({ offset: true }).optional(),
  expand: z.string().optional(),
  external_id: z.string().optional(),
  external_ids: z.array(z.string()).optional(),
  filters: z.array(FilterCondition$zodSchema).optional(),
  limit: z.int().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  offset: z.int().optional(),
  order: CustomerFilterOrder$zodSchema.optional(),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.iso.datetime({ offset: true }).optional(),
  status: Status$zodSchema.optional(),
});
