/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CustomCurrencyLineItem = {
  amount?: string | undefined;
  invoice_level_discount?: string | undefined;
  line_item_discount?: string | undefined;
  prepaid_credits_applied?: string | undefined;
};

export const CustomCurrencyLineItem$zodSchema: z.ZodType<
  CustomCurrencyLineItem
> = z.object({
  amount: z.string().optional(),
  invoice_level_discount: z.string().optional(),
  line_item_discount: z.string().optional(),
  prepaid_credits_applied: z.string().optional(),
});
