/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BillingPeriodInfo,
  BillingPeriodInfo$zodSchema,
} from "./billingperiodinfo.js";
import {
  FeatureUsageSummary,
  FeatureUsageSummary$zodSchema,
} from "./featureusagesummary.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type CustomerUsageSummaryResponse = {
  customer_id?: string | undefined;
  features?: Array<FeatureUsageSummary> | undefined;
  pagination?: PaginationResponse | undefined;
  period?: BillingPeriodInfo | undefined;
};

export const CustomerUsageSummaryResponse$zodSchema: z.ZodType<
  CustomerUsageSummaryResponse
> = z.object({
  customer_id: z.string().optional(),
  features: z.array(FeatureUsageSummary$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
  period: BillingPeriodInfo$zodSchema.optional(),
});
