/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerLookupResult,
  CustomerLookupResult$zodSchema,
} from "./customerlookupresult.js";
import { FailurePoint, FailurePoint$zodSchema } from "./failurepoint.js";
import {
  MeterMatchingResult,
  MeterMatchingResult$zodSchema,
} from "./metermatchingresult.js";
import {
  PriceLookupResult,
  PriceLookupResult$zodSchema,
} from "./pricelookupresult.js";
import {
  SubscriptionLineItemLookupResult,
  SubscriptionLineItemLookupResult$zodSchema,
} from "./subscriptionlineitemlookupresult.js";

export type DebugTracker = {
  customer_lookup?: CustomerLookupResult | undefined;
  failure_point?: FailurePoint | undefined;
  meter_matching?: MeterMatchingResult | undefined;
  price_lookup?: PriceLookupResult | undefined;
  subscription_line_item_lookup?: SubscriptionLineItemLookupResult | undefined;
};

export const DebugTracker$zodSchema: z.ZodType<DebugTracker> = z.object({
  customer_lookup: CustomerLookupResult$zodSchema.optional(),
  failure_point: FailurePoint$zodSchema.optional(),
  meter_matching: MeterMatchingResult$zodSchema.optional(),
  price_lookup: PriceLookupResult$zodSchema.optional(),
  subscription_line_item_lookup: SubscriptionLineItemLookupResult$zodSchema
    .optional(),
});
