/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeleteSubscriptionLineItemRequest,
  DeleteSubscriptionLineItemRequest$zodSchema,
} from "./deletesubscriptionlineitemrequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionLineItemResponse,
  SubscriptionLineItemResponse$zodSchema,
} from "./subscriptionlineitemresponse.js";

export type DeleteSubscriptionLineItemRequestRequest = {
  id: string;
  body: DeleteSubscriptionLineItemRequest;
};

export const DeleteSubscriptionLineItemRequestRequest$zodSchema: z.ZodType<
  DeleteSubscriptionLineItemRequestRequest
> = z.object({
  body: DeleteSubscriptionLineItemRequest$zodSchema.describe(
    "Delete Line Item Request",
  ),
  id: z.string().describe("Line Item ID"),
});

export type DeleteSubscriptionLineItemResponse =
  | SubscriptionLineItemResponse
  | ErrorResponse;

export const DeleteSubscriptionLineItemResponse$zodSchema: z.ZodType<
  DeleteSubscriptionLineItemResponse
> = z.union([
  SubscriptionLineItemResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
