/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeleteCustomerRequest = { id: string };

export const DeleteCustomerRequest$zodSchema: z.ZodType<DeleteCustomerRequest> =
  z.object({
    id: z.string().describe("Customer ID"),
  });
