/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type DeletePlanRequest = { id: string };

export const DeletePlanRequest$zodSchema: z.ZodType<DeletePlanRequest> = z
  .object({
    id: z.string().describe("Plan ID"),
  });

export type DeletePlanResponse = SuccessResponse | ErrorResponse;

export const DeletePlanResponse$zodSchema: z.ZodType<DeletePlanResponse> = z
  .union([
    SuccessResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
