/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DeletePriceRequest,
  DeletePriceRequest$zodSchema,
} from "./deletepricerequest.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type DeletePriceRequestRequest = {
  id: string;
  body: DeletePriceRequest;
};

export const DeletePriceRequestRequest$zodSchema: z.ZodType<
  DeletePriceRequestRequest
> = z.object({
  body: DeletePriceRequest$zodSchema.describe("Delete Price Request"),
  id: z.string().describe("Price ID"),
});

export type DeletePriceResponse = SuccessResponse | ErrorResponse;

export const DeletePriceResponse$zodSchema: z.ZodType<DeletePriceResponse> = z
  .union([
    SuccessResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
