/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type DeletePriceRequest = { end_date?: string | undefined };

export const DeletePriceRequest$zodSchema: z.ZodType<DeletePriceRequest> = z
  .object({
    end_date: z.iso.datetime({ offset: true }).optional(),
  });
