/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntityChangeBehaviour,
  EntityChangeBehaviour$zodSchema,
} from "./entitychangebehaviour.js";
import {
  SubscriptionChangeEntityType,
  SubscriptionChangeEntityType$zodSchema,
} from "./subscriptionchangeentitytype.js";

export type EntityChangeResult = {
  behaviour?: EntityChangeBehaviour | undefined;
  entity_id?: string | undefined;
  entity_type?: SubscriptionChangeEntityType | undefined;
  reference_id?: string | undefined;
};

export const EntityChangeResult$zodSchema: z.ZodType<EntityChangeResult> = z
  .object({
    behaviour: EntityChangeBehaviour$zodSchema.optional(),
    entity_id: z.string().optional(),
    entity_type: SubscriptionChangeEntityType$zodSchema.optional(),
    reference_id: z.string().optional(),
  });
