/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementGrantMeasure = {
  Quantity: "quantity",
  Amount: "amount",
} as const;
export type EntitlementGrantMeasure = ClosedEnum<
  typeof EntitlementGrantMeasure
>;

export const EntitlementGrantMeasure$zodSchema = z.enum([
  "quantity",
  "amount",
]);
