/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  IntegrationEntityType,
  IntegrationEntityType$zodSchema,
} from "./integrationentitytype.js";
import { Status, Status$zodSchema } from "./status.js";

export type EntityIntegrationMappingResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: IntegrationEntityType | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: any } | undefined;
  provider_entity_id?: string | undefined;
  provider_type?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const EntityIntegrationMappingResponse$zodSchema: z.ZodType<
  EntityIntegrationMappingResponse
> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: IntegrationEntityType$zodSchema.optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.any()).optional(),
  provider_entity_id: z.string().optional(),
  provider_type: z.string().optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
