/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementGrantDurationUnit = {
  Hour: "hour",
  Day: "day",
  Week: "week",
} as const;
export type EntitlementGrantDurationUnit = ClosedEnum<
  typeof EntitlementGrantDurationUnit
>;

export const EntitlementGrantDurationUnit$zodSchema = z.enum([
  "hour",
  "day",
  "week",
]);
