/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntityChangeBehaviour,
  EntityChangeBehaviour$zodSchema,
} from "./entitychangebehaviour.js";

export type EntityChangePolicy = {
  default_behaviour?: EntityChangeBehaviour | undefined;
  overrides?: { [k: string]: EntityChangeBehaviour } | undefined;
};

export const EntityChangePolicy$zodSchema: z.ZodType<EntityChangePolicy> = z
  .object({
    default_behaviour: EntityChangeBehaviour$zodSchema.optional(),
    overrides: z.record(z.string(), EntityChangeBehaviour$zodSchema).optional()
      .describe(
        "Overrides is keyed by addon_associations.id (instance), not catalogue addon_id.\nThat is the id an EntityChangeResult reports as EntityID.",
      ),
  });
