/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementAggregationMode = {
  Additive: "additive",
  Parallel: "parallel",
} as const;
export type EntitlementAggregationMode = ClosedEnum<
  typeof EntitlementAggregationMode
>;

export const EntitlementAggregationMode$zodSchema = z.enum([
  "additive",
  "parallel",
]);
