/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementSourceEntityType = {
  Plan: "plan",
  Addon: "addon",
  Subscription: "subscription",
} as const;
export type EntitlementSourceEntityType = ClosedEnum<
  typeof EntitlementSourceEntityType
>;

export const EntitlementSourceEntityType$zodSchema = z.enum([
  "plan",
  "addon",
  "subscription",
]);
