/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementGrantStatus = {
  Active: "active",
  Exhausted: "exhausted",
} as const;
export type EntitlementGrantStatus = ClosedEnum<typeof EntitlementGrantStatus>;

export const EntitlementGrantStatus$zodSchema = z.enum([
  "active",
  "exhausted",
]);
