/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntitlementGrantAllocationBehavior = {
  FirstUsage: "first_usage",
  UnitStart: "unit_start",
} as const;
export type EntitlementGrantAllocationBehavior = ClosedEnum<
  typeof EntitlementGrantAllocationBehavior
>;

export const EntitlementGrantAllocationBehavior$zodSchema = z.enum([
  "first_usage",
  "unit_start",
]);
