/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EntityChangeBehaviour = {
  Carry: "carry",
  Drop: "drop",
  Add: "add",
} as const;
export type EntityChangeBehaviour = ClosedEnum<typeof EntityChangeBehaviour>;

export const EntityChangeBehaviour$zodSchema = z.enum([
  "carry",
  "drop",
  "add",
]);
