/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorCode, ErrorCode$zodSchema } from "./errorcode.js";

export type ErrorResponse = {
  code?: ErrorCode | undefined;
  http_status_code?: number | undefined;
  message?: string | undefined;
};

export const ErrorResponse$zodSchema: z.ZodType<ErrorResponse> = z.object({
  code: ErrorCode$zodSchema.optional(),
  http_status_code: z.int().optional(),
  message: z.string().optional(),
});
