/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const EventProcessingStatusType = {
  Processed: "processed",
  Processing: "processing",
  Failed: "failed",
} as const;
export type EventProcessingStatusType = ClosedEnum<
  typeof EventProcessingStatusType
>;

export const EventProcessingStatusType$zodSchema = z.enum([
  "processed",
  "processing",
  "failed",
]);
