/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Event = {
  customer_id?: string | undefined;
  environment_id?: string | undefined;
  event_name?: string | undefined;
  external_customer_id?: string | undefined;
  id?: string | undefined;
  properties?: { [k: string]: any } | undefined;
  source?: string | undefined;
  timestamp?: string | undefined;
};

export const Event$zodSchema: z.ZodType<Event> = z.object({
  customer_id: z.string().optional(),
  environment_id: z.string().optional(),
  event_name: z.string().optional(),
  external_customer_id: z.string().optional(),
  id: z.string().optional(),
  properties: z.record(z.string(), z.any()).optional(),
  source: z.string().optional(),
  timestamp: z.string().optional(),
});
