/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type EventCostInfo = {
  costNanoUsd?: string | undefined;
  requestId?: string | undefined;
};

export const EventCostInfo$zodSchema: z.ZodType<EventCostInfo> = z.object({
  costNanoUsd: z.string().optional(),
  requestId: z.string().optional(),
});
