/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionChangeExecuteResponse,
  SubscriptionChangeExecuteResponse$zodSchema,
} from "./subscriptionchangeexecuteresponse.js";
import {
  SubscriptionChangeRequest,
  SubscriptionChangeRequest$zodSchema,
} from "./subscriptionchangerequest.js";

export type ExecuteSubscriptionChangeRequest = {
  id: string;
  body: SubscriptionChangeRequest;
};

export const ExecuteSubscriptionChangeRequest$zodSchema: z.ZodType<
  ExecuteSubscriptionChangeRequest
> = z.object({
  body: SubscriptionChangeRequest$zodSchema.describe(
    "Subscription change request",
  ),
  id: z.string().describe("Subscription ID"),
});

export type ExecuteSubscriptionChangeResponse =
  | SubscriptionChangeExecuteResponse
  | ErrorResponse;

export const ExecuteSubscriptionChangeResponse$zodSchema: z.ZodType<
  ExecuteSubscriptionChangeResponse
> = z.union([
  SubscriptionChangeExecuteResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
