/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ExecuteSubscriptionModifyRequest,
  ExecuteSubscriptionModifyRequest$zodSchema,
} from "./executesubscriptionmodifyrequest.js";
import {
  SubscriptionModifyResponse,
  SubscriptionModifyResponse$zodSchema,
} from "./subscriptionmodifyresponse.js";

export type ExecuteSubscriptionModifyRequestRequest = {
  id: string;
  body: ExecuteSubscriptionModifyRequest;
};

export const ExecuteSubscriptionModifyRequestRequest$zodSchema: z.ZodType<
  ExecuteSubscriptionModifyRequestRequest
> = z.object({
  body: ExecuteSubscriptionModifyRequest$zodSchema.describe(
    "Modification request",
  ),
  id: z.string().describe("Subscription ID"),
});

export type ExecuteSubscriptionModifyResponse =
  | SubscriptionModifyResponse
  | ErrorResponse;

export const ExecuteSubscriptionModifyResponse$zodSchema: z.ZodType<
  ExecuteSubscriptionModifyResponse
> = z.union([
  SubscriptionModifyResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
