/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ExecuteInvoiceModifyRequest,
  ExecuteInvoiceModifyRequest$zodSchema,
} from "./executeinvoicemodifyrequest.js";
import {
  InvoiceModifyResponse,
  InvoiceModifyResponse$zodSchema,
} from "./invoicemodifyresponse.js";

export type ExecuteInvoiceModifyRequestRequest = {
  id: string;
  body: ExecuteInvoiceModifyRequest;
};

export const ExecuteInvoiceModifyRequestRequest$zodSchema: z.ZodType<
  ExecuteInvoiceModifyRequestRequest
> = z.object({
  body: ExecuteInvoiceModifyRequest$zodSchema.describe("Modification request"),
  id: z.string().describe("Invoice ID"),
});

export type ExecuteInvoiceModifyResponse =
  | InvoiceModifyResponse
  | ErrorResponse;

export const ExecuteInvoiceModifyResponse$zodSchema: z.ZodType<
  ExecuteInvoiceModifyResponse
> = z.union([
  InvoiceModifyResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
