/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PlanChangeScheduleResult,
  PlanChangeScheduleResult$zodSchema,
} from "./planchangescheduleresult.js";

export type ExecutionDetails = {
  plan_change?: PlanChangeScheduleResult | undefined;
};

export const ExecutionDetails$zodSchema: z.ZodType<ExecutionDetails> = z.object(
  {
    plan_change: PlanChangeScheduleResult$zodSchema.optional(),
  },
);
