/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionChangeV2Request,
  SubscriptionChangeV2Request$zodSchema,
} from "./subscriptionchangev2request.js";
import {
  SubscriptionChangeV2Response,
  SubscriptionChangeV2Response$zodSchema,
} from "./subscriptionchangev2response.js";

export type ExecuteSubscriptionPlanChangeV2Request = {
  id: string;
  body: SubscriptionChangeV2Request;
};

export const ExecuteSubscriptionPlanChangeV2Request$zodSchema: z.ZodType<
  ExecuteSubscriptionPlanChangeV2Request
> = z.object({
  body: SubscriptionChangeV2Request$zodSchema.describe("Plan change request"),
  id: z.string().describe("Subscription ID"),
});

export type ExecuteSubscriptionPlanChangeV2Response =
  | SubscriptionChangeV2Response
  | ErrorResponse;

export const ExecuteSubscriptionPlanChangeV2Response$zodSchema: z.ZodType<
  ExecuteSubscriptionPlanChangeV2Response
> = z.union([
  SubscriptionChangeV2Response$zodSchema,
  ErrorResponse$zodSchema,
]);
