/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubModifyGroupedInvoicingParams,
  SubModifyGroupedInvoicingParams$zodSchema,
} from "./submodifygroupedinvoicingparams.js";
import {
  SubModifyInheritanceRequest,
  SubModifyInheritanceRequest$zodSchema,
} from "./submodifyinheritancerequest.js";
import {
  SubModifyQuantityChangeRequest,
  SubModifyQuantityChangeRequest$zodSchema,
} from "./submodifyquantitychangerequest.js";
import {
  SubModifyTrialEndRequest,
  SubModifyTrialEndRequest$zodSchema,
} from "./submodifytrialendrequest.js";
import {
  SubscriptionModifyType,
  SubscriptionModifyType$zodSchema,
} from "./subscriptionmodifytype.js";

export type ExecuteSubscriptionModifyRequest = {
  grouped_invoicing_params?: SubModifyGroupedInvoicingParams | undefined;
  inheritance_params?: SubModifyInheritanceRequest | undefined;
  quantity_change_params?: SubModifyQuantityChangeRequest | undefined;
  trial_end_params?: SubModifyTrialEndRequest | undefined;
  type: SubscriptionModifyType;
};

export const ExecuteSubscriptionModifyRequest$zodSchema: z.ZodType<
  ExecuteSubscriptionModifyRequest
> = z.object({
  grouped_invoicing_params: SubModifyGroupedInvoicingParams$zodSchema
    .optional(),
  inheritance_params: SubModifyInheritanceRequest$zodSchema.optional(),
  quantity_change_params: SubModifyQuantityChangeRequest$zodSchema.optional(),
  trial_end_params: SubModifyTrialEndRequest$zodSchema.optional(),
  type: SubscriptionModifyType$zodSchema,
});
