/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FailurePointType = {
  CustomerLookup: "customer_lookup",
  MeterLookup: "meter_lookup",
  PriceLookup: "price_lookup",
  SubscriptionLineItemLookup: "subscription_line_item_lookup",
} as const;
export type FailurePointType = ClosedEnum<typeof FailurePointType>;

export const FailurePointType$zodSchema = z.enum([
  "customer_lookup",
  "meter_lookup",
  "price_lookup",
  "subscription_line_item_lookup",
]);
