/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import { FeatureType, FeatureType$zodSchema } from "./featuretype.js";
import { GroupGroup, GroupGroup$zodSchema } from "./groupgroup.js";
import { ReportingUnit, ReportingUnit$zodSchema } from "./reportingunit.js";
import { Status, Status$zodSchema } from "./status.js";

export type Feature = {
  alert_settings?: AlertSettings | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  group?: GroupGroup | undefined;
  group_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_id?: string | undefined;
  name?: string | undefined;
  reporting_unit?: ReportingUnit | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  type?: FeatureType | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const Feature$zodSchema: z.ZodType<Feature> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  group: GroupGroup$zodSchema.optional(),
  group_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_id: z.string().optional(),
  name: z.string().optional(),
  reporting_unit: ReportingUnit$zodSchema.optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  type: FeatureType$zodSchema.optional(),
  unit_plural: z.string().optional(),
  unit_singular: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
