/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FeatureUsageInfo = {
  customer_id?: string | undefined;
  feature_id?: string | undefined;
  meter_id?: string | undefined;
  price_id?: string | undefined;
  processed_at?: string | undefined;
  qty_total?: string | undefined;
  sub_line_item_id?: string | undefined;
  subscription_id?: string | undefined;
};

export const FeatureUsageInfo$zodSchema: z.ZodType<FeatureUsageInfo> = z.object(
  {
    customer_id: z.string().optional(),
    feature_id: z.string().optional(),
    meter_id: z.string().optional(),
    price_id: z.string().optional(),
    processed_at: z.iso.datetime({ offset: true }).optional(),
    qty_total: z.string().optional(),
    sub_line_item_id: z.string().optional(),
    subscription_id: z.string().optional(),
  },
);
