/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FeatureType = {
  Metered: "metered",
  Boolean: "boolean",
  Static: "static",
} as const;
export type FeatureType = ClosedEnum<typeof FeatureType>;

export const FeatureType$zodSchema = z.enum([
  "metered",
  "boolean",
  "static",
]);
