/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FilterOperatorType = {
  Eq: "eq",
  Contains: "contains",
  NotContains: "not_contains",
  Gt: "gt",
  Lt: "lt",
  In: "in",
  NotIn: "not_in",
  Before: "before",
  After: "after",
} as const;
export type FilterOperatorType = ClosedEnum<typeof FilterOperatorType>;

export const FilterOperatorType$zodSchema = z.enum([
  "eq",
  "contains",
  "not_contains",
  "gt",
  "lt",
  "in",
  "not_in",
  "before",
  "after",
]);
