/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type FinalizeInvoiceRequest = { id: string };

export const FinalizeInvoiceRequest$zodSchema: z.ZodType<
  FinalizeInvoiceRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type FinalizeInvoiceResponse = SuccessResponse | ErrorResponse;

export const FinalizeInvoiceResponse$zodSchema: z.ZodType<
  FinalizeInvoiceResponse
> = z.union([
  SuccessResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
