/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  FxConversionSource,
  FxConversionSource$zodSchema,
} from "./fxconversionsource.js";
import { FXRateScope, FXRateScope$zodSchema } from "./fxratescope.js";

export type FxConversion = {
  billing_currency?: string | undefined;
  charge_currency?: string | undefined;
  converted_at?: string | undefined;
  rate?: string | undefined;
  rate_id?: string | undefined;
  scope?: FXRateScope | undefined;
  source?: FxConversionSource | undefined;
};

export const FxConversion$zodSchema: z.ZodType<FxConversion> = z.object({
  billing_currency: z.string().optional().describe(
    "BillingCurrency is the currency the invoice was issued in.",
  ),
  charge_currency: z.string().optional().describe(
    "ChargeCurrency is the invoice's original (draft) currency.",
  ),
  converted_at: z.iso.datetime({ offset: true }).optional().describe(
    "ConvertedAt is when the conversion ran.",
  ),
  rate: z.string().optional().describe(
    "Rate is the frozen rate: billing per 1 charge unit.",
  ),
  rate_id: z.string().optional().describe(
    "RateID is the fx_rates row used, for reference only; never read again.",
  ),
  scope: FXRateScope$zodSchema.optional(),
  source: FxConversionSource$zodSchema.optional(),
});
