/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type FxConversionSource = {
  net?: string | undefined;
  subtotal?: string | undefined;
  total_discount?: string | undefined;
  total_prepaid_credits_applied?: string | undefined;
};

export const FxConversionSource$zodSchema: z.ZodType<FxConversionSource> = z
  .object({
    net: z.string().optional(),
    subtotal: z.string().optional(),
    total_discount: z.string().optional(),
    total_prepaid_credits_applied: z.string().optional(),
  });
