/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const FXRateScope = {
  Tenant: "tenant",
  Customer: "customer",
  Subscription: "subscription",
} as const;
export type FXRateScope = ClosedEnum<typeof FXRateScope>;

export const FXRateScope$zodSchema = z.enum([
  "tenant",
  "customer",
  "subscription",
]);
