/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListCreditGrantApplicationsResponse,
  ListCreditGrantApplicationsResponse$zodSchema,
} from "./listcreditgrantapplicationsresponse.js";

export type GetCustomerUpcomingGrantsRequest = { id: string };

export const GetCustomerUpcomingGrantsRequest$zodSchema: z.ZodType<
  GetCustomerUpcomingGrantsRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetCustomerUpcomingGrantsResponse =
  | ListCreditGrantApplicationsResponse
  | ErrorResponse;

export const GetCustomerUpcomingGrantsResponse$zodSchema: z.ZodType<
  GetCustomerUpcomingGrantsResponse
> = z.union([
  ListCreditGrantApplicationsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
