/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerEntitlementsResponse,
  CustomerEntitlementsResponse$zodSchema,
} from "./customerentitlementsresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetCustomerEntitlementsRequest = { id: string };

export const GetCustomerEntitlementsRequest$zodSchema: z.ZodType<
  GetCustomerEntitlementsRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetCustomerEntitlementsResponse =
  | CustomerEntitlementsResponse
  | ErrorResponse;

export const GetCustomerEntitlementsResponse$zodSchema: z.ZodType<
  GetCustomerEntitlementsResponse
> = z.union([
  CustomerEntitlementsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
