/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerResponse,
  CustomerResponse$zodSchema,
} from "./customerresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetCustomerRequest = { id: string };

export const GetCustomerRequest$zodSchema: z.ZodType<GetCustomerRequest> = z
  .object({
    id: z.string().describe("Customer ID"),
  });

export type GetCustomerResponse = CustomerResponse | ErrorResponse;

export const GetCustomerResponse$zodSchema: z.ZodType<GetCustomerResponse> = z
  .union([
    CustomerResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
