/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerResponse,
  CustomerResponse$zodSchema,
} from "./customerresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetCustomerByExternalIdRequest = { external_id: string };

export const GetCustomerByExternalIdRequest$zodSchema: z.ZodType<
  GetCustomerByExternalIdRequest
> = z.object({
  external_id: z.string().describe("Customer External ID"),
});

export type GetCustomerByExternalIdResponse = CustomerResponse | ErrorResponse;

export const GetCustomerByExternalIdResponse$zodSchema: z.ZodType<
  GetCustomerByExternalIdResponse
> = z.union([
  CustomerResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
