/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerMultiCurrencyInvoiceSummary,
  CustomerMultiCurrencyInvoiceSummary$zodSchema,
} from "./customermulticurrencyinvoicesummary.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetCustomerInvoiceSummaryRequest = { id: string };

export const GetCustomerInvoiceSummaryRequest$zodSchema: z.ZodType<
  GetCustomerInvoiceSummaryRequest
> = z.object({
  id: z.string().describe("Customer ID"),
});

export type GetCustomerInvoiceSummaryResponse =
  | CustomerMultiCurrencyInvoiceSummary
  | ErrorResponse;

export const GetCustomerInvoiceSummaryResponse$zodSchema: z.ZodType<
  GetCustomerInvoiceSummaryResponse
> = z.union([
  CustomerMultiCurrencyInvoiceSummary$zodSchema,
  ErrorResponse$zodSchema,
]);
