/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetEventByIDResponse,
  GetEventByIDResponse$zodSchema,
} from "./geteventbyidresponse.js";

export type GetEventRequest = { id: string };

export const GetEventRequest$zodSchema: z.ZodType<GetEventRequest> = z.object({
  id: z.string().describe("Event ID"),
});

export type GetEventResponse = GetEventByIDResponse | ErrorResponse;

export const GetEventResponse$zodSchema: z.ZodType<GetEventResponse> = z.union([
  GetEventByIDResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
