/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetEventsRequest = {
  end_time?: string | undefined;
  event_id?: string | undefined;
  event_name?: string | undefined;
  external_customer_id?: string | undefined;
  iter_first_key?: string | undefined;
  iter_last_key?: string | undefined;
  offset?: number | undefined;
  order?: string | undefined;
  page_size?: number | undefined;
  property_filters?: { [k: string]: Array<string> } | undefined;
  sort?: string | undefined;
  source?: string | undefined;
  start_time?: string | undefined;
};

export const GetEventsRequest$zodSchema: z.ZodType<GetEventsRequest> = z.object(
  {
    end_time: z.iso.datetime({ offset: true }).optional().describe(
      "End time of the events to be fetched in ISO 8601 format\nDefaults to now if not provided",
    ),
    event_id: z.string().optional().describe(
      "Event ID is the idempotency key for the event",
    ),
    event_name: z.string().optional().describe(
      "Event name / Unique identifier for the event in your system",
    ),
    external_customer_id: z.string().optional().describe(
      "Customer ID in your system that was sent with the event",
    ),
    iter_first_key: z.string().optional().describe(
      "First key to iterate over the events",
    ),
    iter_last_key: z.string().optional().describe(
      "Last key to iterate over the events",
    ),
    offset: z.int().optional().describe(
      "Offset to fetch the events and is set to 0 by default",
    ),
    order: z.string().optional().describe(
      "Order by condition. Allowed values (case sensitive): asc, desc (default: desc)",
    ),
    page_size: z.int().optional().describe(
      "Page size to fetch the events and is set to 50 by default",
    ),
    property_filters: z.record(z.string(), z.array(z.string())).optional()
      .describe(
        "Property filters to filter the events by the keys in `properties` field of the event",
      ),
    sort: z.string().optional().describe(
      "Sort by the field. Allowed values (case sensitive): timestamp, event_name (default: timestamp)",
    ),
    source: z.string().optional().describe(
      "Source to filter the events by the source",
    ),
    start_time: z.iso.datetime({ offset: true }).optional().describe(
      "Start time of the events to be fetched in ISO 8601 format\nDefaults to last 7 days from now if not provided",
    ),
  },
);
