/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetHuggingFaceBillingDataRequest = { requestIds: Array<string> };

export const GetHuggingFaceBillingDataRequest$zodSchema: z.ZodType<
  GetHuggingFaceBillingDataRequest
> = z.object({
  requestIds: z.array(z.string()),
});
