/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PriceResponse, PriceResponse$zodSchema } from "./priceresponse.js";

export type GetPriceByLookupKeyRequest = { lookup_key: string };

export const GetPriceByLookupKeyRequest$zodSchema: z.ZodType<
  GetPriceByLookupKeyRequest
> = z.object({
  lookup_key: z.string().describe("Lookup key"),
});

export type GetPriceByLookupKeyResponse = PriceResponse | ErrorResponse;

export const GetPriceByLookupKeyResponse$zodSchema: z.ZodType<
  GetPriceByLookupKeyResponse
> = z.union([
  PriceResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
