/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetPreviewInvoiceRequest = {
  hide_zero_charges_line_items?: boolean | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  subscription_id: string;
};

export const GetPreviewInvoiceRequest$zodSchema: z.ZodType<
  GetPreviewInvoiceRequest
> = z.object({
  hide_zero_charges_line_items: z.boolean().default(false).describe(
    "hide_zero_charges_line_items indicates whether to hide line items with zero cost",
  ),
  period_end: z.iso.datetime({ offset: true }).optional().describe(
    "period_end is the optional end date of the period to preview",
  ),
  period_start: z.iso.datetime({ offset: true }).optional().describe(
    "period_start is the optional start date of the period to preview",
  ),
  subscription_id: z.string().describe(
    "subscription_id is the unique identifier of the subscription to preview invoice for",
  ),
});
