/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PriceResponse, PriceResponse$zodSchema } from "./priceresponse.js";

export type GetPriceRequest = { id: string };

export const GetPriceRequest$zodSchema: z.ZodType<GetPriceRequest> = z.object({
  id: z.string().describe("Price ID"),
});

export type GetPriceResponse = PriceResponse | ErrorResponse;

export const GetPriceResponse$zodSchema: z.ZodType<GetPriceResponse> = z.union([
  PriceResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
