/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubscriptionScheduleResponse,
  SubscriptionScheduleResponse$zodSchema,
} from "./subscriptionscheduleresponse.js";

/**
 * List of pending schedules for a subscription
 */
export type GetPendingSchedulesResponse = {
  count?: number | undefined;
  schedules?: Array<SubscriptionScheduleResponse> | undefined;
};

export const GetPendingSchedulesResponse$zodSchema: z.ZodType<
  GetPendingSchedulesResponse
> = z.object({
  count: z.int().optional().describe(
    "count is the number of pending schedules",
  ),
  schedules: z.array(SubscriptionScheduleResponse$zodSchema).optional()
    .describe("schedules is the list of pending schedules"),
}).describe("List of pending schedules for a subscription");
