/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetSubscriptionScheduleRequest = { schedule_id: string };

export const GetSubscriptionScheduleRequest$zodSchema: z.ZodType<
  GetSubscriptionScheduleRequest
> = z.object({
  schedule_id: z.string().describe("Schedule ID"),
});
