/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionEntitlementsResponse,
  SubscriptionEntitlementsResponse$zodSchema,
} from "./subscriptionentitlementsresponse.js";

export type GetSubscriptionEntitlementsRequest = {
  id: string;
  feature_ids?: Array<string> | undefined;
};

export const GetSubscriptionEntitlementsRequest$zodSchema: z.ZodType<
  GetSubscriptionEntitlementsRequest
> = z.object({
  feature_ids: z.array(z.string()).describe("Feature IDs to filter by")
    .optional(),
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionEntitlementsResponse =
  | SubscriptionEntitlementsResponse
  | ErrorResponse;

export const GetSubscriptionEntitlementsResponse$zodSchema: z.ZodType<
  GetSubscriptionEntitlementsResponse
> = z.union([
  SubscriptionEntitlementsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
