/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListSubscriptionsResponse,
  ListSubscriptionsResponse$zodSchema,
} from "./listsubscriptionsresponse.js";

export type GetSubscriptionsForCustomerRequest = {
  external_id: string;
  expand?: string | undefined;
};

export const GetSubscriptionsForCustomerRequest$zodSchema: z.ZodType<
  GetSubscriptionsForCustomerRequest
> = z.object({
  expand: z.string().describe(
    "Comma-separated fields to expand: subscription_line_items, subscription_line_items.meters, entitlements, plan, customer",
  ).optional(),
  external_id: z.string().describe("Customer External ID"),
});

export type GetSubscriptionsForCustomerResponse =
  | ListSubscriptionsResponse
  | ErrorResponse;

export const GetSubscriptionsForCustomerResponse$zodSchema: z.ZodType<
  GetSubscriptionsForCustomerResponse
> = z.union([
  ListSubscriptionsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
