/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListAddonAssociationsResponse,
  ListAddonAssociationsResponse$zodSchema,
} from "./listaddonassociationsresponse.js";

export type GetSubscriptionAddonAssociationsRequest = { id: string };

export const GetSubscriptionAddonAssociationsRequest$zodSchema: z.ZodType<
  GetSubscriptionAddonAssociationsRequest
> = z.object({
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionAddonAssociationsResponse =
  | ListAddonAssociationsResponse
  | ErrorResponse;

export const GetSubscriptionAddonAssociationsResponse$zodSchema: z.ZodType<
  GetSubscriptionAddonAssociationsResponse
> = z.union([
  ListAddonAssociationsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
