/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetUsageBySubscriptionResponse,
  GetUsageBySubscriptionResponse$zodSchema,
} from "./getusagebysubscriptionresponse.js";

export type GetSubscriptionUsageResponse =
  | GetUsageBySubscriptionResponse
  | ErrorResponse;

export const GetSubscriptionUsageResponse$zodSchema: z.ZodType<
  GetSubscriptionUsageResponse
> = z.union([
  GetUsageBySubscriptionResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
