/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetSubscriptionScheduleRequest = { id: string };

export const GetSubscriptionScheduleRequest$zodSchema: z.ZodType<
  GetSubscriptionScheduleRequest
> = z.object({
  id: z.string().describe("Schedule ID"),
});
