/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddonAssociationResponse,
  AddonAssociationResponse$zodSchema,
} from "./addonassociationresponse.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type GetSubscriptionAddonAssociationsRequest = { id: string };

export const GetSubscriptionAddonAssociationsRequest$zodSchema: z.ZodType<
  GetSubscriptionAddonAssociationsRequest
> = z.object({
  id: z.string().describe("Subscription ID"),
});

export type GetSubscriptionAddonAssociationsResponse =
  | Array<AddonAssociationResponse>
  | ErrorResponse;

export const GetSubscriptionAddonAssociationsResponse$zodSchema: z.ZodType<
  GetSubscriptionAddonAssociationsResponse
> = z.union([
  z.array(AddonAssociationResponse$zodSchema).describe("OK"),
  ErrorResponse$zodSchema,
]);
