/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetUsageResponse,
  GetUsageResponse$zodSchema,
} from "./getusageresponse.js";

export type GetUsageStatisticsResponse = GetUsageResponse | ErrorResponse;

export const GetUsageStatisticsResponse$zodSchema: z.ZodType<
  GetUsageStatisticsResponse
> = z.union([
  GetUsageResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
