/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetUsageResponse,
  GetUsageResponse$zodSchema,
} from "./getusageresponse.js";

export type GetUsageByMeterResponse = GetUsageResponse | ErrorResponse;

export const GetUsageByMeterResponse$zodSchema: z.ZodType<
  GetUsageByMeterResponse
> = z.union([
  GetUsageResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
