/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregationType,
  AggregationType$zodSchema,
} from "./aggregationtype.js";
import { WindowSize, WindowSize$zodSchema } from "./windowsize.js";

export type GetUsageRequest = {
  aggregation_type: AggregationType;
  billing_anchor?: string | undefined;
  bucket_size?: WindowSize | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  event_name: string;
  external_customer_id?: string | undefined;
  filters?: { [k: string]: Array<string> } | undefined;
  group_by_property?: string | undefined;
  multiplier?: string | undefined;
  property_name?: string | undefined;
  start_time?: string | undefined;
  window_size?: WindowSize | undefined;
};

export const GetUsageRequest$zodSchema: z.ZodType<GetUsageRequest> = z.object({
  aggregation_type: AggregationType$zodSchema,
  billing_anchor: z.iso.datetime({ offset: true }).optional().describe(
    "BillingAnchor enables custom monthly billing periods for usage aggregation.\n\nWhen to use:\n- WindowSize = \"MONTH\" AND you need custom monthly periods (not calendar months)\n- Subscription billing that doesn't align with calendar months\n- Example: Customer signed up on 15th, so billing periods are 15th to 15th\n\nWhen NOT to use:\n- WindowSize != \"MONTH\" (ignored for DAY, HOUR, WEEK, etc.)\n- Standard calendar-based billing (1st to 1st of each month)\n\nExample values:\n- \"2024-03-05T14:30:45.123456789Z\" (5th of each month at 2:30:45 PM)\n- \"2024-01-15T00:00:00Z\" (15th of each month at midnight)\n- \"2024-02-29T12:00:00Z\" (29th of each month at noon - handles leap years)",
  ),
  bucket_size: WindowSize$zodSchema.optional(),
  customer_id: z.string().optional(),
  end_time: z.iso.datetime({ offset: true }).optional(),
  event_name: z.string(),
  external_customer_id: z.string().optional(),
  filters: z.record(z.string(), z.array(z.string())).optional(),
  group_by_property: z.string().optional().describe(
    "GroupByProperty is the property name in event.properties to group by before aggregating.\nWhen set, aggregation is applied per unique value of this property within each bucket,\nthen the per-group results are summed to produce the bucket total.",
  ),
  multiplier: z.string().optional(),
  property_name: z.string().optional().describe(
    "will be empty/ignored in case of COUNT",
  ),
  start_time: z.iso.datetime({ offset: true }).optional(),
  window_size: WindowSize$zodSchema.optional(),
});
