/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AggregationType,
  AggregationType$zodSchema,
} from "./aggregationtype.js";
import { UsageResult, UsageResult$zodSchema } from "./usageresult.js";

export type GetUsageResponse = {
  event_name?: string | undefined;
  results?: Array<UsageResult> | undefined;
  type?: AggregationType | undefined;
  value?: number | undefined;
};

export const GetUsageResponse$zodSchema: z.ZodType<GetUsageResponse> = z.object(
  {
    event_name: z.string().optional(),
    results: z.array(UsageResult$zodSchema).optional(),
    type: AggregationType$zodSchema.optional(),
    value: z.number().optional(),
  },
);
