/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomAnalyticItem,
  CustomAnalyticItem$zodSchema,
} from "./customanalyticitem.js";
import {
  UsageAnalyticItem,
  UsageAnalyticItem$zodSchema,
} from "./usageanalyticitem.js";

export type GetUsageAnalyticsResponse = {
  currency?: string | undefined;
  custom_analytics?: Array<CustomAnalyticItem> | undefined;
  items?: Array<UsageAnalyticItem> | undefined;
  total_cost?: string | undefined;
};

export const GetUsageAnalyticsResponse$zodSchema: z.ZodType<
  GetUsageAnalyticsResponse
> = z.object({
  currency: z.string().optional(),
  custom_analytics: z.array(CustomAnalyticItem$zodSchema).optional(),
  items: z.array(UsageAnalyticItem$zodSchema).optional(),
  total_cost: z.string().optional(),
});
