/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntitlementGrantMeasure,
  EntitlementGrantMeasure$zodSchema,
} from "./entitlementgrantmeasure.js";
import {
  EntitlementGrantStatus,
  EntitlementGrantStatus$zodSchema,
} from "./entitlementgrantstatus.js";

export type GrantAllowanceState = {
  entitlement_id?: string | undefined;
  grant_id?: string | undefined;
  is_active?: boolean | undefined;
  last_computed_at?: string | undefined;
  measure?: EntitlementGrantMeasure | undefined;
  quota?: string | undefined;
  quota_crossed_at?: string | undefined;
  remaining?: string | undefined;
  status?: EntitlementGrantStatus | undefined;
  unlimited?: boolean | undefined;
  usage?: string | undefined;
  valid_from?: string | undefined;
  valid_to?: string | undefined;
};

export const GrantAllowanceState$zodSchema: z.ZodType<GrantAllowanceState> = z
  .object({
    entitlement_id: z.string().optional(),
    grant_id: z.string().optional(),
    is_active: z.boolean().optional(),
    last_computed_at: z.iso.datetime({ offset: true }).optional(),
    measure: EntitlementGrantMeasure$zodSchema.optional(),
    quota: z.string().optional(),
    quota_crossed_at: z.iso.datetime({ offset: true }).optional(),
    remaining: z.string().optional(),
    status: EntitlementGrantStatus$zodSchema.optional(),
    unlimited: z.boolean().optional(),
    usage: z.string().optional(),
    valid_from: z.string().optional(),
    valid_to: z.string().optional(),
  });
