/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GroupedInvoicingChildRequest = {
  external_customer_id: string;
  plan_id: string;
};

export const GroupedInvoicingChildRequest$zodSchema: z.ZodType<
  GroupedInvoicingChildRequest
> = z.object({
  external_customer_id: z.string(),
  plan_id: z.string(),
});
