/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const GroupedInvoicingAction = {
  Add: "add",
  Remove: "remove",
} as const;
export type GroupedInvoicingAction = ClosedEnum<typeof GroupedInvoicingAction>;

export const GroupedInvoicingAction$zodSchema = z.enum([
  "add",
  "remove",
]);
