/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const GroupEntityType = {
  Price: "price",
  Feature: "feature",
} as const;
export type GroupEntityType = ClosedEnum<typeof GroupEntityType>;

export const GroupEntityType$zodSchema = z.enum([
  "price",
  "feature",
]);
