/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GroupResponse = {
  created_at?: string | undefined;
  entity_ids?: Array<string> | undefined;
  entity_type?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

export const GroupResponse$zodSchema: z.ZodType<GroupResponse> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  entity_ids: z.array(z.string()).optional(),
  entity_type: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
});
