/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionRequest,
  AddAddonToSubscriptionRequest$zodSchema,
} from "./addaddontosubscriptionrequest.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  CreateCreditGrantRequest,
  CreateCreditGrantRequest$zodSchema,
} from "./createcreditgrantrequest.js";
import {
  CreateSubscriptionLineItemRequest,
  CreateSubscriptionLineItemRequest$zodSchema,
} from "./createsubscriptionlineitemrequest.js";
import {
  LineItemCommitmentConfig,
  LineItemCommitmentConfig$zodSchema,
} from "./lineitemcommitmentconfig.js";
import {
  OverrideEntitlementRequest,
  OverrideEntitlementRequest$zodSchema,
} from "./overrideentitlementrequest.js";
import {
  OverrideLineItemRequest,
  OverrideLineItemRequest$zodSchema,
} from "./overridelineitemrequest.js";
import {
  SubscriptionCouponInput,
  SubscriptionCouponInput$zodSchema,
} from "./subscriptioncouponinput.js";
import {
  SubscriptionPhaseCreateRequest,
  SubscriptionPhaseCreateRequest$zodSchema,
} from "./subscriptionphasecreaterequest.js";
import {
  TaxRateOverride,
  TaxRateOverride$zodSchema,
} from "./taxrateoverride.js";

export type GroupedInvoicingChildRequest = {
  addons?: Array<AddAddonToSubscriptionRequest> | undefined;
  commitment_amount?: string | undefined;
  commitment_duration?: BillingPeriod | undefined;
  coupons?: Array<string> | undefined;
  credit_grants?: Array<CreateCreditGrantRequest> | undefined;
  enable_true_up?: boolean | undefined;
  external_customer_id: string;
  line_item_commitments?: { [k: string]: LineItemCommitmentConfig } | undefined;
  line_item_coupons?: { [k: string]: Array<string> } | undefined;
  line_items?: Array<CreateSubscriptionLineItemRequest> | undefined;
  overage_factor?: string | undefined;
  override_entitlements?: Array<OverrideEntitlementRequest> | undefined;
  override_line_items?: Array<OverrideLineItemRequest> | undefined;
  phases?: Array<SubscriptionPhaseCreateRequest> | undefined;
  plan_id: string;
  subscription_coupons?: Array<SubscriptionCouponInput> | undefined;
  tax_rate_overrides?: Array<TaxRateOverride> | undefined;
  trial_period_days?: number | undefined;
};

export const GroupedInvoicingChildRequest$zodSchema: z.ZodType<
  GroupedInvoicingChildRequest
> = z.object({
  addons: z.array(AddAddonToSubscriptionRequest$zodSchema).optional(),
  commitment_amount: z.string().optional(),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  coupons: z.array(z.string()).optional().describe(
    "Deprecated: use SubscriptionCoupons instead.",
  ),
  credit_grants: z.array(CreateCreditGrantRequest$zodSchema).optional(),
  enable_true_up: z.boolean().optional(),
  external_customer_id: z.string(),
  line_item_commitments: z.record(
    z.string(),
    LineItemCommitmentConfig$zodSchema,
  ).optional().describe(
    "LineItemCommitments sets per-line-item commitment config, keyed by price_id.",
  ),
  line_item_coupons: z.record(z.string(), z.array(z.string())).optional()
    .describe("Deprecated: use SubscriptionCoupons instead."),
  line_items: z.array(CreateSubscriptionLineItemRequest$zodSchema).optional()
    .describe("LineItems are extra (non-plan) line items added at creation."),
  overage_factor: z.string().optional(),
  override_entitlements: z.array(OverrideEntitlementRequest$zodSchema)
    .optional(),
  override_line_items: z.array(OverrideLineItemRequest$zodSchema).optional()
    .describe(
      "OverrideLineItems overrides specific plan prices for this subscription.",
    ),
  phases: z.array(SubscriptionPhaseCreateRequest$zodSchema).optional(),
  plan_id: z.string(),
  subscription_coupons: z.array(SubscriptionCouponInput$zodSchema).optional()
    .describe(
      "SubscriptionCoupons is the preferred way to attach coupons at creation.\nAccepts coupon_code; optionally targets a line item via price_id.",
    ),
  tax_rate_overrides: z.array(TaxRateOverride$zodSchema).optional(),
  trial_period_days: z.int().optional().describe(
    "TrialPeriodDays: nil = inherit from plan prices, 0 = no trial, >0 = override in days.",
  ),
});
