/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type IngestEventsBulkResponse = { [k: string]: string } | ErrorResponse;

export const IngestEventsBulkResponse$zodSchema: z.ZodType<
  IngestEventsBulkResponse
> = z.union([
  z.record(z.string(), z.string()).describe(
    "message:Event accepted for processing",
  ),
  ErrorResponse$zodSchema,
]);
