/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type IngestEventRequest = {
  customer_id?: string | undefined;
  event_id?: string | undefined;
  event_name: string;
  external_customer_id: string;
  properties?: { [k: string]: string } | undefined;
  source?: string | undefined;
  timestamp?: string | undefined;
};

export const IngestEventRequest$zodSchema: z.ZodType<IngestEventRequest> = z
  .object({
    customer_id: z.string().optional(),
    event_id: z.string().optional(),
    event_name: z.string(),
    external_customer_id: z.string(),
    properties: z.record(z.string(), z.string()).optional().describe(
      "Handled separately for dynamic columns",
    ),
    source: z.string().optional(),
    timestamp: z.string().optional().describe(
      "Handled separately due to parsing",
    ),
  });
