/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";

export type IngestEventResponse = { [k: string]: string } | ErrorResponse;

export const IngestEventResponse$zodSchema: z.ZodType<IngestEventResponse> = z
  .union([
    z.record(z.string(), z.string()).describe(
      "message:Event accepted for processing",
    ),
    ErrorResponse$zodSchema,
  ]);
