/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InlineFXRate = {
  end_date?: string | undefined;
  rate?: string | undefined;
  start_date?: string | undefined;
};

export const InlineFXRate$zodSchema: z.ZodType<InlineFXRate> = z.object({
  end_date: z.iso.datetime({ offset: true }).optional(),
  rate: z.string().optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
});
