/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const IntegrationEntityType = {
  Customer: "customer",
  Plan: "plan",
  Invoice: "invoice",
  Subscription: "subscription",
  Payment: "payment",
  CreditNote: "credit_note",
  Addon: "addon",
  Item: "item",
  ItemPrice: "item_price",
  Price: "price",
} as const;
export type IntegrationEntityType = ClosedEnum<typeof IntegrationEntityType>;

export const IntegrationEntityType$zodSchema = z.enum([
  "customer",
  "plan",
  "invoice",
  "subscription",
  "payment",
  "credit_note",
  "addon",
  "item",
  "item_price",
  "price",
]);
