/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvoiceLineItemPreview = {
  amount?: string | undefined;
  description?: string | undefined;
  is_proration?: boolean | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  quantity?: string | undefined;
  unit_price?: string | undefined;
};

export const InvoiceLineItemPreview$zodSchema: z.ZodType<
  InvoiceLineItemPreview
> = z.object({
  amount: z.string().optional().describe("amount for this line item"),
  description: z.string().optional().describe("description of the line item"),
  is_proration: z.boolean().optional().describe(
    "is_proration indicates if this line item is a proration",
  ),
  period_end: z.iso.datetime({ offset: true }).optional().describe(
    "period_end for this line item (if applicable)",
  ),
  period_start: z.iso.datetime({ offset: true }).optional().describe(
    "period_start for this line item (if applicable)",
  ),
  quantity: z.string().optional().describe("quantity for this line item"),
  unit_price: z.string().optional().describe("unit_price for this line item"),
});
