/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceType = {
  Subscription: "SUBSCRIPTION",
  OneOff: "ONE_OFF",
  Credit: "CREDIT",
} as const;
export type InvoiceType = ClosedEnum<typeof InvoiceType>;

export const InvoiceType$zodSchema = z.enum([
  "SUBSCRIPTION",
  "ONE_OFF",
  "CREDIT",
]);
