/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import {
  InvoiceBillingReason,
  InvoiceBillingReason$zodSchema,
} from "./invoicebillingreason.js";
import { InvoiceStatus, InvoiceStatus$zodSchema } from "./invoicestatus.js";
import { InvoiceType, InvoiceType$zodSchema } from "./invoicetype.js";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";

export const InvoiceFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type InvoiceFilterOrder = ClosedEnum<typeof InvoiceFilterOrder>;

export const InvoiceFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type InvoiceFilter = {
  amount_due_gt?: number | undefined;
  amount_remaining_gt?: number | undefined;
  billing_reason?: InvoiceBillingReason | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  invoice_ids?: Array<string> | undefined;
  invoice_status?: Array<InvoiceStatus> | undefined;
  invoice_type?: InvoiceType | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: InvoiceFilterOrder | undefined;
  payment_status?: Array<PaymentStatus> | undefined;
  period_end_gte?: string | undefined;
  period_end_lte?: string | undefined;
  period_start_gte?: string | undefined;
  period_start_lte?: string | undefined;
  skip_line_items?: boolean | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  subscription_customer_id?: Array<string> | undefined;
  subscription_id?: string | undefined;
};

export const InvoiceFilter$zodSchema: z.ZodType<InvoiceFilter> = z.object({
  amount_due_gt: z.number().optional().describe(
    "amount_due_gt filters invoices with a total amount due greater than the specified value\nUseful for finding invoices above a certain threshold or identifying high-value invoices",
  ),
  amount_remaining_gt: z.number().optional().describe(
    "amount_remaining_gt filters invoices with an outstanding balance greater than the specified value\nUseful for finding invoices that still have significant unpaid amounts",
  ),
  billing_reason: InvoiceBillingReason$zodSchema.optional(),
  currency: z.string().optional().describe(
    "currency filters invoices by their currency (ISO 4217 code, e.g. \"usd\", \"eur\").\nMatches on the invoices.currency column exactly.",
  ),
  customer_id: z.string().optional().describe(
    "customer_id filters invoices for a specific customer using FlexPrice's internal customer ID\nThis is the ID returned by FlexPrice when creating or retrieving customers",
  ),
  end_time: z.iso.datetime({ offset: true }).optional(),
  expand: z.string().optional(),
  external_customer_id: z.string().optional().describe(
    "external_customer_id filters invoices for a customer using your system's customer identifier\nThis is the ID you provided when creating the customer in FlexPrice",
  ),
  filters: z.array(FilterCondition$zodSchema).optional(),
  invoice_ids: z.array(z.string()).optional().describe(
    "invoice_ids restricts results to invoices with the specified IDs\nUse this to retrieve specific invoices when you know their exact identifiers",
  ),
  invoice_status: z.array(InvoiceStatus$zodSchema).optional().describe(
    "invoice_status filters by the current state of invoices in their lifecycle\nMultiple statuses can be specified to include invoices in any of the listed states",
  ),
  invoice_type: InvoiceType$zodSchema.optional(),
  limit: z.int().optional(),
  offset: z.int().optional(),
  order: InvoiceFilterOrder$zodSchema.optional(),
  payment_status: z.array(PaymentStatus$zodSchema).optional().describe(
    "payment_status filters by the payment state of invoices\nMultiple statuses can be specified to include invoices with any of the listed payment states",
  ),
  period_end_gte: z.string().optional().describe(
    "period_end_gte filters invoices with period_end >= value",
  ),
  period_end_lte: z.string().optional().describe(
    "period_end_lte filters invoices with period_end <= value",
  ),
  period_start_gte: z.string().optional().describe(
    "period_start_gte filters invoices with period_start >= value",
  ),
  period_start_lte: z.string().optional().describe(
    "period_start_lte filters invoices with period_start <= value",
  ),
  skip_line_items: z.boolean().optional().describe(
    "SkipLineItems if true, will not include line items in the response",
  ),
  sort: z.array(SortCondition$zodSchema).optional(),
  start_time: z.iso.datetime({ offset: true }).optional(),
  status: Status$zodSchema.optional(),
  subscription_customer_id: z.array(z.string()).optional().describe(
    "subscription_customer_id filters invoices by the subscription owner's customer ID",
  ),
  subscription_id: z.string().optional().describe(
    "subscription_id filters invoices generated for a specific subscription\nOnly returns invoices that were created as part of the specified subscription's billing",
  ),
});
