/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  InvoiceLineItemPreview,
  InvoiceLineItemPreview$zodSchema,
} from "./invoicelineitempreview.js";

export type InvoicePreview = {
  currency?: string | undefined;
  due_date?: string | undefined;
  line_items?: Array<InvoiceLineItemPreview> | undefined;
  subtotal?: string | undefined;
  tax_amount?: string | undefined;
  total?: string | undefined;
};

export const InvoicePreview$zodSchema: z.ZodType<InvoicePreview> = z.object({
  currency: z.string().optional().describe(
    "currency is the currency for all amounts",
  ),
  due_date: z.iso.datetime({ offset: true }).optional().describe(
    "due_date is when the invoice would be due",
  ),
  line_items: z.array(InvoiceLineItemPreview$zodSchema).optional().describe(
    "line_items contains preview of line items",
  ),
  subtotal: z.string().optional().describe(
    "subtotal is the subtotal amount before taxes",
  ),
  tax_amount: z.string().optional().describe(
    "tax_amount is the total tax amount",
  ),
  total: z.string().optional().describe(
    "total is the total amount including taxes",
  ),
});
