/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceSourceType = {
  Checkout: "checkout",
} as const;
export type InvoiceSourceType = ClosedEnum<typeof InvoiceSourceType>;

export const InvoiceSourceType$zodSchema = z.enum([
  "checkout",
]);
