/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";

export type InvoiceModifyResponse = { invoice?: InvoiceResponse | undefined };

export const InvoiceModifyResponse$zodSchema: z.ZodType<InvoiceModifyResponse> =
  z.object({
    invoice: InvoiceResponse$zodSchema.optional(),
  });
