/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceCadence = {
  Arrear: "ARREAR",
  Advance: "ADVANCE",
} as const;
export type InvoiceCadence = ClosedEnum<typeof InvoiceCadence>;

export const InvoiceCadence$zodSchema = z.enum([
  "ARREAR",
  "ADVANCE",
]);
