/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvoiceCoupon = {
  coupon_association_id?: string | undefined;
  coupon_id: string;
};

export const InvoiceCoupon$zodSchema: z.ZodType<InvoiceCoupon> = z.object({
  coupon_association_id: z.string().optional(),
  coupon_id: z.string(),
});
