/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type InvoiceLineItemCoupon = {
  coupon_association_id?: string | undefined;
  coupon_id: string;
  line_item_id: string;
};

export const InvoiceLineItemCoupon$zodSchema: z.ZodType<InvoiceLineItemCoupon> =
  z.object({
    coupon_association_id: z.string().optional(),
    coupon_id: z.string(),
    line_item_id: z.string().describe("price_id used to match the line item"),
  });
