/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { CommitmentInfo, CommitmentInfo$zodSchema } from "./commitmentinfo.js";
import {
  SourceUsageItem,
  SourceUsageItem$zodSchema,
} from "./sourceusageitem.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  UsageBreakdownItem,
  UsageBreakdownItem$zodSchema,
} from "./usagebreakdownitem.js";

export type InvoiceLineItemResponse = {
  adjusted_entitlement_quantity?: string | undefined;
  amount?: string | undefined;
  commitment_info?: CommitmentInfo | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  display_name?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  invoice_id?: string | undefined;
  invoice_level_discount?: string | undefined;
  line_item_discount?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_display_name?: string | undefined;
  meter_id?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  plan_display_name?: string | undefined;
  prepaid_credits_applied?: string | undefined;
  price_id?: string | undefined;
  price_type?: string | undefined;
  price_unit?: string | undefined;
  price_unit_amount?: string | undefined;
  price_unit_id?: string | undefined;
  quantity?: string | undefined;
  status?: Status | undefined;
  subscription_id?: string | undefined;
  subscription_line_item_id?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  usage_analytics?: Array<SourceUsageItem> | undefined;
  usage_breakdown?: Array<UsageBreakdownItem> | undefined;
};

export const InvoiceLineItemResponse$zodSchema: z.ZodType<
  InvoiceLineItemResponse
> = z.object({
  adjusted_entitlement_quantity: z.string().optional().describe(
    "adjusted_entitlement_quantity is the entitlement-covered portion deducted from raw usage.\nNil when no entitlement was applied. Raw usage = Quantity + AdjustedEntitlementQuantity.",
  ),
  amount: z.string().optional(),
  commitment_info: CommitmentInfo$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  display_name: z.string().optional(),
  entity_id: z.string().optional(),
  entity_type: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  invoice_id: z.string().optional(),
  invoice_level_discount: z.string().optional().describe(
    "invoice_level_discount is the discount amount in invoice currency applied to all line items on the invoice.",
  ),
  line_item_discount: z.string().optional().describe(
    "line_item_discount is the discount amount in invoice currency applied directly to this line item.",
  ),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_display_name: z.string().optional(),
  meter_id: z.string().optional(),
  period_end: z.iso.datetime({ offset: true }).optional(),
  period_start: z.iso.datetime({ offset: true }).optional(),
  plan_display_name: z.string().optional(),
  prepaid_credits_applied: z.string().optional().describe(
    "prepaid_credits_applied is the amount in invoice currency reduced from this line item due to prepaid credits application.",
  ),
  price_id: z.string().optional(),
  price_type: z.string().optional(),
  price_unit: z.string().optional(),
  price_unit_amount: z.string().optional(),
  price_unit_id: z.string().optional(),
  quantity: z.string().optional(),
  status: Status$zodSchema.optional(),
  subscription_id: z.string().optional(),
  subscription_line_item_id: z.string().optional().describe(
    "sub_line_item_id links this invoice line item to the subscription_line_item that generated it.",
  ),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
  usage_analytics: z.array(SourceUsageItem$zodSchema).optional().describe(
    "usage_analytics contains usage analytics for this line item (legacy - grouped by source)",
  ),
  usage_breakdown: z.array(UsageBreakdownItem$zodSchema).optional().describe(
    "usage_breakdown contains flexible usage breakdown for this line item (supports any grouping)",
  ),
});
