/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceModifyType = {
  LineItem: "line_item",
} as const;
export type InvoiceModifyType = ClosedEnum<typeof InvoiceModifyType>;

export const InvoiceModifyType$zodSchema = z.enum([
  "line_item",
]);
