/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import { CommitmentType, CommitmentType$zodSchema } from "./commitmenttype.js";

export type LineItemCommitmentConfig = {
  commitment_amount?: number | undefined;
  commitment_duration?: BillingPeriod | undefined;
  commitment_quantity?: number | undefined;
  commitment_type?: CommitmentType | undefined;
  enable_true_up?: boolean | undefined;
  is_window_commitment?: boolean | undefined;
  overage_factor?: number | undefined;
};

export const LineItemCommitmentConfig$zodSchema: z.ZodType<
  LineItemCommitmentConfig
> = z.object({
  commitment_amount: z.number().optional().describe(
    "CommitmentAmount is the minimum amount committed for this line item",
  ),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  commitment_quantity: z.number().optional().describe(
    "CommitmentQuantity is the minimum quantity committed for this line item",
  ),
  commitment_type: CommitmentType$zodSchema.optional(),
  enable_true_up: z.boolean().optional().describe(
    "EnableTrueUp determines if true-up fee should be applied when usage is below commitment",
  ),
  is_window_commitment: z.boolean().optional().describe(
    "IsWindowCommitment determines if commitment is applied per window (e.g., per day) rather than per billing period",
  ),
  overage_factor: z.number().optional().describe(
    "OverageFactor is a multiplier applied to usage beyond the commitment",
  ),
});
