/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const LineItemGrouping = {
  PerChargePeriod: "per_charge_period",
  PerBillingPeriod: "per_billing_period",
} as const;
export type LineItemGrouping = ClosedEnum<typeof LineItemGrouping>;

export const LineItemGrouping$zodSchema = z.enum([
  "per_charge_period",
  "per_billing_period",
]);
