/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SavedPaymentMethodsResponse,
  SavedPaymentMethodsResponse$zodSchema,
} from "./savedpaymentmethodsresponse.js";

export type ListCustomerPaymentMethodsRequest = {
  id: string;
  providers?: Array<string> | undefined;
};

export const ListCustomerPaymentMethodsRequest$zodSchema: z.ZodType<
  ListCustomerPaymentMethodsRequest
> = z.object({
  id: z.string().describe("Customer ID"),
  providers: z.array(z.string()).describe("Limit to these payment gateways")
    .optional(),
});

export type ListCustomerPaymentMethodsResponse =
  | SavedPaymentMethodsResponse
  | ErrorResponse;

export const ListCustomerPaymentMethodsResponse$zodSchema: z.ZodType<
  ListCustomerPaymentMethodsResponse
> = z.union([
  SavedPaymentMethodsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
