/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";
import {
  SubscriptionLineItemResponse,
  SubscriptionLineItemResponse$zodSchema,
} from "./subscriptionlineitemresponse.js";

export type ListSubscriptionLineItemsResponse = {
  items?: Array<SubscriptionLineItemResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListSubscriptionLineItemsResponse$zodSchema: z.ZodType<
  ListSubscriptionLineItemsResponse
> = z.object({
  items: z.array(SubscriptionLineItemResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
