/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type ListSubscriptionsResponse = {
  items?: Array<SubscriptionResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListSubscriptionsResponse$zodSchema: z.ZodType<
  ListSubscriptionsResponse
> = z.object({
  items: z.array(SubscriptionResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
