/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  GetEventsResponse,
  GetEventsResponse$zodSchema,
} from "./geteventsresponse.js";

export type ListRawEventsResponse = GetEventsResponse | ErrorResponse;

export const ListRawEventsResponse$zodSchema: z.ZodType<ListRawEventsResponse> =
  z.union([
    GetEventsResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
