/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddonAssociationResponse,
  AddonAssociationResponse$zodSchema,
} from "./addonassociationresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type ListAddonAssociationsResponse = {
  items?: Array<AddonAssociationResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListAddonAssociationsResponse$zodSchema: z.ZodType<
  ListAddonAssociationsResponse
> = z.object({
  items: z.array(AddonAssociationResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
