/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListSubscriptionSchedulesRequest = { subscription_id: string };

export const ListSubscriptionSchedulesRequest$zodSchema: z.ZodType<
  ListSubscriptionSchedulesRequest
> = z.object({
  subscription_id: z.string().describe("Subscription ID"),
});
