/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";
import { PriceResponse, PriceResponse$zodSchema } from "./priceresponse.js";

export type ListPricesResponse = {
  items?: Array<PriceResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListPricesResponse$zodSchema: z.ZodType<ListPricesResponse> = z
  .object({
    items: z.array(PriceResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
