/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerResponse,
  CustomerResponse$zodSchema,
} from "./customerresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

/**
 * Response object for listing customers with pagination
 */
export type ListCustomersResponse = {
  items?: Array<CustomerResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListCustomersResponse$zodSchema: z.ZodType<ListCustomersResponse> =
  z.object({
    items: z.array(CustomerResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  }).describe("Response object for listing customers with pagination");
