/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreditGrantApplicationResponse,
  CreditGrantApplicationResponse$zodSchema,
} from "./creditgrantapplicationresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type ListCreditGrantApplicationsResponse = {
  items?: Array<CreditGrantApplicationResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListCreditGrantApplicationsResponse$zodSchema: z.ZodType<
  ListCreditGrantApplicationsResponse
> = z.object({
  items: z.array(CreditGrantApplicationResponse$zodSchema).optional(),
  pagination: PaginationResponse$zodSchema.optional(),
});
