/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ListAllSubscriptionSchedulesRequest = {
  pending_only?: boolean | undefined;
  subscription_id?: string | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
};

export const ListAllSubscriptionSchedulesRequest$zodSchema: z.ZodType<
  ListAllSubscriptionSchedulesRequest
> = z.object({
  limit: z.int().describe("Limit results").optional(),
  offset: z.int().describe("Offset for pagination").optional(),
  pending_only: z.boolean().describe("Filter to pending schedules only")
    .optional(),
  subscription_id: z.string().describe("Filter by subscription ID").optional(),
});
