/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";
import { PlanResponse, PlanResponse$zodSchema } from "./planresponse.js";

export type ListPlansResponse = {
  items?: Array<PlanResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListPlansResponse$zodSchema: z.ZodType<ListPlansResponse> = z
  .object({
    items: z.array(PlanResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
