/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import {
  PaginationResponse,
  PaginationResponse$zodSchema,
} from "./paginationresponse.js";

export type ListInvoicesResponse = {
  items?: Array<InvoiceResponse> | undefined;
  pagination?: PaginationResponse | undefined;
};

export const ListInvoicesResponse$zodSchema: z.ZodType<ListInvoicesResponse> = z
  .object({
    items: z.array(InvoiceResponse$zodSchema).optional(),
    pagination: PaginationResponse$zodSchema.optional(),
  });
