/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PricePrice, PricePrice$zodSchema } from "./priceprice.js";

export type MatchedPrice = {
  meter_id?: string | undefined;
  price?: PricePrice | undefined;
  price_id?: string | undefined;
  status?: string | undefined;
};

export const MatchedPrice$zodSchema: z.ZodType<MatchedPrice> = z.object({
  meter_id: z.string().optional(),
  price: PricePrice$zodSchema.optional(),
  price_id: z.string().optional(),
  status: z.string().optional(),
});
