/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MeterMeter, MeterMeter$zodSchema } from "./metermeter.js";

export type MatchedMeter = {
  event_name?: string | undefined;
  meter?: MeterMeter | undefined;
  meter_id?: string | undefined;
};

export const MatchedMeter$zodSchema: z.ZodType<MatchedMeter> = z.object({
  event_name: z.string().optional(),
  meter: MeterMeter$zodSchema.optional(),
  meter_id: z.string().optional(),
});
