/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Meter, Meter$zodSchema } from "./meter.js";

export type MatchedMeter = {
  event_name?: string | undefined;
  meter?: Meter | undefined;
  meter_id?: string | undefined;
};

export const MatchedMeter$zodSchema: z.ZodType<MatchedMeter> = z.object({
  event_name: z.string().optional(),
  meter: Meter$zodSchema.optional(),
  meter_id: z.string().optional(),
});
