/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MeterUsageAttribution = {
  external_customer_id?: string | undefined;
  meter_id?: string | undefined;
  qty_total?: string | undefined;
};

export const MeterUsageAttribution$zodSchema: z.ZodType<MeterUsageAttribution> =
  z.object({
    external_customer_id: z.string().optional(),
    meter_id: z.string().optional(),
    qty_total: z.string().optional(),
  });
