/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  MeterAggregation,
  MeterAggregation$zodSchema,
} from "./meteraggregation.js";
import { MeterFilter, MeterFilter$zodSchema } from "./meterfilter.js";
import { ResetUsage, ResetUsage$zodSchema } from "./resetusage.js";

export type MeterResponse = {
  aggregation?: MeterAggregation | undefined;
  created_at?: string | undefined;
  event_name?: string | undefined;
  filters?: Array<MeterFilter> | undefined;
  id?: string | undefined;
  name?: string | undefined;
  reset_usage?: ResetUsage | undefined;
  status?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
};

export const MeterResponse$zodSchema: z.ZodType<MeterResponse> = z.object({
  aggregation: MeterAggregation$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  event_name: z.string().optional(),
  filters: z.array(MeterFilter$zodSchema).optional(),
  id: z.string().optional(),
  name: z.string().optional(),
  reset_usage: ResetUsage$zodSchema.optional(),
  status: z.string().optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
});
