/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type MeterFilter = {
  key?: string | undefined;
  values?: Array<string> | undefined;
};

export const MeterFilter$zodSchema: z.ZodType<MeterFilter> = z.object({
  key: z.string().optional().describe(
    "Key is the key for the filter from $event.properties\nCurrently we support only first level keys in the properties and not nested keys",
  ),
  values: z.array(z.string()).optional().describe(
    "Values are the possible values for the filter to be considered for the meter\nFor ex \"model_name\" could have values \"o1-mini\", \"gpt-4o\" etc",
  ),
});
