/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$zodSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { MatchedMeter, MatchedMeter$zodSchema } from "./matchedmeter.js";

export type MeterMatchingResult = {
  error?: ErrorResponse | undefined;
  matched_meters?: Array<MatchedMeter> | undefined;
  status?: DebugTrackerStatus | undefined;
};

export const MeterMatchingResult$zodSchema: z.ZodType<MeterMatchingResult> = z
  .object({
    error: ErrorResponse$zodSchema.optional(),
    matched_meters: z.array(MatchedMeter$zodSchema).optional(),
    status: DebugTrackerStatus$zodSchema.optional(),
  });
