/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ModifySubscriptionLineItem = {
  effective_date?: string | undefined;
  line_item_id?: string | undefined;
  quantity?: string | undefined;
};

export const ModifySubscriptionLineItem$zodSchema: z.ZodType<
  ModifySubscriptionLineItem
> = z.object({
  effective_date: z.iso.datetime({ offset: true }).optional(),
  line_item_id: z.string().optional(),
  quantity: z.string().optional(),
});
