/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ModifySubscriptionLineItem,
  ModifySubscriptionLineItem$zodSchema,
} from "./modifysubscriptionlineitem.js";

export type ModifySubscriptionParams = {
  line_item_modifications?: Array<ModifySubscriptionLineItem> | undefined;
  subscription_id?: string | undefined;
};

export const ModifySubscriptionParams$zodSchema: z.ZodType<
  ModifySubscriptionParams
> = z.object({
  line_item_modifications: z.array(ModifySubscriptionLineItem$zodSchema)
    .optional(),
  subscription_id: z.string().optional(),
});
