/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OnExistingEntityPolicy = {
  Reject: "reject",
  Supersede: "supersede",
} as const;
export type OnExistingEntityPolicy = ClosedEnum<typeof OnExistingEntityPolicy>;

export const OnExistingEntityPolicy$zodSchema = z.enum([
  "reject",
  "supersede",
]);
