/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const OnPendingSchedulePolicy = {
  Reject: "reject",
  Supersede: "supersede",
} as const;
export type OnPendingSchedulePolicy = ClosedEnum<
  typeof OnPendingSchedulePolicy
>;

export const OnPendingSchedulePolicy$zodSchema = z.enum([
  "reject",
  "supersede",
]);
