/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingModel, BillingModel$zodSchema } from "./billingmodel.js";
import { BillingTier, BillingTier$zodSchema } from "./billingtier.js";
import {
  CreatePriceTier,
  CreatePriceTier$zodSchema,
} from "./createpricetier.js";
import {
  PriceTransformQuantity,
  PriceTransformQuantity$zodSchema,
} from "./pricetransformquantity.js";

export type OverrideLineItemRequest = {
  amount?: string | undefined;
  billing_model?: BillingModel | undefined;
  price_id: string;
  price_unit_amount?: string | undefined;
  price_unit_tiers?: Array<CreatePriceTier> | undefined;
  quantity?: string | undefined;
  tier_mode?: BillingTier | undefined;
  tiers?: Array<CreatePriceTier> | undefined;
  transform_quantity?: PriceTransformQuantity | undefined;
};

export const OverrideLineItemRequest$zodSchema: z.ZodType<
  OverrideLineItemRequest
> = z.object({
  amount: z.string().optional().describe(
    "Amount is the new price amount that overrides the original price (optional)",
  ),
  billing_model: BillingModel$zodSchema.optional(),
  price_id: z.string().describe(
    "PriceID references the plan price to override",
  ),
  price_unit_amount: z.string().optional().describe(
    "PriceUnitAmount is the amount of the price unit (for CUSTOM type, FLAT_FEE/PACKAGE billing models)",
  ),
  price_unit_tiers: z.array(CreatePriceTier$zodSchema).optional().describe(
    "PriceUnitTiers are the tiers for the price unit (for CUSTOM type, TIERED billing model)",
  ),
  quantity: z.string().optional().describe(
    "Quantity for this line item (optional)",
  ),
  tier_mode: BillingTier$zodSchema.optional(),
  tiers: z.array(CreatePriceTier$zodSchema).optional().describe(
    "Tiers determines the pricing tiers for this line item",
  ),
  transform_quantity: PriceTransformQuantity$zodSchema.optional(),
});
