/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type OverrideEntitlementRequest = {
  config_value?: { [k: string]: any } | undefined;
  entitlement_id: string;
  is_enabled?: boolean | undefined;
  static_value?: string | undefined;
  usage_limit?: number | undefined;
};

export const OverrideEntitlementRequest$zodSchema: z.ZodType<
  OverrideEntitlementRequest
> = z.object({
  config_value: z.record(z.string(), z.any()).optional().describe(
    "ConfigValue is the config value for config features",
  ),
  entitlement_id: z.string().describe(
    "EntitlementID references the plan/addon entitlement to override",
  ),
  is_enabled: z.boolean().optional().describe(
    "IsEnabled determines if the entitlement is enabled or disabled",
  ),
  static_value: z.string().optional().describe(
    "StaticValue is the static value for static features",
  ),
  usage_limit: z.int().optional().describe(
    "UsageLimit is the new usage limit (only these 3 fields can be overridden)\nFor metered features, nil means unlimited usage",
  ),
});
