/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PaginationResponse = {
  limit?: number | undefined;
  offset?: number | undefined;
  total?: number | undefined;
};

export const PaginationResponse$zodSchema: z.ZodType<PaginationResponse> = z
  .object({
    limit: z.int().optional(),
    offset: z.int().optional(),
    total: z.int().optional(),
  });
