/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PaymentMethodType = {
  Card: "CARD",
  Ach: "ACH",
  Offline: "OFFLINE",
  Credits: "CREDITS",
  PaymentLink: "PAYMENT_LINK",
  Upi: "UPI",
} as const;
export type PaymentMethodType = ClosedEnum<typeof PaymentMethodType>;

export const PaymentMethodType$zodSchema = z.enum([
  "CARD",
  "ACH",
  "OFFLINE",
  "CREDITS",
  "PAYMENT_LINK",
  "UPI",
]);
