/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PaymentMethodStatus = {
  Active: "ACTIVE",
  Inactive: "INACTIVE",
  Expired: "EXPIRED",
} as const;
export type PaymentMethodStatus = ClosedEnum<typeof PaymentMethodStatus>;

export const PaymentMethodStatus$zodSchema = z.enum([
  "ACTIVE",
  "INACTIVE",
  "EXPIRED",
]);
