/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PaymentBehavior = {
  AllowIncomplete: "allow_incomplete",
  DefaultIncomplete: "default_incomplete",
  ErrorIfIncomplete: "error_if_incomplete",
  DefaultActive: "default_active",
} as const;
export type PaymentBehavior = ClosedEnum<typeof PaymentBehavior>;

export const PaymentBehavior$zodSchema = z.enum([
  "allow_incomplete",
  "default_incomplete",
  "error_if_incomplete",
  "default_active",
]);
