/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaymentActionType,
  PaymentActionType$zodSchema,
} from "./paymentactiontype.js";

export type PaymentAction = {
  type?: PaymentActionType | undefined;
  url?: string | undefined;
};

export const PaymentAction$zodSchema: z.ZodType<PaymentAction> = z.object({
  type: PaymentActionType$zodSchema.optional(),
  url: z.string().optional(),
});
