/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PaymentActionType = {
  CheckoutUrl: "checkout_url",
  PaymentLink: "payment_link",
} as const;
export type PaymentActionType = ClosedEnum<typeof PaymentActionType>;

export const PaymentActionType$zodSchema = z.enum([
  "checkout_url",
  "payment_link",
]);
