/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PaymentTerms = {
  FifteenNET: "15 NET",
  ThirtyNET: "30 NET",
  FortyFiveNET: "45 NET",
  SixtyNET: "60 NET",
  SeventyFiveNET: "75 NET",
  NinetyNET: "90 NET",
} as const;
export type PaymentTerms = ClosedEnum<typeof PaymentTerms>;

export const PaymentTerms$zodSchema = z.enum([
  "15 NET",
  "30 NET",
  "45 NET",
  "60 NET",
  "75 NET",
  "90 NET",
]);
