/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreditGrantResponse,
  CreditGrantResponse$zodSchema,
} from "./creditgrantresponse.js";
import {
  EntitlementResponse,
  EntitlementResponse$zodSchema,
} from "./entitlementresponse.js";
import { PriceResponse, PriceResponse$zodSchema } from "./priceresponse.js";
import { Status, Status$zodSchema } from "./status.js";

export type PlanResponse = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_grants?: Array<CreditGrantResponse> | undefined;
  description?: string | undefined;
  display_order?: number | undefined;
  entitlements?: Array<EntitlementResponse> | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  prices?: Array<PriceResponse> | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const PlanResponse$zodSchema: z.ZodType<PlanResponse> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  credit_grants: z.array(CreditGrantResponse$zodSchema).optional(),
  description: z.string().optional(),
  display_order: z.int().optional(),
  entitlements: z.array(z.lazy(() => EntitlementResponse$zodSchema)).optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  prices: z.array(z.lazy(() => PriceResponse$zodSchema)).optional().describe(
    "TODO: Add inline addons",
  ),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
