/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";

export type Plan = {
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  display_order?: number | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const Plan$zodSchema: z.ZodType<Plan> = z.object({
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  display_order: z.int().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
