/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PlanPriceSyncStatusResponse = {
  current_sequence?: number | undefined;
  synced?: boolean | undefined;
  unsynced_subscription_count?: number | undefined;
};

export const PlanPriceSyncStatusResponse$zodSchema: z.ZodType<
  PlanPriceSyncStatusResponse
> = z.object({
  current_sequence: z.int().optional(),
  synced: z.boolean().optional(),
  unsynced_subscription_count: z.int().optional(),
});
