/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type PlanChangeScheduleResult = {
  change_type?: string | undefined;
  effective_date?: string | undefined;
  from_plan_id?: string | undefined;
  previous_subscription_id?: string | undefined;
  subscription_id?: string | undefined;
  to_plan_id?: string | undefined;
};

export const PlanChangeScheduleResult$zodSchema: z.ZodType<
  PlanChangeScheduleResult
> = z.object({
  change_type: z.string().optional(),
  effective_date: z.iso.datetime({ offset: true }).optional(),
  from_plan_id: z.string().optional(),
  previous_subscription_id: z.string().optional().describe(
    "previous_subscription_id is set when the change replaced the subscription with a new one",
  ),
  subscription_id: z.string().optional(),
  to_plan_id: z.string().optional(),
});
