/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionChangePreviewResponse,
  SubscriptionChangePreviewResponse$zodSchema,
} from "./subscriptionchangepreviewresponse.js";
import {
  SubscriptionChangeRequest,
  SubscriptionChangeRequest$zodSchema,
} from "./subscriptionchangerequest.js";

export type PreviewSubscriptionChangeRequest = {
  id: string;
  body: SubscriptionChangeRequest;
};

export const PreviewSubscriptionChangeRequest$zodSchema: z.ZodType<
  PreviewSubscriptionChangeRequest
> = z.object({
  body: SubscriptionChangeRequest$zodSchema.describe(
    "Subscription change preview request",
  ),
  id: z.string().describe("Subscription ID"),
});

export type PreviewSubscriptionChangeResponse =
  | SubscriptionChangePreviewResponse
  | ErrorResponse;

export const PreviewSubscriptionChangeResponse$zodSchema: z.ZodType<
  PreviewSubscriptionChangeResponse
> = z.union([
  SubscriptionChangePreviewResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
