/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PriceType = {
  Usage: "USAGE",
  Fixed: "FIXED",
} as const;
export type PriceType = ClosedEnum<typeof PriceType>;

export const PriceType$zodSchema = z.enum([
  "USAGE",
  "FIXED",
]);
