/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PriceEntityType = {
  Plan: "PLAN",
  Subscription: "SUBSCRIPTION",
  Addon: "ADDON",
  Price: "PRICE",
  Costsheet: "COSTSHEET",
} as const;
export type PriceEntityType = ClosedEnum<typeof PriceEntityType>;

export const PriceEntityType$zodSchema = z.enum([
  "PLAN",
  "SUBSCRIPTION",
  "ADDON",
  "PRICE",
  "COSTSHEET",
]);
