/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AddonResponse, AddonResponse$zodSchema } from "./addonresponse.js";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingModel, BillingModel$zodSchema } from "./billingmodel.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import { BillingTier, BillingTier$zodSchema } from "./billingtier.js";
import { GroupResponse, GroupResponse$zodSchema } from "./groupresponse.js";
import { InvoiceCadence, InvoiceCadence$zodSchema } from "./invoicecadence.js";
import { MeterResponse, MeterResponse$zodSchema } from "./meterresponse.js";
import { PlanResponse, PlanResponse$zodSchema } from "./planresponse.js";
import {
  PriceEntityType,
  PriceEntityType$zodSchema,
} from "./priceentitytype.js";
import {
  PriceJSONBTransformQuantity,
  PriceJSONBTransformQuantity$zodSchema,
} from "./pricejsonbtransformquantity.js";
import { PricePriceTier, PricePriceTier$zodSchema } from "./pricepricetier.js";
import { PriceType, PriceType$zodSchema } from "./pricetype.js";
import {
  PriceUnitResponse,
  PriceUnitResponse$zodSchema,
} from "./priceunitresponse.js";
import { PriceUnitType, PriceUnitType$zodSchema } from "./priceunittype.js";
import { Status, Status$zodSchema } from "./status.js";

export type PriceResponse = {
  addon?: AddonResponse | undefined;
  amount?: string | undefined;
  billing_cadence?: BillingCadence | undefined;
  billing_model?: BillingModel | undefined;
  billing_period?: BillingPeriod | undefined;
  billing_period_count?: number | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  currency?: string | undefined;
  description?: string | undefined;
  display_amount?: string | undefined;
  display_name?: string | undefined;
  display_price_unit_amount?: string | undefined;
  end_date?: string | undefined;
  entity_id?: string | undefined;
  entity_type?: PriceEntityType | undefined;
  environment_id?: string | undefined;
  group?: GroupResponse | undefined;
  group_id?: string | undefined;
  id?: string | undefined;
  invoice_cadence?: InvoiceCadence | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter?: MeterResponse | undefined;
  meter_id?: string | undefined;
  min_quantity?: string | null | undefined;
  parent_price_id?: string | undefined;
  plan?: PlanResponse | undefined;
  price_unit?: string | undefined;
  price_unit_amount?: string | undefined;
  price_unit_id?: string | undefined;
  price_unit_tiers?: Array<PricePriceTier> | undefined;
  price_unit_type?: PriceUnitType | undefined;
  pricing_unit?: PriceUnitResponse | undefined;
  sequence?: number | undefined;
  start_date?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  tier_mode?: BillingTier | undefined;
  tiers?: Array<PricePriceTier> | undefined;
  transform_quantity?: PriceJSONBTransformQuantity | undefined;
  trial_period_days?: number | undefined;
  type?: PriceType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const PriceResponse$zodSchema: z.ZodType<PriceResponse> = z.object({
  addon: z.lazy(() => AddonResponse$zodSchema).optional(),
  amount: z.string().optional().describe(
    "Amount stored in main currency units (e.g., dollars, not cents)\nFor USD: 12.50 means $12.50",
  ),
  billing_cadence: BillingCadence$zodSchema.optional(),
  billing_model: BillingModel$zodSchema.optional(),
  billing_period: BillingPeriod$zodSchema.optional(),
  billing_period_count: z.int().optional().describe(
    "BillingPeriodCount is the count of the billing period ex 1, 3, 6, 12",
  ),
  conversion_rate: z.string().optional().describe(
    "ConversionRate is the conversion rate of the price unit to the fiat currency",
  ),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  currency: z.string().optional().describe(
    "Currency 3 digit ISO currency code in lowercase ex usd, eur, gbp",
  ),
  description: z.string().optional().describe("Description of the price"),
  display_amount: z.string().optional().describe(
    "DisplayAmount is the formatted amount with currency symbol\nFor USD: $12.50",
  ),
  display_name: z.string().optional().describe(
    "DisplayName is the name of the price",
  ),
  display_price_unit_amount: z.string().optional().describe(
    "DisplayPriceUnitAmount is the formatted amount of the price unit",
  ),
  end_date: z.iso.datetime({ offset: true }).optional().describe(
    "EndDate is the end date of the price",
  ),
  entity_id: z.string().optional().describe(
    "EntityID holds the value of the \"entity_id\" field.",
  ),
  entity_type: PriceEntityType$zodSchema.optional(),
  environment_id: z.string().optional().describe(
    "EnvironmentID is the environment identifier for the price",
  ),
  group: GroupResponse$zodSchema.optional(),
  group_id: z.string().optional().describe(
    "GroupID references the group this price belongs to",
  ),
  id: z.string().optional().describe("ID uuid identifier for the price"),
  invoice_cadence: InvoiceCadence$zodSchema.optional(),
  lookup_key: z.string().optional().describe(
    "LookupKey used for looking up the price in the database",
  ),
  metadata: z.record(z.string(), z.string()).optional(),
  meter: MeterResponse$zodSchema.optional(),
  meter_id: z.string().optional().describe(
    "MeterID is the id of the meter for usage based pricing",
  ),
  min_quantity: z.string().nullable().optional().describe(
    "MinQuantity is the minimum quantity of the price",
  ),
  parent_price_id: z.string().optional().describe(
    "ParentPriceID references the root price (always set for price lineage tracking)",
  ),
  plan: z.lazy(() => PlanResponse$zodSchema).optional(),
  price_unit: z.string().optional().describe(
    "PriceUnit is the code of the price unit (e.g., 'btc', 'eth')",
  ),
  price_unit_amount: z.string().optional().describe(
    "PriceUnitAmount is the amount of the price unit",
  ),
  price_unit_id: z.string().optional().describe(
    "PriceUnitID is the id of the price unit (for CUSTOM type)",
  ),
  price_unit_tiers: z.array(PricePriceTier$zodSchema).optional().describe(
    "PriceUnitTiers are the tiers for the price unit when BillingModel is TIERED",
  ),
  price_unit_type: PriceUnitType$zodSchema.optional(),
  pricing_unit: PriceUnitResponse$zodSchema.optional(),
  sequence: z.int().optional().describe(
    "Sequence is the monotonic stamp bumped on every state change that\nsubscription line items need to react to. Read by the plan-price sync;\nset by the database (DEFAULT nextval) on create and by the price\nrepository on termination / compatibility-affecting edits.",
  ),
  start_date: z.iso.datetime({ offset: true }).optional().describe(
    "StartDate is the start date of the price",
  ),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  tier_mode: BillingTier$zodSchema.optional(),
  tiers: z.array(PricePriceTier$zodSchema).optional(),
  transform_quantity: PriceJSONBTransformQuantity$zodSchema.optional(),
  trial_period_days: z.int().optional().describe(
    "TrialPeriodDays is the number of days for the trial period\nNote: This is only applicable for recurring prices (BILLING_CADENCE_RECURRING)",
  ),
  type: PriceType$zodSchema.optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
