/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { RoundType, RoundType$zodSchema } from "./roundtype.js";

export type PriceJSONBTransformQuantity = {
  divide_by?: number | undefined;
  round?: RoundType | undefined;
};

export const PriceJSONBTransformQuantity$zodSchema: z.ZodType<
  PriceJSONBTransformQuantity
> = z.object({
  divide_by: z.int().optional().describe("Divide quantity by this number"),
  round: RoundType$zodSchema.optional(),
});
