/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";

export type PriceUnitResponse = {
  base_currency?: string | undefined;
  code?: string | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  symbol?: string | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const PriceUnitResponse$zodSchema: z.ZodType<PriceUnitResponse> = z
  .object({
    base_currency: z.string().optional(),
    code: z.string().optional(),
    conversion_rate: z.string().optional(),
    created_at: z.iso.datetime({ offset: true }).optional(),
    created_by: z.string().optional(),
    environment_id: z.string().optional(),
    id: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
    status: Status$zodSchema.optional(),
    symbol: z.string().optional(),
    tenant_id: z.string().optional(),
    updated_at: z.iso.datetime({ offset: true }).optional(),
    updated_by: z.string().optional(),
  });
