/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreatePriceTier,
  CreatePriceTier$zodSchema,
} from "./createpricetier.js";

export type PriceUnitConfig = {
  amount?: string | undefined;
  price_unit: string;
  price_unit_tiers?: Array<CreatePriceTier> | undefined;
};

export const PriceUnitConfig$zodSchema: z.ZodType<PriceUnitConfig> = z.object({
  amount: z.string().optional(),
  price_unit: z.string(),
  price_unit_tiers: z.array(CreatePriceTier$zodSchema).optional(),
});
