/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const PriceUnitType = {
  Fiat: "FIAT",
  Custom: "CUSTOM",
} as const;
export type PriceUnitType = ClosedEnum<typeof PriceUnitType>;

export const PriceUnitType$zodSchema = z.enum([
  "FIAT",
  "CUSTOM",
]);
