/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ProrationBehavior = {
  CreateProrations: "create_prorations",
  None: "none",
} as const;
export type ProrationBehavior = ClosedEnum<typeof ProrationBehavior>;

export const ProrationBehavior$zodSchema = z.enum([
  "create_prorations",
  "none",
]);
