/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ProrationDetail = {
  charge_amount?: string | undefined;
  credit_amount?: string | undefined;
  description?: string | undefined;
  line_item_id?: string | undefined;
  original_amount?: string | undefined;
  plan_name?: string | undefined;
  price_id?: string | undefined;
  proration_days?: number | undefined;
};

export const ProrationDetail$zodSchema: z.ZodType<ProrationDetail> = z.object({
  charge_amount: z.string().optional(),
  credit_amount: z.string().optional(),
  description: z.string().optional(),
  line_item_id: z.string().optional(),
  original_amount: z.string().optional(),
  plan_name: z.string().optional(),
  price_id: z.string().optional(),
  proration_days: z.int().optional(),
});
