/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ProrationDetails = {
  charge_amount?: string | undefined;
  charge_description?: string | undefined;
  credit_amount?: string | undefined;
  credit_description?: string | undefined;
  currency?: string | undefined;
  current_period_end?: string | undefined;
  current_period_start?: string | undefined;
  days_remaining?: number | undefined;
  days_used?: number | undefined;
  net_amount?: string | undefined;
  proration_date?: string | undefined;
};

export const ProrationDetails$zodSchema: z.ZodType<ProrationDetails> = z.object(
  {
    charge_amount: z.string().optional().describe(
      "charge_amount is the charge amount for the new subscription",
    ),
    charge_description: z.string().optional().describe(
      "charge_description describes what the charge is for",
    ),
    credit_amount: z.string().optional().describe(
      "credit_amount is the credit amount from the old subscription",
    ),
    credit_description: z.string().optional().describe(
      "credit_description describes what the credit is for",
    ),
    currency: z.string().optional().describe(
      "currency is the currency for all amounts",
    ),
    current_period_end: z.iso.datetime({ offset: true }).optional().describe(
      "current_period_end is the end of the current billing period",
    ),
    current_period_start: z.iso.datetime({ offset: true }).optional().describe(
      "current_period_start is the start of the current billing period",
    ),
    days_remaining: z.int().optional().describe(
      "days_remaining is the number of days remaining in the current period",
    ),
    days_used: z.int().optional().describe(
      "days_used is the number of days used in the current period",
    ),
    net_amount: z.string().optional().describe(
      "net_amount is the net amount (charge - credit)",
    ),
    proration_date: z.iso.datetime({ offset: true }).optional().describe(
      "proration_date is the date used for proration calculations",
    ),
  },
);
