/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ProviderError = { message?: string | undefined };

export const ProviderError$zodSchema: z.ZodType<ProviderError> = z.object({
  message: z.string().optional(),
});
