/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  PaymentGatewayType,
  PaymentGatewayType$zodSchema,
} from "./paymentgatewaytype.js";
import { ProviderError, ProviderError$zodSchema } from "./providererror.js";
import {
  SavedPaymentMethod,
  SavedPaymentMethod$zodSchema,
} from "./savedpaymentmethod.js";

export type ProviderSavedPaymentMethods = {
  error?: ProviderError | undefined;
  items?: Array<SavedPaymentMethod> | undefined;
  provider?: PaymentGatewayType | undefined;
};

export const ProviderSavedPaymentMethods$zodSchema: z.ZodType<
  ProviderSavedPaymentMethods
> = z.object({
  error: ProviderError$zodSchema.optional(),
  items: z.array(SavedPaymentMethod$zodSchema).optional(),
  provider: PaymentGatewayType$zodSchema.optional(),
});
