/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListCustomersResponse,
  ListCustomersResponse$zodSchema,
} from "./listcustomersresponse.js";

export type QueryCustomerResponse = ListCustomersResponse | ErrorResponse;

export const QueryCustomerResponse$zodSchema: z.ZodType<QueryCustomerResponse> =
  z.union([
    ListCustomersResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
