/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListSubscriptionLineItemsResponse,
  ListSubscriptionLineItemsResponse$zodSchema,
} from "./listsubscriptionlineitemsresponse.js";

export type QuerySubscriptionLineItemsResponse =
  | ListSubscriptionLineItemsResponse
  | ErrorResponse;

export const QuerySubscriptionLineItemsResponse$zodSchema: z.ZodType<
  QuerySubscriptionLineItemsResponse
> = z.union([
  ListSubscriptionLineItemsResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
