/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListInvoicesResponse,
  ListInvoicesResponse$zodSchema,
} from "./listinvoicesresponse.js";

export type QueryInvoiceResponse = ListInvoicesResponse | ErrorResponse;

export const QueryInvoiceResponse$zodSchema: z.ZodType<QueryInvoiceResponse> = z
  .union([
    ListInvoicesResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
