/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ListPlansResponse,
  ListPlansResponse$zodSchema,
} from "./listplansresponse.js";

export type QueryPlanResponse = ListPlansResponse | ErrorResponse;

export const QueryPlanResponse$zodSchema: z.ZodType<QueryPlanResponse> = z
  .union([
    ListPlansResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
