/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  ModelsTemporalWorkflowResult,
  ModelsTemporalWorkflowResult$zodSchema,
} from "./modelstemporalworkflowresult.js";

export type RecalculateInvoiceRequest = { id: string };

export const RecalculateInvoiceRequest$zodSchema: z.ZodType<
  RecalculateInvoiceRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type RecalculateInvoiceResponse =
  | ModelsTemporalWorkflowResult
  | ErrorResponse;

export const RecalculateInvoiceResponse$zodSchema: z.ZodType<
  RecalculateInvoiceResponse
> = z.union([
  ModelsTemporalWorkflowResult$zodSchema,
  ErrorResponse$zodSchema,
]);
