/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const RecurringPaymentStatus = {
  Pending: "PENDING",
  Active: "ACTIVE",
  Paused: "PAUSED",
  Rejected: "REJECTED",
  Cancelled: "CANCELLED",
  Expired: "EXPIRED",
  Unknown: "UNKNOWN",
} as const;
export type RecurringPaymentStatus = ClosedEnum<typeof RecurringPaymentStatus>;

export const RecurringPaymentStatus$zodSchema = z.enum([
  "PENDING",
  "ACTIVE",
  "PAUSED",
  "REJECTED",
  "CANCELLED",
  "EXPIRED",
  "UNKNOWN",
]);
