/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";

export type RemoveAddonRequest = {
  addon_association_id: string;
  effective_date?: string | undefined;
  proration_behavior?: ProrationBehavior | undefined;
  reason?: string | undefined;
};

export const RemoveAddonRequest$zodSchema: z.ZodType<RemoveAddonRequest> = z
  .object({
    addon_association_id: z.string(),
    effective_date: z.iso.datetime({ offset: true }).optional().describe(
      "EffectiveDate defaults to period end when nil; mid-period with create_prorations issues a wallet credit.",
    ),
    proration_behavior: ProrationBehavior$zodSchema.optional(),
    reason: z.string().optional(),
  });
