/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type RemoveSubscriptionAddonResponse = SuccessResponse | ErrorResponse;

export const RemoveSubscriptionAddonResponse$zodSchema: z.ZodType<
  RemoveSubscriptionAddonResponse
> = z.union([
  SuccessResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
