/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type ReportingUnit = {
  conversion_rate?: number | undefined;
  unit_plural?: string | undefined;
  unit_singular?: string | undefined;
};

export const ReportingUnit$zodSchema: z.ZodType<ReportingUnit> = z.object({
  conversion_rate: z.number().optional().describe(
    "Multiplier: reporting_unit_value = unit_value * conversion_rate; must be > 0",
  ),
  unit_plural: z.string().optional().describe(
    "Display unit label, plural (e.g. \"seconds\")",
  ),
  unit_singular: z.string().optional().describe(
    "Display unit label, singular (e.g. \"second\")",
  ),
});
