/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const ResetUsage = {
  BillingPeriod: "BILLING_PERIOD",
  Never: "NEVER",
} as const;
export type ResetUsage = ClosedEnum<typeof ResetUsage>;

export const ResetUsage$zodSchema = z.enum([
  "BILLING_PERIOD",
  "NEVER",
]);
