/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const RoundType = {
  Up: "up",
  Down: "down",
} as const;
export type RoundType = ClosedEnum<typeof RoundType>;

export const RoundType$zodSchema = z.enum([
  "up",
  "down",
]);
