/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ProviderSavedPaymentMethods,
  ProviderSavedPaymentMethods$zodSchema,
} from "./providersavedpaymentmethods.js";

export type SavedPaymentMethodsResponse = {
  providers?: Array<ProviderSavedPaymentMethods> | undefined;
};

export const SavedPaymentMethodsResponse$zodSchema: z.ZodType<
  SavedPaymentMethodsResponse
> = z.object({
  providers: z.array(ProviderSavedPaymentMethods$zodSchema).optional(),
});
