/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  RecurringPaymentStatus,
  RecurringPaymentStatus$zodSchema,
} from "./recurringpaymentstatus.js";

export type SavedRecurringPaymentDetails = {
  auto_chargeable_till?: string | undefined;
  max_amount?: string | undefined;
  status?: RecurringPaymentStatus | undefined;
};

export const SavedRecurringPaymentDetails$zodSchema: z.ZodType<
  SavedRecurringPaymentDetails
> = z.object({
  auto_chargeable_till: z.string().optional(),
  max_amount: z.string().optional(),
  status: RecurringPaymentStatus$zodSchema.optional(),
});
