/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SavedCardDetails = {
  brand?: string | undefined;
  exp_month?: number | undefined;
  exp_year?: number | undefined;
  last4?: string | undefined;
};

export const SavedCardDetails$zodSchema: z.ZodType<SavedCardDetails> = z.object(
  {
    brand: z.string().optional(),
    exp_month: z.int().optional(),
    exp_year: z.int().optional(),
    last4: z.string().optional(),
  },
);
