/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SourceUsageItem = {
  cost?: string | undefined;
  event_count?: number | undefined;
  percentage?: string | undefined;
  source?: string | undefined;
  usage?: string | undefined;
};

export const SourceUsageItem$zodSchema: z.ZodType<SourceUsageItem> = z.object({
  cost: z.string().optional().describe(
    "cost is the cost attributed to this source for the line item",
  ),
  event_count: z.int().optional().describe(
    "event_count is the number of events from this source (optional)",
  ),
  percentage: z.string().optional().describe(
    "percentage is the percentage of total line item cost from this source (optional)",
  ),
  source: z.string().optional().describe(
    "source is the name of the event source",
  ),
  usage: z.string().optional().describe(
    "usage is the total usage amount from this source (optional, for additional context)",
  ),
});
