/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const Status = {
  Published: "published",
  Deleted: "deleted",
  Archived: "archived",
} as const;
export type Status = ClosedEnum<typeof Status>;

export const Status$zodSchema = z.enum([
  "published",
  "deleted",
  "archived",
]);
