/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  GroupedInvoicingAction,
  GroupedInvoicingAction$zodSchema,
} from "./groupedinvoicingaction.js";

export type SubModifyGroupedInvoicingParams = {
  action: GroupedInvoicingAction;
  child_subscription_ids?: Array<string> | undefined;
  parent_subscription_id?: string | undefined;
};

export const SubModifyGroupedInvoicingParams$zodSchema: z.ZodType<
  SubModifyGroupedInvoicingParams
> = z.object({
  action: GroupedInvoicingAction$zodSchema,
  child_subscription_ids: z.array(z.string()).optional(),
  parent_subscription_id: z.string().optional().describe(
    "ParentSubscriptionID is required for action 'add'.",
  ),
});
