/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SubModifyInheritanceRequest = {
  external_customer_ids_to_inherit_subscription?: Array<string> | undefined;
};

export const SubModifyInheritanceRequest$zodSchema: z.ZodType<
  SubModifyInheritanceRequest
> = z.object({
  external_customer_ids_to_inherit_subscription: z.array(z.string()).optional(),
});
