/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { LineItemChange, LineItemChange$zodSchema } from "./lineitemchange.js";

export type SubModifyLineItemChangeRequest = {
  line_items: Array<LineItemChange>;
};

export const SubModifyLineItemChangeRequest$zodSchema: z.ZodType<
  SubModifyLineItemChangeRequest
> = z.object({
  line_items: z.array(LineItemChange$zodSchema),
});
