/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionRequest,
  AddAddonToSubscriptionRequest$zodSchema,
} from "./addaddontosubscriptionrequest.js";
import {
  RemoveAddonRequest,
  RemoveAddonRequest$zodSchema,
} from "./removeaddonrequest.js";

export type SubModifyBulkAddonParams = {
  adds?: Array<AddAddonToSubscriptionRequest> | undefined;
  removes?: Array<RemoveAddonRequest> | undefined;
};

export const SubModifyBulkAddonParams$zodSchema: z.ZodType<
  SubModifyBulkAddonParams
> = z.object({
  adds: z.array(AddAddonToSubscriptionRequest$zodSchema).optional(),
  removes: z.array(RemoveAddonRequest$zodSchema).optional(),
});
