/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  AddAddonToSubscriptionRequest,
  AddAddonToSubscriptionRequest$zodSchema,
} from "./addaddontosubscriptionrequest.js";
import {
  RemoveAddonRequest,
  RemoveAddonRequest$zodSchema,
} from "./removeaddonrequest.js";
import {
  SubscriptionModificationAction,
  SubscriptionModificationAction$zodSchema,
} from "./subscriptionmodificationaction.js";

export type SubModifyAddonParams = {
  action: SubscriptionModificationAction;
  add?: AddAddonToSubscriptionRequest | undefined;
  remove?: RemoveAddonRequest | undefined;
};

export const SubModifyAddonParams$zodSchema: z.ZodType<SubModifyAddonParams> = z
  .object({
    action: SubscriptionModificationAction$zodSchema,
    add: AddAddonToSubscriptionRequest$zodSchema.optional(),
    remove: RemoveAddonRequest$zodSchema.optional(),
  });
