/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  SubModifyCouponAction,
  SubModifyCouponAction$zodSchema,
} from "./submodifycouponaction.js";

export type SubModifyCouponParams = {
  action: SubModifyCouponAction;
  coupon_association_id?: string | undefined;
  coupon_code?: string | undefined;
  end_date?: string | undefined;
  start_date?: string | undefined;
  subscription_id?: string | undefined;
  subscription_line_item_id?: string | undefined;
};

export const SubModifyCouponParams$zodSchema: z.ZodType<SubModifyCouponParams> =
  z.object({
    action: SubModifyCouponAction$zodSchema,
    coupon_association_id: z.string().optional().describe(
      "Required when action=\"remove\". ID of the CouponAssociation to soft-delete.",
    ),
    coupon_code: z.string().optional().describe(
      "Required for action=\"add\". Coupon code of the coupon to attach.",
    ),
    end_date: z.iso.datetime({ offset: true }).optional().describe(
      "Optional. When the coupon association ends.",
    ),
    start_date: z.iso.datetime({ offset: true }).optional().describe(
      "Optional. When the coupon association starts; defaults to now.",
    ),
    subscription_id: z.string().optional().describe(
      "Optional. Apply at subscription level. Mutually exclusive with SubscriptionLineItemID.",
    ),
    subscription_line_item_id: z.string().optional().describe(
      "Optional. Apply at a specific line item. Mutually exclusive with SubscriptionID.",
    ),
  });
