/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubModifyTaxAction = {
  Add: "add",
  Remove: "remove",
} as const;
export type SubModifyTaxAction = ClosedEnum<typeof SubModifyTaxAction>;

export const SubModifyTaxAction$zodSchema = z.enum([
  "add",
  "remove",
]);
