/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  GroupedInvoicingChildRequest,
  GroupedInvoicingChildRequest$zodSchema,
} from "./groupedinvoicingchildrequest.js";

export type SubscriptionInheritanceConfig = {
  external_customer_ids_to_inherit_subscription?: Array<string> | undefined;
  grouped_invoicing_children_to_create?:
    | Array<GroupedInvoicingChildRequest>
    | undefined;
  invoicing_customer_external_id?: string | undefined;
  parent_subscription_id?: string | undefined;
  subscriptions_ids_for_grouped_invoicing?: Array<string> | undefined;
};

export const SubscriptionInheritanceConfig$zodSchema: z.ZodType<
  SubscriptionInheritanceConfig
> = z.object({
  external_customer_ids_to_inherit_subscription: z.array(z.string()).optional()
    .describe(
      "ExternalCustomerIDsToInheritSubscription creates inherited skeleton subscriptions for child customers. Parent only.",
    ),
  grouped_invoicing_children_to_create: z.array(
    GroupedInvoicingChildRequest$zodSchema,
  ).optional(),
  invoicing_customer_external_id: z.string().optional().describe(
    "InvoicingCustomerExternalID routes invoices to a different customer. Required for delegated; rejected for inherited.",
  ),
  parent_subscription_id: z.string().optional().describe(
    "ParentSubscriptionID links to an existing parent. Required for inherited/grouped_invoicing; rejected for standalone/delegated/parent.",
  ),
  subscriptions_ids_for_grouped_invoicing: z.array(z.string()).optional()
    .describe(
      "SubscriptionsIDsForGroupedInvoicing converts existing standalone subscriptions to grouped_invoicing under this parent. Parent only.",
    ),
});
