/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionModificationAction = {
  Add: "add",
  Remove: "remove",
} as const;
export type SubscriptionModificationAction = ClosedEnum<
  typeof SubscriptionModificationAction
>;

export const SubscriptionModificationAction$zodSchema = z.enum([
  "add",
  "remove",
]);
