/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ProrationBehavior,
  ProrationBehavior$zodSchema,
} from "./prorationbehavior.js";
import {
  SubscriptionChangeEntityPolicies,
  SubscriptionChangeEntityPolicies$zodSchema,
} from "./subscriptionchangeentitypolicies.js";

export type SubscriptionChangeV2Request = {
  entity_policies?: SubscriptionChangeEntityPolicies | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  proration_behavior: ProrationBehavior;
  target_plan_id: string;
};

export const SubscriptionChangeV2Request$zodSchema: z.ZodType<
  SubscriptionChangeV2Request
> = z.object({
  entity_policies: SubscriptionChangeEntityPolicies$zodSchema.optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  proration_behavior: ProrationBehavior$zodSchema,
  target_plan_id: z.string(),
});
