/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionChangeEntityType = {
  Plan: "plan",
  Addon: "addon",
  CreditGrant: "credit_grant",
  Entitlement: "entitlement",
  EntitlementGrant: "entitlement_grant",
} as const;
export type SubscriptionChangeEntityType = ClosedEnum<
  typeof SubscriptionChangeEntityType
>;

export const SubscriptionChangeEntityType$zodSchema = z.enum([
  "plan",
  "addon",
  "credit_grant",
  "entitlement",
  "entitlement_grant",
]);
