/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  DebugTrackerStatus,
  DebugTrackerStatus$zodSchema,
} from "./debugtrackerstatus.js";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  MatchedSubscriptionLineItem,
  MatchedSubscriptionLineItem$zodSchema,
} from "./matchedsubscriptionlineitem.js";

export type SubscriptionLineItemLookupResult = {
  error?: ErrorResponse | undefined;
  matched_line_items?: Array<MatchedSubscriptionLineItem> | undefined;
  status?: DebugTrackerStatus | undefined;
};

export const SubscriptionLineItemLookupResult$zodSchema: z.ZodType<
  SubscriptionLineItemLookupResult
> = z.object({
  error: ErrorResponse$zodSchema.optional(),
  matched_line_items: z.array(MatchedSubscriptionLineItem$zodSchema).optional(),
  status: DebugTrackerStatus$zodSchema.optional(),
});
