/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  EntityChangePolicy,
  EntityChangePolicy$zodSchema,
} from "./entitychangepolicy.js";

export type SubscriptionChangeEntityPolicies = {
  addons?: EntityChangePolicy | undefined;
};

export const SubscriptionChangeEntityPolicies$zodSchema: z.ZodType<
  SubscriptionChangeEntityPolicies
> = z.object({
  addons: EntityChangePolicy$zodSchema.optional(),
});
