/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  OnPendingSchedulePolicy,
  OnPendingSchedulePolicy$zodSchema,
} from "./onpendingschedulepolicy.js";

export type SubscriptionChangeConflictPolicies = {
  on_pending_schedule?: OnPendingSchedulePolicy | undefined;
};

export const SubscriptionChangeConflictPolicies$zodSchema: z.ZodType<
  SubscriptionChangeConflictPolicies
> = z.object({
  on_pending_schedule: OnPendingSchedulePolicy$zodSchema.optional(),
});
