/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangedResources,
  ChangedResources$zodSchema,
} from "./changedresources.js";
import {
  EntityChangeResult,
  EntityChangeResult$zodSchema,
} from "./entitychangeresult.js";
import { PlanSummary, PlanSummary$zodSchema } from "./plansummary.js";
import {
  SubscriptionChangeType,
  SubscriptionChangeType$zodSchema,
} from "./subscriptionchangetype.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type SubscriptionChangeV2Response = {
  change_type?: SubscriptionChangeType | undefined;
  changed_resources?: ChangedResources | undefined;
  effective_at?: string | undefined;
  entity_changes?: Array<EntityChangeResult> | undefined;
  from_plan?: PlanSummary | undefined;
  is_scheduled?: boolean | undefined;
  metadata?: { [k: string]: string } | undefined;
  schedule_id?: string | undefined;
  scheduled_at?: string | undefined;
  subscription?: SubscriptionResponse | undefined;
  to_plan?: PlanSummary | undefined;
  warnings?: Array<string> | undefined;
};

export const SubscriptionChangeV2Response$zodSchema: z.ZodType<
  SubscriptionChangeV2Response
> = z.object({
  change_type: SubscriptionChangeType$zodSchema.optional(),
  changed_resources: ChangedResources$zodSchema.optional(),
  effective_at: z.iso.datetime({ offset: true }).optional(),
  entity_changes: z.array(EntityChangeResult$zodSchema).optional(),
  from_plan: PlanSummary$zodSchema.optional(),
  is_scheduled: z.boolean().optional().describe(
    "IsScheduled is true when the change was deferred to the period end instead\nof being applied immediately.",
  ),
  metadata: z.record(z.string(), z.string()).optional(),
  schedule_id: z.string().optional(),
  scheduled_at: z.iso.datetime({ offset: true }).optional(),
  subscription: SubscriptionResponse$zodSchema.optional(),
  to_plan: PlanSummary$zodSchema.optional(),
  warnings: z.array(z.string()).optional(),
});
