/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SubscriptionCouponInput = {
  coupon_code: string;
  end_date?: string | undefined;
  price_id?: string | undefined;
  start_date?: string | undefined;
};

export const SubscriptionCouponInput$zodSchema: z.ZodType<
  SubscriptionCouponInput
> = z.object({
  coupon_code: z.string(),
  end_date: z.iso.datetime({ offset: true }).optional(),
  price_id: z.string().optional(),
  start_date: z.iso.datetime({ offset: true }).optional(),
});
