/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionScheduleChangeType = {
  PlanChange: "plan_change",
  Cancellation: "cancellation",
} as const;
export type SubscriptionScheduleChangeType = ClosedEnum<
  typeof SubscriptionScheduleChangeType
>;

export const SubscriptionScheduleChangeType$zodSchema = z.enum([
  "plan_change",
  "cancellation",
]);
