/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  ChangedResources,
  ChangedResources$zodSchema,
} from "./changedresources.js";
import {
  SubscriptionResponse,
  SubscriptionResponse$zodSchema,
} from "./subscriptionresponse.js";

export type SubscriptionModifyResponse = {
  changed_resources?: ChangedResources | undefined;
  subscription?: SubscriptionResponse | undefined;
};

export const SubscriptionModifyResponse$zodSchema: z.ZodType<
  SubscriptionModifyResponse
> = z.object({
  changed_resources: ChangedResources$zodSchema.optional(),
  subscription: SubscriptionResponse$zodSchema.optional(),
});
