/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingModel, BillingModel$zodSchema } from "./billingmodel.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import { BillingTier, BillingTier$zodSchema } from "./billingtier.js";
import {
  CreatePriceTier,
  CreatePriceTier$zodSchema,
} from "./createpricetier.js";
import { InvoiceCadence, InvoiceCadence$zodSchema } from "./invoicecadence.js";
import {
  PriceTransformQuantity,
  PriceTransformQuantity$zodSchema,
} from "./pricetransformquantity.js";
import { PriceType, PriceType$zodSchema } from "./pricetype.js";
import {
  PriceUnitConfig,
  PriceUnitConfig$zodSchema,
} from "./priceunitconfig.js";
import { PriceUnitType, PriceUnitType$zodSchema } from "./priceunittype.js";

export type SubscriptionPriceCreateRequest = {
  amount?: string | undefined;
  billing_model: BillingModel;
  billing_period: BillingPeriod;
  billing_period_count?: number | undefined;
  description?: string | undefined;
  display_name?: string | undefined;
  end_date?: string | undefined;
  filter_values?: { [k: string]: Array<string> } | undefined;
  invoice_cadence: InvoiceCadence;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  meter_id?: string | undefined;
  min_quantity?: number | undefined;
  price_unit_config?: PriceUnitConfig | undefined;
  price_unit_type: PriceUnitType;
  start_date?: string | undefined;
  tier_mode?: BillingTier | undefined;
  tiers?: Array<CreatePriceTier> | undefined;
  transform_quantity?: PriceTransformQuantity | undefined;
  trial_period_days?: number | undefined;
  type: PriceType;
};

export const SubscriptionPriceCreateRequest$zodSchema: z.ZodType<
  SubscriptionPriceCreateRequest
> = z.object({
  amount: z.string().optional(),
  billing_model: BillingModel$zodSchema,
  billing_period: BillingPeriod$zodSchema,
  billing_period_count: z.int().optional(),
  description: z.string().optional(),
  display_name: z.string().optional(),
  end_date: z.iso.datetime({ offset: true }).optional(),
  filter_values: z.record(z.string(), z.array(z.string())).optional(),
  invoice_cadence: InvoiceCadence$zodSchema,
  lookup_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  meter_id: z.string().optional(),
  min_quantity: z.int().optional(),
  price_unit_config: PriceUnitConfig$zodSchema.optional(),
  price_unit_type: PriceUnitType$zodSchema,
  start_date: z.iso.datetime({ offset: true }).optional(),
  tier_mode: BillingTier$zodSchema.optional(),
  tiers: z.array(CreatePriceTier$zodSchema).optional(),
  transform_quantity: PriceTransformQuantity$zodSchema.optional(),
  trial_period_days: z.int().optional(),
  type: PriceType$zodSchema,
});
