/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionLineItemEntityType = {
  Plan: "plan",
  Addon: "addon",
  Subscription: "subscription",
} as const;
export type SubscriptionLineItemEntityType = ClosedEnum<
  typeof SubscriptionLineItemEntityType
>;

export const SubscriptionLineItemEntityType$zodSchema = z.enum([
  "plan",
  "addon",
  "subscription",
]);
