/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  BillingPeriodBehaviour,
  BillingPeriodBehaviour$zodSchema,
} from "./billingperiodbehaviour.js";

export type SubscriptionChangeBillingPeriodResult = {
  behaviour?: BillingPeriodBehaviour | undefined;
  billing_anchor?: string | undefined;
  current_period_end?: string | undefined;
  current_period_start?: string | undefined;
};

export const SubscriptionChangeBillingPeriodResult$zodSchema: z.ZodType<
  SubscriptionChangeBillingPeriodResult
> = z.object({
  behaviour: BillingPeriodBehaviour$zodSchema.optional(),
  billing_anchor: z.iso.datetime({ offset: true }).optional(),
  current_period_end: z.iso.datetime({ offset: true }).optional(),
  current_period_start: z.iso.datetime({ offset: true }).optional(),
});
