/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const SubscriptionModifyType = {
  Inheritance: "inheritance",
  QuantityChange: "quantity_change",
  GroupedInvoicing: "grouped_invoicing",
  TrialEnd: "trial_end",
} as const;
export type SubscriptionModifyType = ClosedEnum<typeof SubscriptionModifyType>;

export const SubscriptionModifyType$zodSchema = z.enum([
  "inheritance",
  "quantity_change",
  "grouped_invoicing",
  "trial_end",
]);
