/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";
import { BillingCadence, BillingCadence$zodSchema } from "./billingcadence.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import {
  FilterCondition,
  FilterCondition$zodSchema,
} from "./filtercondition.js";
import { SortCondition, SortCondition$zodSchema } from "./sortcondition.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  SubscriptionStatus,
  SubscriptionStatus$zodSchema,
} from "./subscriptionstatus.js";
import {
  SubscriptionType,
  SubscriptionType$zodSchema,
} from "./subscriptiontype.js";

export const SubscriptionFilterOrder = {
  Asc: "asc",
  Desc: "desc",
} as const;
export type SubscriptionFilterOrder = ClosedEnum<
  typeof SubscriptionFilterOrder
>;

export const SubscriptionFilterOrder$zodSchema = z.enum([
  "asc",
  "desc",
]);

export type SubscriptionFilter = {
  active_at?: string | undefined;
  billing_cadence?: Array<BillingCadence> | undefined;
  billing_period?: Array<BillingPeriod> | undefined;
  customer_id?: string | undefined;
  customer_ids?: Array<string> | undefined;
  effective_date_for_update?: string | undefined;
  end_time?: string | undefined;
  expand?: string | undefined;
  external_customer_id?: string | undefined;
  filters?: Array<FilterCondition> | undefined;
  invoicing_customer_ids?: Array<string> | undefined;
  limit?: number | undefined;
  offset?: number | undefined;
  order?: SubscriptionFilterOrder | undefined;
  parent_subscription_ids?: Array<string> | undefined;
  plan_id?: string | undefined;
  sort?: Array<SortCondition> | undefined;
  start_time?: string | undefined;
  status?: Status | undefined;
  subscription_ids?: Array<string> | undefined;
  subscription_status?: Array<SubscriptionStatus> | undefined;
  subscription_type?: Array<SubscriptionType> | undefined;
  trial_end_due_lte?: string | undefined;
  with_line_items?: boolean | undefined;
};

export const SubscriptionFilter$zodSchema: z.ZodType<SubscriptionFilter> = z
  .object({
    active_at: z.iso.datetime({ offset: true }).optional().describe(
      "ActiveAt filters subscriptions that are active at the given time",
    ),
    billing_cadence: z.array(BillingCadence$zodSchema).optional().describe(
      "BillingCadence filters by billing cadence",
    ),
    billing_period: z.array(BillingPeriod$zodSchema).optional().describe(
      "BillingPeriod filters by billing period",
    ),
    customer_id: z.string().optional().describe(
      "CustomerID filters by customer ID",
    ),
    customer_ids: z.array(z.string()).optional().describe(
      "CustomerIDs filters by customer IDs",
    ),
    effective_date_for_update: z.string().optional().describe(
      "EffectiveDateForUpdate selects subscriptions that need a billing-period pass on or before this time:\ncurrent_period_end <= date OR (cancel_at IS NOT NULL AND cancel_at <= date).\nWhen nil, period/cancel cutoff logic is not applied by this field (see TimeRangeFilter for legacy period-end filtering).",
    ),
    end_time: z.iso.datetime({ offset: true }).optional(),
    expand: z.string().optional(),
    external_customer_id: z.string().optional().describe(
      "ExternalCustomerID filters by external customer ID",
    ),
    filters: z.array(FilterCondition$zodSchema).optional(),
    invoicing_customer_ids: z.array(z.string()).optional().describe(
      "InvoicingCustomerIDs filters by invoicing customer ID",
    ),
    limit: z.int().optional(),
    offset: z.int().optional(),
    order: SubscriptionFilterOrder$zodSchema.optional(),
    parent_subscription_ids: z.array(z.string()).optional().describe(
      "ParentSubscriptionIDs filters by parent subscription IDs",
    ),
    plan_id: z.string().optional().describe("PlanID filters by plan ID"),
    sort: z.array(SortCondition$zodSchema).optional(),
    start_time: z.iso.datetime({ offset: true }).optional(),
    status: Status$zodSchema.optional(),
    subscription_ids: z.array(z.string()).optional(),
    subscription_status: z.array(SubscriptionStatus$zodSchema).optional()
      .describe("SubscriptionStatus filters by subscription status"),
    subscription_type: z.array(SubscriptionType$zodSchema).optional().describe(
      "SubscriptionType filters by subscription type",
    ),
    trial_end_due_lte: z.iso.datetime({ offset: true }).optional().describe(
      "TrialEndDueLTE, when set, restricts to subscriptions with trial_end not nil and trial_end <= trial_end_due_lte.\nUse with subscription_status trialing for trial-end cron processing.",
    ),
    with_line_items: z.boolean().optional().describe(
      "WithLineItems includes line items in the response",
    ),
  });
