/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type SuccessResponse = { message?: string | undefined };

export const SuccessResponse$zodSchema: z.ZodType<SuccessResponse> = z.object({
  message: z.string().optional(),
});
