/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TaxExemptionReasonCode,
  TaxExemptionReasonCode$zodSchema,
} from "./taxexemptionreasoncode.js";

export type TaxExemptionSummary = {
  reason?: string | undefined;
  reason_code?: TaxExemptionReasonCode | undefined;
};

export const TaxExemptionSummary$zodSchema: z.ZodType<TaxExemptionSummary> = z
  .object({
    reason: z.string().optional(),
    reason_code: TaxExemptionReasonCode$zodSchema.optional(),
  });
