/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Status, Status$zodSchema } from "./status.js";
import { TaxRateScope, TaxRateScope$zodSchema } from "./taxratescope.js";
import { TaxRateStatus, TaxRateStatus$zodSchema } from "./taxratestatus.js";
import { TaxRateType, TaxRateType$zodSchema } from "./taxratetype.js";

export type TaxRateResponse = {
  code?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  fixed_value?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  percentage_value?: string | undefined;
  scope?: TaxRateScope | undefined;
  status?: Status | undefined;
  tax_rate_status?: TaxRateStatus | undefined;
  tax_rate_type?: TaxRateType | undefined;
  tenant_id?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
};

export const TaxRateResponse$zodSchema: z.ZodType<TaxRateResponse> = z.object({
  code: z.string().optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  fixed_value: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  percentage_value: z.string().optional(),
  scope: TaxRateScope$zodSchema.optional(),
  status: Status$zodSchema.optional(),
  tax_rate_status: TaxRateStatus$zodSchema.optional(),
  tax_rate_type: TaxRateType$zodSchema.optional(),
  tenant_id: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
});
