/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaxRateScope = {
  Internal: "INTERNAL",
  External: "EXTERNAL",
  Onetime: "ONETIME",
} as const;
export type TaxRateScope = ClosedEnum<typeof TaxRateScope>;

export const TaxRateScope$zodSchema = z.enum([
  "INTERNAL",
  "EXTERNAL",
  "ONETIME",
]);
