/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaxRateStatus = {
  Active: "ACTIVE",
  Inactive: "INACTIVE",
} as const;
export type TaxRateStatus = ClosedEnum<typeof TaxRateStatus>;

export const TaxRateStatus$zodSchema = z.enum([
  "ACTIVE",
  "INACTIVE",
]);
