/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaxRateEntityType = {
  Customer: "customer",
  Subscription: "subscription",
  Invoice: "invoice",
  Tenant: "tenant",
} as const;
export type TaxRateEntityType = ClosedEnum<typeof TaxRateEntityType>;

export const TaxRateEntityType$zodSchema = z.enum([
  "customer",
  "subscription",
  "invoice",
  "tenant",
]);
