/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TaxExemptionSummary,
  TaxExemptionSummary$zodSchema,
} from "./taxexemptionsummary.js";

export type TaxSummary = {
  exclusive_tax?: string | undefined;
  exemption?: TaxExemptionSummary | undefined;
  inclusive_tax?: string | undefined;
  total_tax?: string | undefined;
};

export const TaxSummary$zodSchema: z.ZodType<TaxSummary> = z.object({
  exclusive_tax: z.string().optional(),
  exemption: TaxExemptionSummary$zodSchema.optional(),
  inclusive_tax: z.string().optional(),
  total_tax: z.string().optional(),
});
