/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TaxTreatment = {
  Taxable: "taxable",
  Exempt: "exempt",
} as const;
export type TaxTreatment = ClosedEnum<typeof TaxTreatment>;

export const TaxTreatment$zodSchema = z.enum([
  "taxable",
  "exempt",
]);
