/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  TenantBillingDetails,
  TenantBillingDetails$zodSchema,
} from "./tenantbillingdetails.js";

export type TenantResponse = {
  billing_details?: TenantBillingDetails | undefined;
  created_at?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: string | undefined;
  updated_at?: string | undefined;
};

export const TenantResponse$zodSchema: z.ZodType<TenantResponse> = z.object({
  billing_details: TenantBillingDetails$zodSchema.optional(),
  created_at: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  status: z.string().optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
});
