/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Address, Address$zodSchema } from "./address.js";

export type TenantBillingDetails = {
  address?: Address | undefined;
  email?: string | undefined;
  help_email?: string | undefined;
  phone?: string | undefined;
};

export const TenantBillingDetails$zodSchema: z.ZodType<TenantBillingDetails> = z
  .object({
    address: Address$zodSchema.optional(),
    email: z.string().optional(),
    help_email: z.string().optional(),
    phone: z.string().optional(),
  });
