/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { Bucket, Bucket$zodSchema } from "./bucket.js";
import { CommitmentType, CommitmentType$zodSchema } from "./commitmenttype.js";

export type TimeOfDayBucket = {
  commitment_type?: CommitmentType | undefined;
  commitment_value?: string | undefined;
  end?: Bucket | undefined;
  id?: string | undefined;
  overage_factor?: number | undefined;
  price_id?: string | undefined;
  start?: Bucket | undefined;
  true_up_enabled?: boolean | undefined;
};

export const TimeOfDayBucket$zodSchema: z.ZodType<TimeOfDayBucket> = z.object({
  commitment_type: CommitmentType$zodSchema.optional(),
  commitment_value: z.string().optional(),
  end: Bucket$zodSchema.optional(),
  id: z.string().optional().describe(
    "ID is server-assigned. Stable for the lifetime of the line item;\ninvoice breakdown and analytics responses reference this ID.",
  ),
  overage_factor: z.number().optional(),
  price_id: z.string().optional().describe(
    "PriceID is the SUBSCRIPTION-scoped price created at bucket-creation time.\nImmutable post-create; changing pricing requires a successor line item.",
  ),
  start: Bucket$zodSchema.optional(),
  true_up_enabled: z.boolean().optional(),
});
