/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TransactionStatus = {
  Pending: "pending",
  Completed: "completed",
  Failed: "failed",
} as const;
export type TransactionStatus = ClosedEnum<typeof TransactionStatus>;

export const TransactionStatus$zodSchema = z.enum([
  "pending",
  "completed",
  "failed",
]);
