/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TransactionType = {
  Credit: "credit",
  Debit: "debit",
} as const;
export type TransactionType = ClosedEnum<typeof TransactionType>;

export const TransactionType$zodSchema = z.enum([
  "credit",
  "debit",
]);
