/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TransactionReason = {
  InvoicePayment: "INVOICE_PAYMENT",
  FreeCreditGrant: "FREE_CREDIT_GRANT",
  SubscriptionCreditGrant: "SUBSCRIPTION_CREDIT_GRANT",
  PurchasedCreditInvoiced: "PURCHASED_CREDIT_INVOICED",
  PurchasedCreditDirect: "PURCHASED_CREDIT_DIRECT",
  CreditNote: "CREDIT_NOTE",
  CreditExpired: "CREDIT_EXPIRED",
  WalletTermination: "WALLET_TERMINATION",
  ManualBalanceDebit: "MANUAL_BALANCE_DEBIT",
  CreditAdjustment: "CREDIT_ADJUSTMENT",
  InvoiceVoidRefund: "INVOICE_VOID_REFUND",
} as const;
export type TransactionReason = ClosedEnum<typeof TransactionReason>;

export const TransactionReason$zodSchema = z.enum([
  "INVOICE_PAYMENT",
  "FREE_CREDIT_GRANT",
  "SUBSCRIPTION_CREDIT_GRANT",
  "PURCHASED_CREDIT_INVOICED",
  "PURCHASED_CREDIT_DIRECT",
  "CREDIT_NOTE",
  "CREDIT_EXPIRED",
  "WALLET_TERMINATION",
  "MANUAL_BALANCE_DEBIT",
  "CREDIT_ADJUSTMENT",
  "INVOICE_VOID_REFUND",
]);
