/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const TrialEndAction = {
  Immediate: "immediate",
  ScheduledDate: "scheduled_date",
} as const;
export type TrialEndAction = ClosedEnum<typeof TrialEndAction>;

export const TrialEndAction$zodSchema = z.enum([
  "immediate",
  "scheduled_date",
]);
