/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type TriggerInvoiceCommsWebhookRequest = { id: string };

export const TriggerInvoiceCommsWebhookRequest$zodSchema: z.ZodType<
  TriggerInvoiceCommsWebhookRequest
> = z.object({
  id: z.string().describe("Invoice ID"),
});

export type TriggerInvoiceCommsWebhookResponse =
  | SuccessResponse
  | ErrorResponse;

export const TriggerInvoiceCommsWebhookResponse$zodSchema: z.ZodType<
  TriggerInvoiceCommsWebhookResponse
> = z.union([
  SuccessResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
