/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { BillingModel, BillingModel$zodSchema } from "./billingmodel.js";
import { BillingPeriod, BillingPeriod$zodSchema } from "./billingperiod.js";
import { BillingTier, BillingTier$zodSchema } from "./billingtier.js";
import { CommitmentType, CommitmentType$zodSchema } from "./commitmenttype.js";
import {
  CreatePriceTier,
  CreatePriceTier$zodSchema,
} from "./createpricetier.js";
import {
  PriceTransformQuantity,
  PriceTransformQuantity$zodSchema,
} from "./pricetransformquantity.js";

export type UpdateSubscriptionLineItemRequest = {
  amount?: string | undefined;
  billing_model?: BillingModel | undefined;
  commitment_amount?: number | undefined;
  commitment_duration?: BillingPeriod | undefined;
  commitment_overage_factor?: number | undefined;
  commitment_quantity?: number | undefined;
  commitment_true_up_enabled?: boolean | undefined;
  commitment_type?: CommitmentType | undefined;
  commitment_windowed?: boolean | undefined;
  effective_from?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  tier_mode?: BillingTier | undefined;
  tiers?: Array<CreatePriceTier> | undefined;
  transform_quantity?: PriceTransformQuantity | undefined;
};

export const UpdateSubscriptionLineItemRequest$zodSchema: z.ZodType<
  UpdateSubscriptionLineItemRequest
> = z.object({
  amount: z.string().optional().describe(
    "Amount is the new price amount that overrides the original price",
  ),
  billing_model: BillingModel$zodSchema.optional(),
  commitment_amount: z.number().optional().describe("Commitment fields"),
  commitment_duration: BillingPeriod$zodSchema.optional(),
  commitment_overage_factor: z.number().optional(),
  commitment_quantity: z.number().optional(),
  commitment_true_up_enabled: z.boolean().optional(),
  commitment_type: CommitmentType$zodSchema.optional(),
  commitment_windowed: z.boolean().optional(),
  effective_from: z.string().optional().describe(
    "EffectiveFrom for the existing line item (if not provided, defaults to now)",
  ),
  metadata: z.record(z.string(), z.string()).optional().describe(
    "Metadata for the new line item",
  ),
  tier_mode: BillingTier$zodSchema.optional(),
  tiers: z.array(CreatePriceTier$zodSchema).optional().describe(
    "Tiers determines the pricing tiers for this line item",
  ),
  transform_quantity: PriceTransformQuantity$zodSchema.optional(),
});
