/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SubscriptionLineItemResponse,
  SubscriptionLineItemResponse$zodSchema,
} from "./subscriptionlineitemresponse.js";
import {
  UpdateSubscriptionLineItemRequest,
  UpdateSubscriptionLineItemRequest$zodSchema,
} from "./updatesubscriptionlineitemrequest.js";

export type UpdateSubscriptionLineItemRequestRequest = {
  id: string;
  body: UpdateSubscriptionLineItemRequest;
};

export const UpdateSubscriptionLineItemRequestRequest$zodSchema: z.ZodType<
  UpdateSubscriptionLineItemRequestRequest
> = z.object({
  body: UpdateSubscriptionLineItemRequest$zodSchema.describe(
    "Update Line Item Request",
  ),
  id: z.string().describe("Line Item ID"),
});

export type UpdateSubscriptionLineItemResponse =
  | SubscriptionLineItemResponse
  | ErrorResponse;

export const UpdateSubscriptionLineItemResponse$zodSchema: z.ZodType<
  UpdateSubscriptionLineItemResponse
> = z.union([
  SubscriptionLineItemResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
