/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import { PlanResponse, PlanResponse$zodSchema } from "./planresponse.js";
import {
  UpdatePlanRequest,
  UpdatePlanRequest$zodSchema,
} from "./updateplanrequest.js";

export type UpdatePlanRequestRequest = { id: string; body: UpdatePlanRequest };

export const UpdatePlanRequestRequest$zodSchema: z.ZodType<
  UpdatePlanRequestRequest
> = z.object({
  body: UpdatePlanRequest$zodSchema.describe("Plan update"),
  id: z.string().describe("Plan ID"),
});

export type UpdatePlanResponse = PlanResponse | ErrorResponse;

export const UpdatePlanResponse$zodSchema: z.ZodType<UpdatePlanResponse> = z
  .union([
    PlanResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
