/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PaymentStatus, PaymentStatus$zodSchema } from "./paymentstatus.js";

export type UpdatePaymentStatusRequest = {
  amount?: string | undefined;
  payment_status: PaymentStatus;
};

export const UpdatePaymentStatusRequest$zodSchema: z.ZodType<
  UpdatePaymentStatusRequest
> = z.object({
  amount: z.string().optional().describe(
    "amount is the optional payment amount to record",
  ),
  payment_status: PaymentStatus$zodSchema,
});
