/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import {
  UpdateInvoiceRequest,
  UpdateInvoiceRequest$zodSchema,
} from "./updateinvoicerequest.js";

export type UpdateInvoiceRequestRequest = {
  id: string;
  body: UpdateInvoiceRequest;
};

export const UpdateInvoiceRequestRequest$zodSchema: z.ZodType<
  UpdateInvoiceRequestRequest
> = z.object({
  body: UpdateInvoiceRequest$zodSchema.describe("Invoice Update Request"),
  id: z.string().describe("Invoice ID"),
});

export type UpdateInvoiceResponse = InvoiceResponse | ErrorResponse;

export const UpdateInvoiceResponse$zodSchema: z.ZodType<UpdateInvoiceResponse> =
  z.union([
    InvoiceResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
