/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CreateEntityIntegrationMappingRequest,
  CreateEntityIntegrationMappingRequest$zodSchema,
} from "./createentityintegrationmappingrequest.js";

/**
 * Request object for updating an existing customer. All fields are optional - only provided fields will be updated
 */
export type UpdateCustomerRequest = {
  address_city?: string | undefined;
  address_country?: string | undefined;
  address_line1?: string | undefined;
  address_line2?: string | undefined;
  address_postal_code?: string | undefined;
  address_state?: string | undefined;
  email?: string | undefined;
  external_id?: string | undefined;
  integration_entity_mapping?:
    | Array<CreateEntityIntegrationMappingRequest>
    | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const UpdateCustomerRequest$zodSchema: z.ZodType<UpdateCustomerRequest> =
  z.object({
    address_city: z.string().optional().describe(
      "address_city is the updated city name with maximum 100 characters",
    ),
    address_country: z.string().optional().describe(
      "address_country is the updated two-letter ISO 3166-1 alpha-2 country code",
    ),
    address_line1: z.string().optional().describe(
      "address_line1 is the updated primary address line with maximum 255 characters",
    ),
    address_line2: z.string().optional().describe(
      "address_line2 is the updated secondary address line with maximum 255 characters",
    ),
    address_postal_code: z.string().optional().describe(
      "address_postal_code is the updated postal code with maximum 20 characters",
    ),
    address_state: z.string().optional().describe(
      "address_state is the updated state, province, or region name with maximum 100 characters",
    ),
    email: z.string().optional().describe(
      "email is the updated email address and must be a valid email format if provided",
    ),
    external_id: z.string().optional().describe(
      "external_id is the updated external identifier for the customer",
    ),
    integration_entity_mapping: z.array(
      CreateEntityIntegrationMappingRequest$zodSchema,
    ).optional().describe(
      "integration_entity_mapping contains provider integration mappings for this customer",
    ),
    metadata: z.record(z.string(), z.string()).optional().describe(
      "metadata contains updated key-value pairs that will replace existing metadata",
    ),
    name: z.string().optional().describe(
      "name is the updated name or company name for the customer",
    ),
  }).describe(
    "Request object for updating an existing customer. All fields are optional - only provided fields will be updated",
  );
