/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateInvoiceRequest = {
  due_date?: string | undefined;
  invoice_pdf_url?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
};

export const UpdateInvoiceRequest$zodSchema: z.ZodType<UpdateInvoiceRequest> = z
  .object({
    due_date: z.iso.datetime({ offset: true }).optional(),
    invoice_pdf_url: z.string().optional().describe(
      "invoice_pdf_url is the URL where customers can download the PDF version of this invoice",
    ),
    metadata: z.record(z.string(), z.string()).optional(),
  });
