/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateLineItemRequest = {
  amount?: string | undefined;
  description?: string | undefined;
  display_name?: string | undefined;
  period_end?: string | undefined;
  period_start?: string | undefined;
  quantity?: string | undefined;
};

export const UpdateLineItemRequest$zodSchema: z.ZodType<UpdateLineItemRequest> =
  z.object({
    amount: z.string().optional(),
    description: z.string().optional(),
    display_name: z.string().optional(),
    period_end: z.iso.datetime({ offset: true }).optional(),
    period_start: z.iso.datetime({ offset: true }).optional(),
    quantity: z.string().optional(),
  });
