/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  InvoiceResponse,
  InvoiceResponse$zodSchema,
} from "./invoiceresponse.js";
import {
  UpdatePaymentStatusRequest,
  UpdatePaymentStatusRequest$zodSchema,
} from "./updatepaymentstatusrequest.js";

export type UpdateInvoicePaymentStatusRequest = {
  id: string;
  body: UpdatePaymentStatusRequest;
};

export const UpdateInvoicePaymentStatusRequest$zodSchema: z.ZodType<
  UpdateInvoicePaymentStatusRequest
> = z.object({
  body: UpdatePaymentStatusRequest$zodSchema.describe(
    "Payment Status Update Request",
  ),
  id: z.string().describe("Invoice ID"),
});

export type UpdateInvoicePaymentStatusResponse =
  | InvoiceResponse
  | ErrorResponse;

export const UpdateInvoicePaymentStatusResponse$zodSchema: z.ZodType<
  UpdateInvoicePaymentStatusResponse
> = z.union([
  InvoiceResponse$zodSchema,
  ErrorResponse$zodSchema,
]);
