/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdatePlanRequest = {
  description?: string | undefined;
  display_order?: number | undefined;
  lookup_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
};

export const UpdatePlanRequest$zodSchema: z.ZodType<UpdatePlanRequest> = z
  .object({
    description: z.string().optional(),
    display_order: z.int().optional(),
    lookup_key: z.string().optional(),
    metadata: z.record(z.string(), z.string()).optional(),
    name: z.string().optional(),
  });
