/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UsageAnalyticPoint = {
  computed_commitment_utilized_amount?: string | undefined;
  computed_overage_amount?: string | undefined;
  computed_true_up_amount?: string | undefined;
  cost?: string | undefined;
  event_count?: number | undefined;
  timestamp?: string | undefined;
  usage?: string | undefined;
};

export const UsageAnalyticPoint$zodSchema: z.ZodType<UsageAnalyticPoint> = z
  .object({
    computed_commitment_utilized_amount: z.string().optional().describe(
      "Commitment breakdown (only populated for windowed commitments)",
    ),
    computed_overage_amount: z.string().optional(),
    computed_true_up_amount: z.string().optional(),
    cost: z.string().optional(),
    event_count: z.int().optional().describe(
      "Number of events in this time window",
    ),
    timestamp: z.string().optional(),
    usage: z.string().optional(),
  });
