/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UsageResult = {
  value?: number | undefined;
  window_size?: string | undefined;
};

export const UsageResult$zodSchema: z.ZodType<UsageResult> = z.object({
  value: z.number().optional(),
  window_size: z.string().optional(),
});
