/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { PointBucket, PointBucket$zodSchema } from "./pointbucket.js";

export type UsageAnalyticPoint = {
  buckets?: Array<PointBucket> | undefined;
  computed_commitment_utilized_amount?: string | undefined;
  computed_overage_amount?: string | undefined;
  computed_true_up_amount?: string | undefined;
  cost?: string | undefined;
  discount?: string | undefined;
  event_count?: number | undefined;
  subtotal?: string | undefined;
  timestamp?: string | undefined;
  usage?: string | undefined;
};

export const UsageAnalyticPoint$zodSchema: z.ZodType<UsageAnalyticPoint> = z
  .object({
    buckets: z.array(PointBucket$zodSchema).optional().describe(
      "Buckets lists every commitment bucket this (possibly rolled-up) window\noverlaps — only populated when BreakdownBucket=true and the line item has\nCommitmentTimeBuckets. A coarse window can overlap more than one bucket, and\nonly partially, so this is a list. Empty when the window touches no bucket.\nIt is an informational HINT only: the point's single cost/computed_* totals\nmix all overlapped buckets and out-of-bucket time and CANNOT be split per\nbucket — read bucket_summaries for exact per-bucket cost.",
    ),
    computed_commitment_utilized_amount: z.string().optional().describe(
      "Commitment breakdown (only populated for windowed commitments)",
    ),
    computed_overage_amount: z.string().optional(),
    computed_true_up_amount: z.string().optional(),
    cost: z.string().optional().describe(
      "Cost is the final cost after discount (Subtotal - Discount)",
    ),
    discount: z.string().optional(),
    event_count: z.int().optional().describe(
      "Number of events in this time window",
    ),
    subtotal: z.string().optional(),
    timestamp: z.string().optional(),
    usage: z.string().optional(),
  });
