/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const UserType = {
  User: "user",
  ServiceAccount: "service_account",
} as const;
export type UserType = ClosedEnum<typeof UserType>;

export const UserType$zodSchema = z.enum([
  "user",
  "service_account",
]);
