/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { TenantResponse, TenantResponse$zodSchema } from "./tenantresponse.js";
import { UserType, UserType$zodSchema } from "./usertype.js";

export type UserResponse = {
  email?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  roles?: Array<string> | undefined;
  tenant?: TenantResponse | undefined;
  type?: UserType | undefined;
};

export const UserResponse$zodSchema: z.ZodType<UserResponse> = z.object({
  email: z.string().optional().describe("Empty for service accounts"),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  roles: z.array(z.string()).optional(),
  tenant: TenantResponse$zodSchema.optional(),
  type: UserType$zodSchema.optional(),
});
