/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Value = {
  array?: Array<string> | undefined;
  boolean?: boolean | undefined;
  date?: string | undefined;
  number?: number | undefined;
  string?: string | undefined;
};

export const Value$zodSchema: z.ZodType<Value> = z.object({
  array: z.array(z.string()).optional(),
  boolean: z.boolean().optional(),
  date: z.string().optional(),
  number: z.number().optional(),
  string: z.string().optional(),
});
