/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ErrorResponse, ErrorResponse$zodSchema } from "./errorresponse.js";
import {
  SuccessResponse,
  SuccessResponse$zodSchema,
} from "./successresponse.js";

export type VoidInvoiceRequest = { id: string };

export const VoidInvoiceRequest$zodSchema: z.ZodType<VoidInvoiceRequest> = z
  .object({
    id: z.string().describe("Invoice ID"),
  });

export type VoidInvoiceResponse = SuccessResponse | ErrorResponse;

export const VoidInvoiceResponse$zodSchema: z.ZodType<VoidInvoiceResponse> = z
  .union([
    SuccessResponse$zodSchema,
    ErrorResponse$zodSchema,
  ]);
