/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import {
  CustomerResponse,
  CustomerResponse$zodSchema,
} from "./customerresponse.js";
import { Status, Status$zodSchema } from "./status.js";
import {
  TransactionReason,
  TransactionReason$zodSchema,
} from "./transactionreason.js";
import {
  TransactionStatus,
  TransactionStatus$zodSchema,
} from "./transactionstatus.js";
import {
  TransactionType,
  TransactionType$zodSchema,
} from "./transactiontype.js";
import { UserResponse, UserResponse$zodSchema } from "./userresponse.js";
import { WalletResponse, WalletResponse$zodSchema } from "./walletresponse.js";
import {
  WalletTxReferenceType,
  WalletTxReferenceType$zodSchema,
} from "./wallettxreferencetype.js";

export type WalletTransactionResponse = {
  amount?: string | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  created_by_user?: UserResponse | undefined;
  credit_amount?: string | undefined;
  credit_balance_after?: string | undefined;
  credit_balance_before?: string | undefined;
  credits_available?: string | undefined;
  currency?: string | undefined;
  customer?: CustomerResponse | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  expiry_date?: string | undefined;
  id?: string | undefined;
  idempotency_key?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  priority?: number | undefined;
  reference_id?: string | undefined;
  reference_type?: WalletTxReferenceType | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  transaction_reason?: TransactionReason | undefined;
  transaction_status?: TransactionStatus | undefined;
  type?: TransactionType | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet?: WalletResponse | undefined;
  wallet_id?: string | undefined;
};

export const WalletTransactionResponse$zodSchema: z.ZodType<
  WalletTransactionResponse
> = z.object({
  amount: z.string().optional(),
  conversion_rate: z.string().optional().describe(
    "conversion_rate is the conversion rate for the transaction to the currency",
  ),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  created_by_user: UserResponse$zodSchema.optional(),
  credit_amount: z.string().optional(),
  credit_balance_after: z.string().optional(),
  credit_balance_before: z.string().optional(),
  credits_available: z.string().optional(),
  currency: z.string().optional(),
  customer: CustomerResponse$zodSchema.optional().describe(
    "Customer response object containing all customer information",
  ),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  expiry_date: z.iso.datetime({ offset: true }).optional(),
  id: z.string().optional(),
  idempotency_key: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  priority: z.int().optional(),
  reference_id: z.string().optional(),
  reference_type: WalletTxReferenceType$zodSchema.optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional().describe(
    "topup_conversion_rate is the conversion rate for the topup to the currency",
  ),
  transaction_reason: TransactionReason$zodSchema.optional(),
  transaction_status: TransactionStatus$zodSchema.optional(),
  type: TransactionType$zodSchema.optional(),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
  wallet: WalletResponse$zodSchema.optional(),
  wallet_id: z.string().optional(),
});
