/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type WalletTopupParams = {
  wallet_id: string;
  wallet_transaction_id?: string | undefined;
};

export const WalletTopupParams$zodSchema: z.ZodType<WalletTopupParams> = z
  .object({
    wallet_id: z.string(),
    wallet_transaction_id: z.string().optional(),
  });
