/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { AlertSettings, AlertSettings$zodSchema } from "./alertsettings.js";
import { AlertState, AlertState$zodSchema } from "./alertstate.js";
import { AutoTopup, AutoTopup$zodSchema } from "./autotopup.js";
import {
  CreditBreakdown,
  CreditBreakdown$zodSchema,
} from "./creditbreakdown.js";
import { Status, Status$zodSchema } from "./status.js";
import { WalletConfig, WalletConfig$zodSchema } from "./walletconfig.js";
import { WalletStatus, WalletStatus$zodSchema } from "./walletstatus.js";
import { WalletType, WalletType$zodSchema } from "./wallettype.js";

export type WalletResponse = {
  alert_settings?: AlertSettings | undefined;
  alert_state?: AlertState | undefined;
  auto_topup?: AutoTopup | undefined;
  balance?: string | undefined;
  config?: WalletConfig | undefined;
  conversion_rate?: string | undefined;
  created_at?: string | undefined;
  created_by?: string | undefined;
  credit_balance?: string | undefined;
  credits_available_breakdown?: CreditBreakdown | undefined;
  currency?: string | undefined;
  customer_id?: string | undefined;
  description?: string | undefined;
  environment_id?: string | undefined;
  id?: string | undefined;
  metadata?: { [k: string]: string } | undefined;
  name?: string | undefined;
  status?: Status | undefined;
  tenant_id?: string | undefined;
  topup_conversion_rate?: string | undefined;
  updated_at?: string | undefined;
  updated_by?: string | undefined;
  wallet_status?: WalletStatus | undefined;
  wallet_type?: WalletType | undefined;
};

export const WalletResponse$zodSchema: z.ZodType<WalletResponse> = z.object({
  alert_settings: AlertSettings$zodSchema.optional(),
  alert_state: AlertState$zodSchema.optional(),
  auto_topup: AutoTopup$zodSchema.optional(),
  balance: z.string().optional(),
  config: WalletConfig$zodSchema.optional(),
  conversion_rate: z.string().optional().describe(
    "amount in the currency =  number of credits * conversion_rate\nex if conversion_rate is 1, then 1 USD = 1 credit\nex if conversion_rate is 2, then 1 USD = 0.5 credits\nex if conversion_rate is 0.5, then 1 USD = 2 credits",
  ),
  created_at: z.iso.datetime({ offset: true }).optional(),
  created_by: z.string().optional(),
  credit_balance: z.string().optional(),
  credits_available_breakdown: CreditBreakdown$zodSchema.optional(),
  currency: z.string().optional(),
  customer_id: z.string().optional(),
  description: z.string().optional(),
  environment_id: z.string().optional(),
  id: z.string().optional(),
  metadata: z.record(z.string(), z.string()).optional(),
  name: z.string().optional(),
  status: Status$zodSchema.optional(),
  tenant_id: z.string().optional(),
  topup_conversion_rate: z.string().optional().describe(
    "topup_conversion_rate is the conversion rate for the topup to the currency\nex if topup_conversion_rate is 1, then 1 USD = 1 credit\nex if topup_conversion_rate is 2, then 1 USD = 0.5 credits\nex if topup_conversion_rate is 0.5, then 1 USD = 2 credits",
  ),
  updated_at: z.iso.datetime({ offset: true }).optional(),
  updated_by: z.string().optional(),
  wallet_status: WalletStatus$zodSchema.optional(),
  wallet_type: WalletType$zodSchema.optional(),
});
