/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const WalletType = {
  PrePaid: "PRE_PAID",
  PostPaid: "POST_PAID",
} as const;
export type WalletType = ClosedEnum<typeof WalletType>;

export const WalletType$zodSchema = z.enum([
  "PRE_PAID",
  "POST_PAID",
]);
