/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const WalletConfigPriceType = {
  All: "ALL",
  Usage: "USAGE",
  Fixed: "FIXED",
} as const;
export type WalletConfigPriceType = ClosedEnum<typeof WalletConfigPriceType>;

export const WalletConfigPriceType$zodSchema = z.enum([
  "ALL",
  "USAGE",
  "FIXED",
]);
