/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const WalletTxReferenceType = {
  Payment: "PAYMENT",
  External: "EXTERNAL",
  Request: "REQUEST",
  Invoice: "INVOICE",
} as const;
export type WalletTxReferenceType = ClosedEnum<typeof WalletTxReferenceType>;

export const WalletTxReferenceType$zodSchema = z.enum([
  "PAYMENT",
  "EXTERNAL",
  "REQUEST",
  "INVOICE",
]);
