/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../types/enums.js";

export const WindowSize = {
  Minute: "MINUTE",
  FifteenMIN: "15MIN",
  ThirtyMIN: "30MIN",
  Hour: "HOUR",
  ThreeHOUR: "3HOUR",
  SixHOUR: "6HOUR",
  TwelveHOUR: "12HOUR",
  Day: "DAY",
  Week: "WEEK",
  Month: "MONTH",
} as const;
export type WindowSize = ClosedEnum<typeof WindowSize>;

export const WindowSize$zodSchema = z.enum([
  "MINUTE",
  "15MIN",
  "30MIN",
  "HOUR",
  "3HOUR",
  "6HOUR",
  "12HOUR",
  "DAY",
  "WEEK",
  "MONTH",
]);
